SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ConceptoGastoInventariable2
AS
SELECT
Empresa,
Sucursal,
Concepto,
SUM(Cantidad) AS Cantidad,
SUM(Importe) AS Importe
FROM ConceptoGastoInventariable WITH (NOLOCK)
GROUP BY Empresa, Sucursal, Concepto

