SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ContParalelaDPolizaRegistrada

AS
SELECT
ID,
ContID,
ContMov,
ContMovID,
PolizaEstatus,
ContFechaEmision,
ContOrigenTipo,
ContOrigen,
ContOrigenID
FROM
ContParalelaD WITH (NOLOCK)
WHERE (PolizaEstatus = 'Registrada')

