SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW CxcPendienteWizard

AS
SELECT cp.*
FROM CxcPendiente cp WITH (NOLOCK)
JOIN MovTipo mt WITH (NOLOCK) ON mt.Modulo = 'CXC' AND mt.Mov = cp.Mov
WHERE mt.Clave NOT IN ('CXC.A')

