SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW CxpPendienteWizard

AS
SELECT cp.*
FROM CxpPendiente cp WITH (NOLOCK)
JOIN MovTipo mt WITH (NOLOCK) ON mt.Modulo = 'CXP' AND mt.Mov = cp.Mov
WHERE mt.Clave NOT IN ('CXP.A')

