SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW gCxcFacturaAnticipo
 AS
SELECT
ID,
CxcID,
Importe,
Sucursal,
SucursalOrigen
FROM CxcFacturaAnticipo WITH(NOLOCK)
UNION ALL
SELECT
ID,
CxcID,
Importe,
Sucursal,
SucursalOrigen
FROM hCxcFacturaAnticipo WITH(NOLOCK)
;

