SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW POSSaldoCaja

AS
SELECT plc.FormaPago, p.Caja,  SUM(plc.Importe * mt.Factor) Importe, SUM(plc.ImporteRef * mt.Factor) ImporteRef
FROM POSLCobro plc WITH(NOLOCK)
INNER JOIN POSL p WITH(NOLOCK) ON plc.ID = p.ID
INNER JOIN MovTipo mt WITH(NOLOCK) ON p.Mov = mt.Mov
AND mt.Modulo = 'POS'
WHERE  p.Estatus IN('CONCLUIDO','TRASPASADO')
GROUP BY plc.FormaPago, p.Caja

