SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW POSSerieLoteTemp2

AS
SELECT s.ID,  ISNULL(COUNT(s.SerieLote),0.0) SerieLote ,s.Articulo,s.SubCuenta,s.RenglonID
FROM POSLSerieLote s WITH(NOLOCK)
JOIN Art a WITH(NOLOCK) ON s.Articulo = a.Articulo
WHERE  a.Tipo IN('SERIE','LOTE')
GROUP BY s.ID  ,s.Articulo,s.SubCuenta,s.RenglonID

