SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ProdDExportacion AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,ID))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,Renglon))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.Renglon))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,RenglonSub))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.RenglonSub))) +
REPLICATE(' ',50)
OrdenExportacion,
ProdD.*,
Art.Descripcion1 Descripcion
FROM ProdD WITH(NOLOCK) JOIN Art WITH(NOLOCK)
ON ProdD.Articulo = Art.Articulo

