SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW SerieLoteMovINVExportacion AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,InvD.ID))))) + RTRIM(LTRIM(CONVERT(varchar,InvD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,InvD.Renglon))))) + RTRIM(LTRIM(CONVERT(varchar,InvD.Renglon))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,InvD.RenglonSub))))) + RTRIM(LTRIM(CONVERT(varchar,InvD.RenglonSub))) +
RTRIM(SerieLoteMov.SerieLote)
OrdenExportacion,
SerieLoteMov.*
FROM SerieLoteMov WITH(NOLOCK) JOIN InvD WITH(NOLOCK)
ON SerieLoteMov.ID = InvD.ID AND SerieLoteMov.RenglonID = InvD.RenglonID
WHERE SerieLoteMov.Modulo = 'INV'

