SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW SerieLoteMovPCExportacion AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,PCD.ID))))) + RTRIM(LTRIM(CONVERT(varchar,PCD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,PCD.Renglon))))) + RTRIM(LTRIM(CONVERT(varchar,PCD.Renglon))) +
RTRIM(SerieLoteMov.SerieLote)
OrdenExportacion,
SerieLoteMov.*
FROM SerieLoteMov WITH(NOLOCK) JOIN PCD WITH(NOLOCK)
ON SerieLoteMov.ID = PCD.ID AND SerieLoteMov.RenglonID = PCD.Renglon
WHERE SerieLoteMov.Modulo = 'PC'

