SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW SerieLoteMovPRODExportacion AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,ProdD.ID))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,ProdD.Renglon))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.Renglon))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,ProdD.RenglonSub))))) + RTRIM(LTRIM(CONVERT(varchar,ProdD.RenglonSub))) +
RTRIM(SerieLoteMov.SerieLote)
OrdenExportacion,
SerieLoteMov.*
FROM SerieLoteMov WITH(NOLOCK) JOIN ProdD WITH(NOLOCK)
ON SerieLoteMov.ID = ProdD.ID AND SerieLoteMov.RenglonID = ProdD.RenglonID
WHERE SerieLoteMov.Modulo = 'PROD'

