SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnIntelisisCFDIListaPAC
(
@Empresa			varchar(5)
)
RETURNS @Lista TABLE
(
Servidor		varchar(100)
)

AS BEGIN
DECLARE
@EsGuatemala			bit
SELECT @EsGuatemala = 0
IF @EsGuatemala = 0
INSERT @Lista (Servidor)
SELECT 'EDICOM'
UNION
SELECT 'SOLUCIONFACTIBLE'
UNION
SELECT 'FacturaInteligente'
UNION
SELECT 'InvoiceOne'
UNION
SELECT 'FormasDigitales'
UNION
SELECT 'eKomercio'
UNION
SELECT 'Aspel'
UNION
SELECT 'MASTEREDI'
UNION
SELECT 'FEL'
UNION
SELECT 'KONESH'
UNION
SELECT 'Levicom'
/*
UNION
SELECT 'FoliosDigitales'
UNION
SELECT 'ExpidetuFactura'
UNION
SELECT 'Servisim'
ELSE
INSERT @Lista (Servidor)
SELECT 'MYSUITEGUATEMALA'
*/
RETURN
END

