SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnListaTimbrarCFDIServidor
(
@Empresa			varchar(5)
)
RETURNS @Lista TABLE
(
Servidor		varchar(100)
)

AS BEGIN
DECLARE
@EsGuatemala			bit
SELECT @EsGuatemala = 0
SELECT @EsGuatemala = ISNULL(EsGuatemala,0) FROM Empresa WITH(NOLOCK) WHERE Empresa = @Empresa
IF @EsGuatemala = 0
INSERT @Lista (Servidor)
SELECT 'Aspel'
UNION
SELECT 'EDICOM'
UNION
SELECT 'SOLUCIONFACTIBLE'
UNION
SELECT 'MASTEREDI'
UNION
SELECT 'FEL'
UNION
SELECT 'KONESH'
UNION
SELECT 'Levicom'
UNION
SELECT 'INVOICEONE'
UNION
SELECT 'FacturaInteligente'
UNION
SELECT 'EKOMERCIO'
UNION
SELECT 'FormasDigitales'
ELSE
INSERT @Lista (Servidor)
SELECT 'MYSUITEGUATEMALA'
RETURN
END

