SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnListaCFD_tipoDeComprobante
(
@Empresa			varchar(5)
)
RETURNS @Lista TABLE
(
CFD_tipoDeComprobante		varchar(100)
)

AS BEGIN
DECLARE
@EsGuatemala			bit
SELECT @EsGuatemala = 0
SELECT @EsGuatemala = ISNULL(EsGuatemala,0) FROM Empresa WITH(NOLOCK) WHERE Empresa = @Empresa
IF @EsGuatemala = 0
INSERT @Lista (CFD_tipoDeComprobante)
SELECT 'ingreso'
UNION
SELECT 'egreso'
UNION
SELECT 'traslado'
ELSE
INSERT @Lista (CFD_tipoDeComprobante)
SELECT 'FACE63'
UNION
SELECT 'NCE64'
UNION
SELECT 'NDE65'
RETURN
END

