SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgArtComisionBC ON ArtComision

FOR UPDATE, DELETE
AS BEGIN
IF dbo.fnEstaSincronizando() = 1 RETURN
IF UPDATE(Tipo) OR UPDATE(Porcentaje) OR UPDATE(Importe)
INSERT ArtComisionHist (Comision, Fecha, Tipo, Porcentaje, Importe)
SELECT Comision, GETDATE(), Tipo, Porcentaje, Importe FROM Deleted
END

