SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgArtSubFamMes
ON ArtGrupo

FOR  INSERT, UPDATE, DELETE
AS
BEGIN
DELETE FROM ArtSubFamMes
WHERE Clave IN (SELECT ClaveMes FROM DELETED)
INSERT ArtSubFamMes (Clave, Descripcion, EstatusIntelIMES)
SELECT ClaveMES, Grupo, 0
FROM INSERTED
RETURN
END

