SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgDiaFestivoAC ON DiaFestivo

FOR INSERT, UPDATE
AS BEGIN
DECLARE
@Fecha		datetime,
@FechaSinHora	datetime
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @Fecha = Fecha FROM Inserted
SELECT @FechaSinHora = @Fecha
EXEC spExtraerFecha @FechaSinHora OUTPUT
UPDATE DiaFestivo SET Fecha = @FechaSinHora WHERE Fecha = @Fecha
END

