SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgEmbarqueDAC ON EmbarqueD

FOR INSERT, UPDATE
AS BEGIN
IF dbo.fnEstaSincronizando() = 1 RETURN
IF UPDATE(Paquetes) OR UPDATE(Observaciones)
UPDATE EmbarqueMov
SET Paquetes = i.Paquetes, ObservacionesEmbarque = i.Observaciones
FROM Inserted i, EmbarqueMov em
WHERE i.EmbarqueMov = em.ID
END

