SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgMenuBC ON Menu

FOR UPDATE, DELETE
AS BEGIN
DECLARE
@MenuN  	varchar(50),
@MenuA	varchar(50)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @MenuN = Menu FROM Inserted
SELECT @MenuA = Menu FROM Deleted
IF @MenuA = @MenuN RETURN
IF @MenuN IS NULL
BEGIN
DELETE MenuOpcion        WHERE Menu = @MenuA
DELETE UsuarioMenuOpcion WHERE Menu = @MenuA
END ELSE
BEGIN
UPDATE MenuOpcion        SET Menu = @MenuN WHERE Menu = @MenuA
UPDATE UsuarioMenuOpcion SET Menu = @MenuN WHERE Menu = @MenuA
END
END

