SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgMFATipoCtaAC ON MFATipoCta

AFTER INSERT, UPDATE
AS BEGIN
DECLARE
@CuentaN  		varchar(50),
@CuentaA  		varchar(50)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @CuentaN = Cuenta FROM Inserted
SELECT @CuentaA = Cuenta FROM Deleted
IF @CuentaN <> @CuentaA
UPDATE MFATipoCta SET Longitud = LEN(@CuentaN) WHERE Cuenta = @CuentaN
END

