SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgOfertaD ON OfertaD

FOR INSERT
AS BEGIN
DECLARE
@ID int,
@Mov varchar(20),
@MovTipo varchar(20),
@Estatus varchar(20)
SELECT @ID = ID FROM inserted
IF @ID IS NOT NULL
BEGIN
SELECT @Mov = Mov, @Estatus = Estatus FROM Oferta WHERE ID = @ID
SELECT @MovTipo = Clave FROM MovTipo WHERE Modulo = 'OFER' AND Mov = @Mov
IF @MovTipo = 'OFER.OM' AND @Estatus = 'SINAFECTAR'
IF (SELECT COUNT(Articulo) FROM OfertaD WHERE ID = @ID) > 1
RAISERROR('Este movimiento Solo Permite Usar Un Articulo', 16, -1)
END
END

