SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgPOSFechaCierreA ON POSFechaCierre

FOR INSERT
AS BEGIN
DECLARE
@SucursalA           int,
@FechaA              datetime
SELECT @SucursalA = Sucursal, @FechaA = Fecha FROM INSERTED
IF EXISTS (SELECT * FROM POSEstatusCajasCierre WHERE Sucursal = @SucursalA AND Fecha <> @FechaA)
UPDATE POSEstatusCajasCierre SET Fecha = @FechaA WHERE Sucursal = @SucursalA AND Fecha <> @FechaA
END

