SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgProdDAC ON ProdD

FOR INSERT, UPDATE
AS BEGIN
IF NOT UPDATE(Articulo) RETURN
DECLARE
@ID		int,
@Renglon	float,
@RenglonSub int
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @ID = MIN(ID), @Renglon = MIN(Renglon), @RenglonSub = MIN(RenglonSub) FROM Inserted WHERE NULLIF(RTRIM(Articulo), '') IS NULL
IF @ID IS NOT NULL AND @Renglon IS NOT NULL AND @RenglonSub IS NOT NULL
DELETE ProdD WHERE ID = @ID AND Renglon = @Renglon AND RenglonSub = @RenglonSub
END

