SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgRutaDistribucionBC ON RutaDistribucion

FOR UPDATE, DELETE
AS BEGIN
DECLARE
@RutaN	varchar(50),
@RutaA	varchar(50)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @RutaN = Ruta FROM Inserted
SELECT @RutaA = Ruta FROM Deleted
IF @RutaN = @RutaA RETURN
IF @RutaN IS NULL
DELETE RutaDistribucionD WHERE Ruta = @RutaA
ELSE
UPDATE RutaDistribucionD SET Ruta =  @RutaN WHERE Ruta = @RutaA
END

