SET DATEFIRST 7
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
SET ANSI_WARNINGS ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgSchemaInsert ON sx_schema
FOR INSERT
AS BEGIN
DECLARE
@Datos varchar(max)
SELECT @Datos = Script FROM Inserted
EXEC(@Datos)
END

