SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgTablaStBC ON TablaSt

FOR UPDATE, DELETE
AS BEGIN
DECLARE
@ClaveNueva  	varchar(50),
@ClaveAnterior	varchar(50)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @ClaveNueva    = TablaSt FROM Inserted
SELECT @ClaveAnterior = TablaSt FROM Deleted
IF @ClaveNueva = @ClaveAnterior RETURN
IF @ClaveNueva IS NULL
DELETE TablaStD WHERE TablaSt = @ClaveAnterior
ELSE
UPDATE TablaStD SET TablaSt = @ClaveNueva WHERE TablaSt = @ClaveAnterior
END

