SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgVersion ON Version

FOR INSERT, UPDATE
AS BEGIN
DECLARE
@Version	int,
@Fecha	datetime
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @Version = Version, @Fecha = Fecha FROM Inserted
IF NOT EXISTS(SELECT * FROM VersionLog WHERE Version = @Version)
INSERT VersionLog (Version, Fecha) VALUES (@Version, @Fecha)
END

