SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgVentaCobroC ON VentaCobro

FOR UPDATE
AS BEGIN
DECLARE
@Mensaje		varchar(255),
@ID			int,
@Actualizado	bit
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @ID = ID, @Actualizado = ISNULL(Actualizado, 0) FROM Inserted
IF @Actualizado = 0
BEGIN
IF (SELECT Estatus FROM Venta WHERE ID = @ID) IN ('PENDIENTE', 'PROCESAR', 'CONCLUIDO', 'CANCELADO')
BEGIN
SELECT @Mensaje = Descripcion FROM MensajeLista WHERE Mensaje = 60090
RAISERROR (@Mensaje,16,-1)
END
END
END

