SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgWebArtC ON WebArt

FOR UPDATE
AS BEGIN
DECLARE
@IDI          int,
@IDVarI       int,
@IDB          int,
@IDVarB       int
SELECT @IDI = ID,@IDVarI = VariacionID FROM INSERTED
SELECT @IDB = ID,@IDVarB = VariacionID FROM DELETED
IF   @IDVarI <>@IDVarB
DELETE WebArtVariacionCombinacion
WHERE IDArt = @IDI
END

