SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgWebSituacionAC ON WebSituacion

FOR INSERT,UPDATE
AS BEGIN
DECLARE @NombreN varchar(255)
DECLARE crNombre CURSOR local FOR
SELECT Nombre FROM INSERTED
OPEN crNombre
FETCH NEXT FROM crNombre INTO @NombreN
WHILE @@FETCH_STATUS = 0
BEGIN
IF(ISNULL(@NombreN, '') = '')
BEGIN
RAISERROR('El campo Nombre no puede estar vacio', 16, -1)
END
FETCH NEXT FROM crNombre INTO @NombreN
END
CLOSE crNombre
DEALLOCATE crNombre
END

