SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgWebSitioBC ON WebSitio

FOR UPDATE, DELETE
AS BEGIN
DECLARE
@SitioA	varchar(20),
@SitioN	varchar(20)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @SitioA = Sitio FROM Deleted
SELECT @SitioN = Sitio FROM Inserted
IF @SitioA = @SitioN RETURN
IF @SitioN IS NULL
BEGIN
DELETE WebSitioD   WHERE Sitio = @SitioA
DELETE WebSitioDoc WHERE Sitio = @SitioA
END ELSE
BEGIN
UPDATE WebSitioD   SET Sitio = @SitioN WHERE Sitio = @SitioA
UPDATE WebSitioDoc SET Sitio = @SitioN WHERE Sitio = @SitioA
UPDATE WebPagina   SET Sitio = @SitioN WHERE Sitio = @SitioA
END
END

