SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER TRIGGER tgZonaBC ON Zona

FOR UPDATE, DELETE
AS BEGIN
DECLARE
@ZonaN  	varchar(50),
@ZonaA	varchar(50),
@Mensaje	varchar(255)
IF dbo.fnEstaSincronizando() = 1 RETURN
SELECT @ZonaN = Zona FROM Inserted
SELECT @ZonaA = Zona FROM Deleted
IF @ZonaN = @ZonaA RETURN
IF @ZonaN IS NULL AND
EXISTS(SELECT * FROM Cte WHERE Zona = @ZonaA) OR
EXISTS(SELECT * FROM CteEnviarA WHERE Zona = @ZonaA) OR
EXISTS(SELECT * FROM Ruta WHERE Zona = @ZonaA)
BEGIN
SELECT @Mensaje = '"'+LTRIM(RTRIM(@ZonaA))+ '" ' + Descripcion FROM MensajeLista WHERE Mensaje = 30155
RAISERROR (@Mensaje,16,-1)
END ELSE
IF @ZonaA IS NOT NULL
BEGIN
UPDATE Cte SET Zona = @ZonaN WHERE Zona = @ZonaA
UPDATE CteEnviarA SET Zona = @ZonaN WHERE Zona = @ZonaA
UPDATE Ruta SET Zona = @ZonaN WHERE Zona = @ZonaA
END
END

