SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fn_clase_cuenta (@clase_cuenta varchar(50))
RETURNS nvarchar(1)
AS BEGIN
RETURN
CASE LOWER(@clase_cuenta)
WHEN 'control'  THEN N'C'
WHEN 'registro' THEN N'R'
ELSE NULL
END
END

