SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fn_tipoope (@tipo_operacion varchar(50))
RETURNS varchar(10)
AS BEGIN
RETURN
CASE LOWER(@tipo_operacion)
WHEN 'prestacion_servicios'		THEN '03'
WHEN 'arrendamiento_inmuebles'	THEN '06'
WHEN 'otros'						THEN '85'
END
END

