SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnCanalesCte(@Cadena VARCHAR(50))
RETURNS VARCHAR(50)
AS
BEGIN
DECLARE @CadenaR	VARCHAR(50)
IF @Cadena IN (SELECT DISTINCT Categoria
FROM Cte WITH (NOLOCK)
WHERE Categoria IS NOT NULL
AND Categoria NOT LIKE ''
AND Categoria NOT IN ('E-TAIL','RETAIL','Installers'))
SET @CadenaR='IT'
ELSE
BEGIN
IF @Cadena='Installers'
SET @CadenaR='INSTALLERS'
ELSE
BEGIN
IF @Cadena IN (SELECT DISTINCT Categoria
FROM Cte WITH (NOLOCK)
WHERE Categoria IS NOT NULL
AND Categoria NOT LIKE ''
AND Categoria IN ('E-TAIL','RETAIL'))
SET @CadenaR=REPLACE(@Cadena,'-','')
ELSE
BEGIN
IF @Cadena NOT IN (SELECT DISTINCT Categoria
FROM Cte WITH (NOLOCK)
WHERE Categoria IN ('ETAIL','RETAIL','Installers'))
SET @CadenaR='IT'
ELSE
BEGIN
IF @Cadena='Installers'
SET @CadenaR='INSTALLERS'
ELSE
BEGIN
IF @Cadena IN (SELECT DISTINCT Categoria
FROM Cte WITH (NOLOCK)
WHERE Categoria IN ('ETAIL','RETAIL'))
SET @CadenaR=@Cadena
END
END
END
END
END
RETURN @CadenaR
END

