SET DATEFIRST 7    
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
SET ANSI_WARNINGS ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnDirectorioEliminarDiagonalFinal(
@Directorio			varchar(255))
RETURNS varchar(255)
AS
BEGIN
IF RIGHT(@Directorio, 1) = '\'
SELECT @Directorio = SUBSTRING(@Directorio, 1, LEN(@Directorio) - 1)
RETURN @Directorio
END

