SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fneDocEsNumero
(
@Resultado        varchar(4)
)
RETURNS varchar(100)
AS
BEGIN
IF ISNUMERIC(@Resultado) = 0
SET @Resultado = NULL
RETURN (@Resultado)
END

