SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnEmidaNivelCfgSiteID(
@Empresa	varchar(5)
)
RETURNS varchar(10)
AS
BEGIN
RETURN(SELECT NivelCfgSiteID FROM EmidaCfg WITH(NOLOCK) WHERE Empresa = @Empresa)
END

