SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnPOSValidarCteMost (
@Cliente		varchar(10)
)
RETURNS bit

AS
BEGIN
DECLARE
@Resultado		bit,
@RFC			varchar(15)
SELECT @RFC = NULLIF(RFC,'')
FROM Cte WITH(NOLOCK)
WHERE Cliente = @Cliente
SET @Resultado = 1
IF NULLIF(@RFC,'') IS NOT NULL
SET @Resultado = 0
IF @Resultado = 1
BEGIN
IF EXISTS (SELECT * FROM POSCteFacCred WITH(NOLOCK) WHERE Cliente = @Cliente)
SET @Resultado = 0
END
RETURN (@Resultado)
END

