SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnPOSAbrirCajon (
@ID   varchar(36)
)
RETURNS bit

AS
BEGIN
DECLARE
@Resultado            bit
SELECT @Resultado    = 0
IF EXISTS(SELECT * FROM POSLCobro c WITH(NOLOCK) JOIN FormaPago f WITH(NOLOCK) ON f.FormaPago = c.FormaPago WHERE   f.AbreCajon = 1 AND c.ID = @ID)
AND EXISTS(SELECT * FROM POSReporteTicket WITH(NOLOCK) WHERE RID = @ID AND AbreCajon = 1)
SELECT @Resultado = 1
RETURN (@Resultado)
END

