SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnPOSValidarBloquearCaja (
@Codigo varchar(36)
)
RETURNS bit

AS
BEGIN
DECLARE
@Resultado bit
SELECT @Resultado = 0
IF (SELECT Accion FROM CB WITH(NOLOCK) WHERE Codigo = @Codigo) IN ('DESBLOQUEAR CAJA')
SELECT @Resultado = 1
RETURN (@Resultado)
END

