SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnPOSCalculaMoratoriosPagados (
@Mov		varchar(20),
@MovID		varchar(20)
)
RETURNS float

AS
BEGIN
RETURN(SELECT ISNULL(SUM(d.DescuentoRecargos),0)
FROM POSHistMoratorios m WITH(NOLOCK) JOIN CxcD d WITH(NOLOCK) ON m.IDGenerado = d.ID
WHERE d.Aplica = @Mov AND d.AplicaID = @MovID)
END

