SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnPOSValidarCteExpress (
@RFC	varchar(15)
)
RETURNS int

AS
BEGIN
DECLARE
@Resultado  int
SET @Resultado = NULL
IF EXISTS(SELECT * FROM Cte WITH(NOLOCK) WHERE RFC = @RFC AND @RFC NOT IN ('XAXX010101000', 'XEXX010101000'))
SELECT @Resultado = 1
RETURN (@Resultado)
END

