SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnSincroISTablaConCampoIdentity
(
@Tabla				varchar(50)
)
RETURNS bit

AS BEGIN
DECLARE
@Resultado	bit
IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMNPROPERTY(OBJECT_ID(TABLE_NAME),COLUMN_NAME,'IsIdentity') = 1 AND TABLE_NAME = @Tabla) SET @Resultado = 1 ELSE SET @Resultado = 0
RETURN (@Resultado)
END

