SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnTMATarimaOriginal (@Tarima varchar(20))
RETURNS varchar(20)

AS BEGIN
DECLARE
@LEN	int
IF @Tarima LIKE '%-%'
BEGIN
SELECT @LEN = LEN(@Tarima)
WHILE SUBSTRING(@Tarima,@LEN,1) <> '-'
SELECT @LEN = @LEN -1
SELECT @Tarima = SUBSTRING(@Tarima,1, @LEN-1)
END
RETURN(@Tarima)
END

