SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnUsuarioACorreo
(
@Usuario					varchar(10)
)
RETURNS varchar(255)

AS BEGIN
DECLARE
@Correo				varchar(255),
@Personal				varchar(10)
SET @Correo = ''
SELECT @Correo = ISNULL(eMail,''), @Personal = Personal FROM Usuario WITH(NOLOCK) WHERE Usuario = @Usuario
IF NULLIF(@Correo,'') IS NULL SELECT @Correo = ISNULL(eMail,'') FROM Personal WITH(NOLOCK) WHERE Personal = @Personal
RETURN (@Correo)
END

