SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnXMLValor2 (@Valor varchar(8000))
RETURNS varchar(8000)

AS BEGIN
SELECT @Valor = dbo.fnQuitarDoblesEspacios(@Valor)
SELECT @Valor = NULLIF(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@Valor, '&', ''), '<', ''), '>', ''), '"', ''), '''', ''))),'')
RETURN (@Valor)
END

