SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnXMLParametro (@Parametro varchar(max))
RETURNS varchar(max)

AS BEGIN
DECLARE
@Resultado	varchar(max)
SELECT @Resultado = REPLACE(@Parametro, ' ', '_')
IF dbo.fnEsNumerico(SUBSTRING(@Resultado, 1, 1)) = 1 SELECT @Resultado = '_' + @Resultado
RETURN(@Resultado)
END

