SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fn_CanalesCte(@Cadena VARCHAR(50))
RETURNS VARCHAR(50)
AS
BEGIN
DECLARE @resultado	VARCHAR(50)
SET @resultado=(SELECT Valor
FROM TablaSTD ts
WHERE ts.TablaSt='CategoriasArts'
AND ts.Nombre=@Cadena)
RETURN @resultado
END

