SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fn_emisor (@tipo_aplicacion varchar(50))
RETURNS varchar(50)
AS BEGIN
RETURN
CASE LOWER(@tipo_aplicacion)
WHEN 'cobro' THEN 'terceros'
WHEN 'pago'  THEN 'empresa'
ELSE NULL
END
END

