SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fn_r3 (@si_1 float, @entonces_1 float, @si_2 float)
RETURNS float
AS BEGIN
RETURN (ISNULL(@si_2, 0.0) * ISNULL(@entonces_1, 0.0)) / NULLIF(@si_1, 0.0)
END

