SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION [dbo].[fnAspelJustificadocto] (@Docto VARCHAR(20))
RETURNS VARCHAR(8) AS
BEGIN
DECLARE
@Nuevodocto	varchar(8)
IF ISNUMERIC(@Docto) = 1 AND LEFT(@Docto,1) <> '0'
BEGIN
SET @Nuevodocto = RIGHT('0000000' + @Docto, 7)
END
ELSE
IF ISNUMERIC(@Docto) = 1 AND len(@Docto) = 7 AND LEFT(@Docto,1) = '0' 
SET @Nuevodocto= '0' +  @Docto
ELSE
SET @Nuevodocto =  @Docto
RETURN(@Nuevodocto)
END

