SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnCentrar (@Texto varchar(max), @Espacio int)
RETURNS varchar(max)

AS BEGIN
IF LEN(@Texto)>@Espacio SELECT @Texto = SUBSTRING(@Texto, 1, @Espacio)
RETURN(SPACE((@Espacio-LEN(@Texto))/2)+@Texto)
END

