SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnClaveAfectacionMAVI(
@Mov		varchar(20),
@Modulo		varchar(5)
)
RETURNS varchar(20)
AS
BEGIN
DECLARE
@Clave		varchar(20)
SET @Clave = NULL
SELECT @Clave = Clave
FROM MovTipo
WHERE Modulo = @Modulo AND Mov = @Mov
SELECT @Clave = RTRIM(@Clave)
RETURN (@Clave)
END

