SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnContarLetras
(
@Texto				varchar(100),
@Letra				varchar(1)
)
RETURNS int

AS BEGIN
RETURN  (LEN(@Texto) - LEN(REPLACE(@Texto, @Letra, '')))
END

