SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnCtoTabla (@Tipo varchar(20))
RETURNS varchar(50)

AS BEGIN
DECLARE
@Tabla	varchar(50)
SELECT @Tabla = NULL
SELECT @Tabla = CASE @Tipo
WHEN 'Cliente'   THEN 'Cte'
WHEN 'Proveedor' THEN 'Prov'
WHEN 'Almacen'   THEN 'Alm'
WHEN 'Articulo'	 THEN 'Art'
ELSE @Tipo
END
RETURN (@Tabla)
END

