SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnDividirHora (@Hora varchar(5), @Parte char(1))
RETURNS int

AS BEGIN
IF UPPER(@Parte) = 'M' RETURN(CONVERT(int, SUBSTRING(@Hora, 4, 2)))
ELSE IF UPPER(@Parte) = 'H' RETURN(CONVERT(int, SUBSTRING(@Hora, 1, 2)))
RETURN(-1)
END

