SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnDineroEsPagoEmida(
@ModuloID		int)
RETURNS int
AS
BEGIN
DECLARE @Valor	int
SELECT @Valor = COUNT(c.ID)
FROM DineroD Dd
JOIN Dinero D ON Dd.Aplica = D.Mov AND Dd.AplicaID = D.MovID
JOIN MovImpuesto m ON m.Modulo = 'DIN' AND m.ModuloID = D.ID AND m.OrigenModulo = 'CXP'
JOIN Cxp c ON m.OrigenModuloID = c.ID
JOIN MovTipo mt ON c.Mov = mt.Mov AND mt.Modulo = 'CXP' AND ISNULL(mt.SubClave, '') = 'CXP.AEMIDA'
WHERE Dd.ID = @ModuloID
RETURN @Valor
END

