SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnEsPitex (@Cliente varchar(20))
RETURNS bit

AS BEGIN
DECLARE @Espitex bit, @Pitex varchar(20)
SELECT @EsPitex = 0, @Pitex = NULL
SELECT @Pitex = NULLIF(RTRIM(Pitex),'') FROM Cte WHERE Cliente = @Cliente
IF @Pitex IS NOT NULL
SELECT @EsPitex = 1
RETURN(@EsPitex)
END

