SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fneWebVerificarWebArtMarca
(@ID   int)
RETURNS varchar(255)

AS BEGIN
DECLARE
@Resultado  varchar(255)
SET @Resultado = NULL
IF EXISTS(SELECT * FROM WebArt WHERE MarcaID = @ID )SET @Resultado = 'Tiene Articulos Asociados, No se Puede Eliminar'
RETURN(@Resultado)
END

