SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fneWebConvertirDescripcionHTML
(@Texto   varchar(MAX))
RETURNS varchar(MAX)

AS BEGIN
DECLARE
@Resultado  varchar(MAX)
SELECT @Resultado = REPLACE(LTRIM(RTRIM(@Texto)),'&','&#038;')
SELECT @Resultado = REPLACE(REPLACE(REPLACE(REPLACE(@Resultado,'<','&#060;'),'>','&#062;'),CHAR(34),'&#034;'),'=','&#061;')
RETURN(@Resultado)
END

