SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fneWebValidarNombre
(@Nombre   varchar(255))
RETURNS bit

AS BEGIN
DECLARE
@Resultado  bit
SET @Resultado = 1
IF NULLIF(@Nombre,'') IS NULL
SET @Resultado = 0
RETURN(@Resultado)
END

