SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnExtencionArchivo
(@Archivo varchar(255))
RETURNS varchar(50)

AS BEGIN
DECLARE
@Extension varchar(255),
@Posicion  int
SELECT @Posicion = CASE (CHARINDEX('.', @Archivo))
WHEN 0 THEN -1
ELSE LEN(@Archivo) - CHARINDEX('.', REVERSE(@Archivo)) +1
END
SET	@Extension = SUBSTRING(@Archivo, @Posicion, LEN(@Archivo))
RETURN (@Extension)
END

