SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnExtraerClaveID (@Clave varchar(20))
RETURNS int

AS BEGIN
DECLARE
@p	int,
@c	char(1),
@ID	varchar(20)
SELECT @ID = ''
SELECT @p = LEN(@Clave)
WHILE @p > 0
BEGIN
SELECT @c = SUBSTRING(@Clave, @p, 1)
IF (@c <> '.') AND dbo.fnEsNumerico(@c) = 1 SELECT @ID = @c + @ID ELSE BREAK
SELECT @p = @p - 1
END
RETURN (NULLIF(CONVERT(int, @ID), 0))
END

