SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnFechaUltimaCompra
(
@Articulo       VARCHAR(20),
@Almacen        VARCHAR(20)
)
RETURNS DATETIME
AS
BEGIN
DECLARE
@Fecha          DATETIME
SELECT TOP 1 @Fecha = FechaEmision
FROM Compra c
JOIN CompraD cd ON c.ID = cd.ID
JOIN MovTipo mt ON c.Mov = mt.Mov AND 'COMS' = mt.Modulo
WHERE c.Estatus = 'CONCLUIDO' AND mt.Clave IN ('COMS.F', 'COMS.EI', 'COMS.EG') AND cd.Articulo = @Articulo AND c.Almacen = @Almacen
ORDER BY c.ID DESC
RETURN (@Fecha)
END

