SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnFolioConsecutivo
(
@MovID				varchar(20)
)
RETURNS varchar(20)

AS BEGIN
DECLARE
@Folio	varchar(20),
@p		int
SELECT @p = LEN(@MovID)
WHILE @p >= 1 AND dbo.fnEsNumerico(SUBSTRING(@MovID, @p, 1)) = 1
SELECT @p = @p - 1
SELECT @Folio = RTRIM(SUBSTRING(@MovID, @p+1, LEN(@MovID)))
RETURN (@Folio)
END

