SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnIDLocalModulo (@Modulo varchar(5), @SucursalRemota int, @IDRemoto int)
RETURNS int

AS BEGIN
DECLARE
@Tabla varchar(100)
SELECT @Tabla = dbo.fnSincroISMovTabla(@Modulo)
RETURN(dbo.fnIDLocal(@Tabla, @SucursalRemota, @IDRemoto))
END

