SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnIDLocal (@Tabla varchar(100), @SucursalRemota int, @IDRemoto int)
RETURNS int

AS BEGIN
RETURN(SELECT IDLocal FROM IDLocal WHERE Tabla = @Tabla AND SucursalRemota = @SucursalRemota AND IDRemoto = @IDRemoto)
END

