SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnInvCapaExistenciaPorFecha (@ID int, @FechaA datetime)
RETURNS float
AS
BEGIN
DECLARE @Existencia float
SELECT @Existencia = ISNULL(SUM(ISNULL(CargoU,0)) - SUM(ISNULL(AbonoU,0)),0)
FROM InvCapaAux
WHERE ID = @ID
AND Fecha < @FechaA
RETURN (@Existencia)
END

