SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnMFAIEPSIVA(
@Empresa		varchar(5),
@DefImpuesto	float,
@IVATasa		float,
@IEPS			float
)
RETURNS float
AS
BEGIN
DECLARE @Valor	float
IF @DefImpuesto = @IVATasa
SELECT @Valor = @IEPS * (@DefImpuesto/100)
ELSE
SELECT @Valor = 0
RETURN @Valor
END

