SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnPCPCatalogoTipoRama
(
@Proyecto				varchar(50),
@CatalogoTipo			varchar(50)
)
RETURNS varchar(50)

AS BEGIN
DECLARE
@Resultado	varchar(50)
SELECT @Resultado = ISNULL(Rama,'') FROM ClavePresupuestalCatalogoTipo WHERE RTRIM(Proyecto) = RTRIM(@Proyecto) AND Tipo = RTRIM(@CatalogoTipo)
RETURN (@Resultado)
END

