SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.fnPOSValidarMonedero(
@Monedero  varchar(20)
)
RETURNS varchar(100)

AS
BEGIN
DECLARE
@Resultado  varchar(100)
IF EXISTS(SELECT * FROM POSValeSerie WHERE Serie = @Monedero AND Estatus = 'CANCELADO')
SELECT @Resultado = 'Monedero Cancelado '
ELSE
SELECT @Resultado = NULL
RETURN (@Resultado)
END

