SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnRedondeoDecimales(@Empresa Varchar(5))
RETURNS int

AS BEGIN
RETURN (SELECT DecimalesCantidades FROM EmpresaGral WHERE Empresa = @Empresa)
END

