SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnTipoContactoEspecifico (@ContAutoContactoEsp varchar(50), @TipoContacto varchar(20))
RETURNS varchar(10)

AS BEGIN
DECLARE
@Resultado varchar(20)
SELECT @Resultado = NULL
SELECT @Resultado =
CASE UPPER(@ContAutoContactoEsp)
WHEN 'AGENTE'			THEN 'Agente'
WHEN 'PERSONAL'		THEN 'Personal'
WHEN 'CUENTA DINERO'		THEN 'Cuenta Dinero'
WHEN 'CUENTA DINERO DESTINO'   THEN 'Cuenta Dinero'
WHEN 'ALMACEN'			THEN 'Almacen'
WHEN 'ALMACEN DESTINO'		THEN 'Almacen'
WHEN 'ALMACEN DETALLE'		THEN 'Almacen'
ELSE @TipoContacto
END
RETURN(@Resultado)
END

