SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnTipoCambioCompra
(
@Moneda				varchar(10)
)
RETURNS float

AS BEGIN
DECLARE
@TipoCambio	float
SELECT @TipoCambio = ISNULL(TipoCambioCompra,TipoCambio) FROM Mon WHERE Moneda = @Moneda
RETURN (@TipoCambio)
END

