SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnVentaDArticulo (@ID int, @Renglon float)
RETURNS varchar(20)

AS BEGIN
DECLARE
@Articulo  varchar(20)
SELECT @Articulo = CASE ISNULL(vcfdTipoOperacion,'') WHEN 'A' THEN NULL ELSE CFDVentaD.VentaDArticulo END
FROM CFDVentaD JOIN CFDVenta ON CFDVentaD.ID = CFDVenta.ID
WHERE CFDVentaD.ID = @ID AND CFDVentaD.VentaDRenglon = @Renglon
RETURN(@Articulo)
END

