SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION fnWebArtVariacionTieneWebArt
(@ID   int)
RETURNS bit
AS BEGIN
DECLARE @Return bit
IF EXISTS(SELECT TOP 1 ID FROM WebArt WHERE VariacionID = @ID)
SELECT @Return = 1
ELSE
SELECT @Return = 0
RETURN @Return
END

