SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION dbo.funcWeb2UnixToDate
( @UNIX_TIME int )
RETURNS  datetime
AS
BEGIN
RETURN  	dateadd(ss,@UNIX_TIME,25567)
END

