SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION JSON2XML
(
@JSON VARCHAR(MAX)
)
RETURNS XML
AS
BEGIN
DECLARE @XML XML
SET @XML = CAST(dbo.CLRJSONTOXML(@JSON) AS XML)
RETURN @XML
END

