SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER FUNCTION [dbo].[XML2JSON]
(
@XML XML
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
DECLARE @JSON NVARCHAR(MAX)
SET @JSON = dbo.CLRXMLTOJSON(CAST(@XML AS NVARCHAR(MAX)))
RETURN @JSON
END

