SET DATEFIRST 7
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET ANSI_WARNINGS ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE  spAspelBorraPropReg

AS
BEGIN
TRUNCATE TABLE AspelCargaProp
TRUNCATE TABLE AspelCargaReg
UPDATE Aspel_Paso SET
IntegracionVisor = 0
END

