SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spBorrarTabla
@Tabla	varchar(50)

AS BEGIN
if exists (select * from sysobjects where id = object_id('dbo.'+@Tabla) and type = 'U')
BEGIN
IF RTRIM(LTRIM(@Tabla)) = 'Tarima'
BEGIN
EXEC('DELETE T FROM ' + @Tabla + ' T JOIN AlmPos A ON T.Posicion = A.Posicion AND T.Almacen = A.Almacen WHERE A.Tipo <> ''Domicilio'' ')
END
IF RTRIM(LTRIM(@Tabla)) = 'Inv'
BEGIN
ALTER TABLE Inv DISABLE TRIGGER tgInvB
EXEC("DELETE "+@Tabla)
ALTER TABLE Inv ENABLE TRIGGER tgInvB
END
IF RTRIM(LTRIM(@Tabla)) NOT IN ('Tarima','Inv')
BEGIN
BEGIN TRAN TR1
BEGIN
EXEC("DISABLE TRIGGER ALL ON "+@Tabla)
EXEC("DELETE "+@Tabla)
IF (SELECT VERSION FROM VERSION) >= 1140 EXEC("spSincroSemilla "+@Tabla)
EXEC("ENABLE TRIGGER ALL ON "+@Tabla)
END
COMMIT TRAN TR1
END
END
END

