SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC  dbo.spCotizacionVtas
@ID   INT

AS
BEGIN
CREATE TABLE  #COTIZACIONPRE(
INDICE				INT IDENTITY(1,1),
ID					INT,
RENGLON				FLOAT,
ORDENREPORTE		FLOAT NULL,
EMPRESANOMBRE		VARCHAR(100) NULL,
EMPRESADIRECCION	VARCHAR(250) NULL,
CLIENTE				VARCHAR(10) NULL,
CTENOMBRE			VARCHAR(100) NULL,
CTEDIRECCION		VARCHAR(250) NULL,
CTEENVNOMBRE		VARCHAR(100) NULL,
CTEENVDIRECCION		VARCHAR(250) NULL,
ARTICULO			VARCHAR(20) NULL,
DESCRIPCION1		VARCHAR(100) NULL,
DESCRIPCION2		VARCHAR(255) NULL,
CANTIDAD			FLOAT  NULL,
PRECIO				MONEY NULL,
PCFDIAS				INT NULL,
IMPORTE				MONEY NULL,
IMPORTEVTA			MONEY NULL,
IMPUESTOVTA			MONEY NULL,
TIPO				VARCHAR(100) NULL,
COLOR				INT NULL,
MOV					VARCHAR(70)NULL,
FECHAEMISION		DATETIME NULL,
ATENCION			VARCHAR (100) NULL,
VTASOBSER			VARCHAR(100) NULL,
ENVIAR				INT NULL,
CONCEPTO			VARCHAR (100) NULL,
descuento			MONEY  NULL,
nameagent			VARCHAR(100) NULL,
TIPONOMBRE			VARCHAR(100) NULL
)
DECLARE @DIASENCABEZADO INT,
@DIASTEXTO	VARCHAR(40),
@DESCUENTO  MONEY,
@fechad		DATETIME,
@fechaa		DATETIME,
@dias		INT,
@meses		INT,
@diasletra  VARCHAR(5),
@mesesletra VARCHAR(5)
SELECT @fechad = VigenciaDesde, @fechaa = VigenciaHasta FROM Venta WHERE id = @id
SELECT @meses = FLOOR((DATEDIFF(DAY, @fechad, @fechaa) + 1) / 30)
SELECT @dias = DATEDIFF(DAY, @fechad, @fechaa) + 1
SELECT @diasletra = CONVERT (VARCHAR(5), @dias)
SELECT @mesesletra = CONVERT (VARCHAR(5), @meses)
SELECT @DESCUENTO = SUM(ISNULL(DESCUENTOSTOTALES, 0)) FROM VENTATCALC WHERE ID = @ID
SELECT @DIASENCABEZADO = 0 
SELECT @DIASTEXTO = @diasletra + CASE WHEN @dias = 1 THEN ' DIA ' ELSE ' DIAS ' END + CASE WHEN @meses = 0 THEN '' ELSE ' EN ' + @mesesletra + CASE WHEN @meses = 1 THEN 'MES' ELSE ' MESES ' END END
INSERT INTO #COTIZACIONPRE (ID, RENGLON, ORDENREPORTE, EMPRESANOMBRE, EMPRESADIRECCION, CLIENTE, CTENOMBRE, CTEDIRECCION, CTEENVNOMBRE, CTEENVDIRECCION, ARTICULO, DESCRIPCION1, DESCRIPCION2, CANTIDAD, PRECIO,
IMPORTE, IMPORTEVTA, IMPUESTOVTA, TIPO, COLOR, MOV, FECHAEMISION, ATENCION, VTASOBSER, ENVIAR, CONCEPTO, descuento, nameagent, TIPONOMBRE)
SELECT V.ID, D.RENGLON, 1.1, E.NOMBRE, ISNULL(E.DIRECCION, '') + '  ' + ISNULL(E.DireccionNumero, '') + '  ' + ISNULL(E.DIRECCIONNUMEROINT, '') + ISNULL(E.Colonia, '') + ' ' + ISNULL(E.CodigoPostal, ''),
C.CLIENTE, C.nombre, ISNULL(c.DIRECCION, '') + '  ' + ISNULL(c.DireccionNumero, '') + '  ' + ISNULL(c.DIRECCIONNUMEROINT, '') + ISNULL(c.Colonia, '') + ' ' + ISNULL(c.CodigoPostal, ''),
ISNULL(T.nombre, ''), ISNULL(T.DIRECCION, '') + '  ' + ISNULL(T.DireccionNumero, '') + '  ' + ISNULL(T.DIRECCIONNUMEROINT, '') + ISNULL(T.Colonia, '') + ' ' + ISNULL(T.CodigoPostal, ''),
a.articulo, CASE WHEN a.Categoria = 'NO EXISTE' THEN ISNULL(D.DescripcionExtra, 'ESCRIBE EN EL CAMPO OBSERVACIONES') ELSE A.DESCRIPCION1 END, SPACE(25) + SUBSTRING(A.Descripcion2, 1, 120), D.CANTIDAD, D.PRECIO,
D.CANTIDAD * D.PRECIO * 0,V.IMPORTE, V.Impuestos, '', 0, V.MOV + ' ' + V.MOVID, V.FECHAEMISION, V.ATENCION, V.OBSERVACIONES, V.EnviarA, V.Concepto, @DESCUENTO, gn.Nombre, ''
FROM Venta V
LEFT OUTER JOIN VentaD D		ON	V.ID = D.ID
LEFT OUTER JOIN Cte C			ON	V.Cliente =C.Cliente
LEFT OUTER JOIN CteEnviarA T	ON	V.Cliente = T.Cliente AND V.EnviarA = T.ID
LEFT OUTER JOIN Empresa E       ON	V.Empresa = E.Empresa
LEFT OUTER JOIN Art a			ON	D.Articulo = A.Articulo
LEFT OUTER JOIN Agente gn       ON	v.Agente = gn.Agente
WHERE V.ID = @ID
CREATE TABLE #OBSERVA1(
INDICE	INT IDENTITY(2,2),
ASUNTO  VARCHAR(250) NULL,
TIPO	VARCHAR(100) NULL
)
CREATE TABLE #OBSERVA2 (
INDICE			INT IDENTITY(1,1),
IDVTAS			INT,
ASUNTO			VARCHAR(255) NULL,
TIPO			VARCHAR(100) NULL,
TIPOANTERIOR	VARCHAR(100) NULL,
COLOR			INT NULL
)
DECLARE @ASUNTO	VARCHAR(255),
@TIPO			VARCHAR(100),
@TIPOANTERIOR	VARCHAR(100),
@GRIS			INT,
@BLANCO			INT,
@COLORANTERIOR	INT
SELECT @GRIS = 1, @BLANCO = 0, @COLORANTERIOR = 0
DECLARE GRIS_BLANCO
CURSOR FOR
SELECT ASUNTO, TIPO
FROM TAREA
WHERE MODULOID = @ID AND MODULO = 'VTAS' AND estado = 'Completada'
ORDER BY Tipo
OPEN GRIS_BLANCO
FETCH NEXT FROM GRIS_BLANCO
INTO @ASUNTO, @TIPO
WHILE @@FETCH_STATUS = 0
BEGIN
SELECT  @COLORANTERIOR = @GRIS - @COLORANTERIOR
INSERT INTO #OBSERVA2 (IDVTAS, ASUNTO, TIPO, TIPOANTERIOR, COLOR)
VALUES (@ID, @ASUNTO, @TIPO, ISNULL(@TIPOANTERIOR, @TIPO), @COLORANTERIOR)
SELECT  @TIPOANTERIOR = @TIPO
FETCH NEXT FROM GRIS_BLANCO
INTO @ASUNTO,@TIPO
END
CLOSE GRIS_BLANCO
DEALLOCATE GRIS_BLANCO
INSERT INTO #COTIZACIONPRE
SELECT V.ID, 204800, 10.1, E.NOMBRE, ISNULL(E.DIRECCION, '') + '  ' + ISNULL(E.DireccionNumero, '') + '  ' + ISNULL(E.DIRECCIONNUMEROINT, '') + ISNULL(E.Colonia, '') + ' ' + ISNULL(E.CodigoPostal, ''),
c.cliente,C.nombre, ISNULL(c.DIRECCION, '') + '  ' + ISNULL(c.DireccionNumero, '') + '  ' + ISNULL(c.DIRECCIONNUMEROINT, '') + ISNULL(c.Colonia, '') + ' ' + ISNULL(c.CodigoPostal, ''),
ISNULL(T.nombre, ''), ISNULL(T.DIRECCION, '') + '  ' + ISNULL(T.DireccionNumero, '') + '  ' + ISNULL(T.DIRECCIONNUMEROINT, '') + ISNULL(T.Colonia, '') + ' ' + ISNULL(T.CodigoPostal, ''),
'', '', SER.ASUNTO, 0, 0, 0, 0, V.IMPORTE, V.Impuestos, SER.TIPO, SER.COLOR, V.MOV + ' ' + V.MOVID, V.FECHAEMISION, V.ATENCION, V.OBSERVACIONES, V.EnviarA, CONCEPTO, @DESCUENTO, gn.nombre,
SER.TIPO
FROM Venta V
LEFT OUTER JOIN Cte C			ON	V.Cliente = C.Cliente
LEFT OUTER JOIN CteEnviarA T	ON	V.Cliente = T.Cliente AND V.EnviarA = T.ID
LEFT OUTER JOIN Empresa E       ON  V.Empresa = E.Empresa
LEFT OUTER JOIN Agente gn		ON	v.Agente = gn.agente
LEFT OUTER JOIN #OBSERVA2 SER	ON  V.ID = SER.IDVTAS
WHERE V.ID = @ID
ORDER BY SER.INDICE
SELECT  *, DIASTEXTO = @DIASTEXTO, diasletra = @diasletra, mesesletra = @mesesletra
FROM #COTIZACIONPRE
END

