SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spContParalelaXMLPlantillaI

AS
BEGIN
INSERT ContParalelaXMLPlantilla(Modulo)
SELECT Modulo
FROM Modulo
WHERE Modulo NOT IN(SELECT Modulo FROM ContParalelaXMLPlantilla)
RETURN
END

