SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spContratoCerrarDia
@Fecha			datetime,
@Ok			int		OUTPUT,
@OkRef			varchar(255)	OUTPUT

AS BEGIN
DECLARE
@ID		int
DECLARE crContratoCerrarDia CURSOR FOR
SELECT ID
FROM Contrato
WHERE Estatus IN ('PENDIENTE', 'VIGENTE', 'VENCIDO')
OPEN crContratoCerrarDia
FETCH NEXT FROM crContratoCerrarDia INTO @ID
WHILE @@FETCH_STATUS <> -1
BEGIN
IF @@FETCH_STATUS <> -2
BEGIN
EXEC spAfectar 'PACTO', @ID, @EnSilencio = 1, @Ok = @Ok OUTPUT, @OkRef = @OkRef OUTPUT
END
FETCH NEXT FROM crContratoCerrarDia INTO @ID
END  
CLOSE crContratoCerrarDia
DEALLOCATE crContratoCerrarDia
RETURN
END

