SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spDesAsignarAcceso
@ID		INT

AS BEGIN
DECLARE
@EstacionTrabajo	INT
UPDATE Acceso SET FechaSalida = GETDATE() WHERE ID=@ID
UPDATE AccesoMes SET FechaSalida = GETDATE() WHERE ID = @ID
/*  SELECT @EstacionTrabajo = EstacionTrabajo FROM Acceso WHERE ID = @ID
DELETE EstacionTrabajo WHERE EstacionTrabajo = @EstacionTrabajo*/
RETURN
END

