SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spDistCategoriaLista

AS
BEGIN
DECLARE @TablaRet table(
Clave  int IDENTITY(1,1),
Nombre varchar(100)
)
INSERT INTO @TablaRet (Nombre) VALUES ('')
INSERT INTO @TablaRet (Nombre)
SELECT UPPER(LTRIM(RTRIM(Categoria))) FROM Art WHERE LEN(LTRIM(RTRIM(ISNULL(Categoria,'')))) > 0 GROUP BY Categoria ORDER BY 1
SELECT Clave, Nombre FROM @TablaRet ORDER BY 1
END

