SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spDisponibleAlmWMSFiltro
@Modulo     VARCHAR(20)

AS
BEGIN
CREATE TABLE #MovWMS (
ID     INT,
Mov    VARCHAR(20))
IF @Modulo='VTAS'
BEGIN
INSERT INTO #MovWMS (ID, Mov)
SELECT ID, Mov
FROM Venta a
JOIN Alm b ON b.Almacen=a.Almacen
WHERE Mov IN (SELECT Movimiento FROM WMSModuloMovimiento WHERE Modulo='VTAS')
AND a.Estatus='SINAFECTAR'
AND b.WMS=1
END
IF @Modulo='INV'
BEGIN
INSERT INTO #MovWMS (ID, Mov)
SELECT ID, Mov
FROM Inv a
JOIN Alm b ON b.Almacen=a.Almacen
WHERE Mov IN (SELECT Movimiento FROM WMSModuloMovimiento WHERE Modulo='INV')
AND a.Estatus='SINAFECTAR'
AND b.WMS=1
END
IF @Modulo='COMS'
BEGIN
INSERT INTO #MovWMS (ID, Mov)
SELECT ID, Mov
FROM Compra a
JOIN Alm b ON b.Almacen=a.Almacen
WHERE Mov IN (SELECT Movimiento FROM WMSModuloMovimiento WHERE Modulo='COMS')
AND a.Estatus='SINAFECTAR'
AND b.WMS=1
END
SELECT * FROM #MovWMS
RETURN
END

