SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spDistCorridaUltima (
@Empresa              varchar(5)
)

AS
BEGIN
DECLARE @Corrida int
SET @Empresa = LTRIM(RTRIM(ISNULL(@Empresa,'')))
SELECT @Corrida = MAX(Corrida) FROM DistCorrida WHERE Empresa = @Empresa
SELECT ISNULL(@Corrida,0) AS Corrida
END

