SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spDROP_COLUMN
@Tabla          sysname,
@Campo          sysname,
@Otros          sysname = NULL

AS BEGIN
DECLARE
@SQL	varchar(max)
IF EXISTS (SELECT * FROM SysObjects, SysColumns WHERE SysObjects.ID = SysColumns.ID AND SysObjects.Name = @Tabla AND SysColumns.Name = @Campo)
BEGIN
EXEC spDROP_CONSTRAINT @Tabla, @Campo
SELECT @SQL = 'ALTER TABLE ' + @Tabla + ' DROP COLUMN ' + RTRIM(@Campo)
IF @SQL IS NOT NULL
EXEC(@SQL)
END
RETURN
END

