SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE speCommerceCopiarVariacion
@ID int,
@NombreNuevo varchar(100)

AS BEGIN
DECLARE
@IDNuevo int,
@Ok int,
@OkRef varchar(255)
INSERT INTO WebArtVariacion (Orden, Nombre,		  GUID)
VALUES (0,		@NombreNuevo, NEWID())
SELECT @IDNuevo = SCOPE_IDENTITY()
EXEC speCommerceCopiarOpciones @IDNuevo, @ID, @Ok OUTPUT, @OkRef OUTPUT
END

