SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE speDocInRutaDEliminar
@GUID      varchar(36)

AS BEGIN
DELETE eDocInRutaD WHERE GUID = @GUID
DELETE eDocInRutaDCondicion WHERE GUID = @GUID
END

