SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spEliminarPK
@Tabla 	varchar(100)

AS BEGIN
DECLARE
@pk varchar(256)
SELECT @pk = pk FROM SysPK WHERE Tabla = @Tabla
IF @pk IS NOT NULL
EXEC('ALTER TABLE '+@Tabla+' DROP CONSTRAINT '+@pk)
END

