SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spExisteArchivo
@FileName varchar(255)

AS BEGIN
SET NOCOUNT ON
DECLARE @File_Exists int
EXEC Master.dbo.xp_fileexist @FileName, @File_Exists OUT
IF @File_Exists = 0
SELECT 'El archivo no existe '
ELSE
select ''
END

