SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spExtraerFloat
@Texto 	  	varchar(8000)	OUTPUT,
@Float     	float		OUTPUT,
@Separador	varchar(10)

AS BEGIN
DECLARE
@FloatSt	varchar(255)
SELECT @Float = NULL
EXEC spExtraerDato @Texto OUTPUT, @FloatSt OUTPUT, @Separador
IF dbo.fnEsNumerico(@FloatSt) = 1
SELECT @Float = CONVERT(float, @FloatSt)
RETURN
END

