SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spHECreaPassWord
@PassWord varchar(5) OUTPUT
AS
BEGIN
DECLARE @Contador int
SET @Contador=5
SET @PassWord=''
WHILE @Contador>0
BEGIN
SELECT @PassWord=@PassWord+CONVERT(varchar(1),FLOOR(RAND()*10))
SET @Contador=@Contador-1
END
SELECT @PassWord
END

