SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spHistCXP
@Horas      float,
@HastaFecha datetime,
@HastaHora  datetime,
@Ok         int          OUTPUT,
@OkRef      varchar(255) OUTPUT

AS BEGIN
DECLARE
@ID        int,
@Cantidad  int
BEGIN TRANSACTION
ALTER TABLE CXP DISABLE TRIGGER ALL
SELECT @Cantidad = 0
DECLARE crHistCXP CURSOR FORWARD_ONLY LOCAL STATIC FOR
SELECT TOP 1000000 ID
FROM CXP
WHERE FechaEmision < @HastaFecha AND Estatus IN ('CONCLUIDO', 'CONCILIADO', 'CANCELADO')
ORDER BY FechaEmision
OPEN crHistCXP
FETCH NEXT FROM crHistCXP INTO @ID
WHILE @@FETCH_STATUS = 0 AND @Ok IS NULL
BEGIN
EXEC spHistCXPMover @ID, @Ok OUTPUT, @OkRef OUTPUT
IF @Ok IS NULL
EXEC spHistMovMover @ID, 'CXP', @Ok OUTPUT, @OkRef OUTPUT
IF @Ok IS NULL SELECT @Cantidad = @Cantidad + 1
FETCH NEXT FROM crHistCXP INTO @ID
END
CLOSE crHistCXP
DEALLOCATE crHistCXP
ALTER TABLE CXP ENABLE TRIGGER ALL
IF @Ok IS NULL COMMIT TRANSACTION ELSE ROLLBACK TRANSACTION
INSERT HistLog (Modulo, HastaFecha, HastaHora, Cantidad, Ok, OkRef, Horas, Periodo, Ejercicio) VALUES ('CXP', @HastaFecha, @HastaHora, @Cantidad, @Ok, @OkRef, @Horas, MONTH(@HastaFecha), YEAR(@HastaFecha))
RETURN
END
;

