SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spHistAuto
@Modulo			varchar(5),
@Ejecutar		bit

AS BEGIN
DECLARE
@Linea		varchar(max),
@SQL		varchar(max)
IF @Ejecutar = 0
BEGIN
IF @Modulo IS NULL
EXEC spHistSugerir @EnSilencio = 1
IF @Modulo IS NOT NULL
EXEC spHistSugerir @Modulo = @Modulo, @EnSilencio = 1
DECLARE cCodigo CURSOR FOR
SELECT [SQL] FROM HistResultado WHERE Ejecutable = 1 ORDER BY ID ASC
OPEN cCodigo
FETCH NEXT FROM cCodigo INTO @Linea
WHILE @@FETCH_STATUS = 0
BEGIN
SELECT @SQL = ISNULL(@SQL,'')+CHAR(13)+CHAR(10)+CASE WHEN RTRIM(LTRIM(@Linea)) = CHAR(71)+CHAR(79) THEN ';' ELSE RTRIM(LTRIM(@Linea)) END
IF RTRIM(LTRIM(@Linea)) = CHAR(71)+CHAR(79)
BEGIN
BEGIN TRY
EXEC (@SQL)
SELECT @SQL = ''
END TRY
BEGIN CATCH
SELECT @SQL = ''
END CATCH
END
FETCH NEXT FROM cCodigo INTO @Linea
END
CLOSE cCodigo
DEALLOCATE cCodigo
END
END

