SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spInvAfectarUtilizarSeleccion
@Modulo		varchar(5),
@UtilizarID	int,
@Ok		int		OUTPUT,
@OkRef		varchar(255)	OUTPUT

AS BEGIN
IF @Modulo = 'VTAS' UPDATE VentaD  SET CantidadA = NULL WHERE ID = @UtilizarID AND CantidadA IS NOT NULL ELSE
IF @Modulo = 'COMS' UPDATE CompraD SET CantidadA = NULL WHERE ID = @UtilizarID AND CantidadA IS NOT NULL ELSE
IF @Modulo = 'INV'  UPDATE InvD    SET CantidadA = NULL WHERE ID = @UtilizarID AND CantidadA IS NOT NULL ELSE
IF @Modulo = 'PROD' UPDATE ProdD   SET CantidadA = NULL WHERE ID = @UtilizarID AND CantidadA IS NOT NULL
IF @@ERROR <> 0 SELECT @Ok = 1
END

