SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spInsertarNominaConcepto

AS BEGIN
EXEC spInsertarNominaConcepto1
EXEC spInsertarNominaConcepto2
EXEC spInsertarNominaConcepto3
EXEC spInsertarNominaConcepto4
EXEC spInsertarNominaConcepto5
EXEC spInsertarNominaConcepto6
END

