SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spLimpiarRutaCFD
@Estacion	int,
@Ruta  varchar(256)

AS BEGIN
SET @Ruta = ISNULL(@Ruta,'')
DELETE RutaAcuse WHERE Estacion = @Estacion
INSERT RutaAcuse(Estacion,Ruta,Acuse,Descripcion)
VALUES (@Estacion,@Ruta,'','')
RETURN
END

