SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spMonActualizarTipoCambio
@Estacion	int

AS BEGIN
DECLARE
@Moneda			varchar(20),
@TipoCambio		float
DECLARE crMonActualizar CURSOR LOCAL FOR
SELECT Moneda, TipoCambio
FROM MonActualizarTemp
WHERE Estacion = @Estacion
AND TipoCambio IS NOT NULL
OPEN crMonActualizar
FETCH NEXT FROM crMonActualizar INTO @Moneda, @TipoCambio
WHILE @@FETCH_STATUS <> -1
BEGIN
IF @@FETCH_STATUS <> -2
BEGIN
UPDATE Mon SET TipoCambio = @TipoCambio WHERE Moneda = @Moneda
END
FETCH NEXT FROM crMonActualizar INTO @Moneda, @TipoCambio
END
CLOSE crMonActualizar
DEALLOCATE crMonActualizar
END

