SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spNetAddCfgXUsuario
@Empresa		varchar(5)  = NULL,
@Descripcion	varchar(80) = NULL,
@IDUsuario 	int			= NULL
AS BEGIN
IF NOT EXISTS(SELECT 1 FROM PortalNetCfgXUsuario WHERE Empresa = @Empresa AND Descripcion = @Descripcion AND IDUsuario = @IDUsuario)
INSERT INTO PortalNetCfgXUsuario SELECT @Empresa, @Descripcion, @IDUsuario
SELECT 'Registro actualizado'
END

