SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE dbo.spNetDocsGrupo
@Grupo	AS VARCHAR(50)
AS
BEGIN
SET NOCOUNT ON
SELECT DISTINCT Grupo  FROM DocRama gdr WHERE Rama = @Grupo
SET NOCOUNT OFF
END

