SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE dbo.spNetAmenidadesAfecta
@ID			INT,
@Cliente		VARCHAR(10),
@FechaD		DATETIME = NULL,
@Mov			VARCHAR(20),
@MovID			VARCHAR(20),
@FechaDesde	DATETIME,
@FechaHasta	DATETIME
AS BEGIN
IF @FechaHasta IS NULL OR @FechaHasta = ''
BEGIN
UPDATE Amenidades SET Mov = @Mov, MovID = @MovID, FechaHasta = @FechaDesde WHERE Cliente = RTRIM(LTRIM(@Cliente)) AND CONVERT(DATE, FechaDesde) = @FechaD
END
ELSE
BEGIN
UPDATE Amenidades SET Mov = @Mov, MovID = @MovID WHERE Cliente = RTRIM(LTRIM(@Cliente)) AND CONVERT(DATE, FechaDesde) = @FechaD
END
END

