SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE dbo.spNotaCreditoVta
@ID INT

AS BEGIN
SELECT	V.ID,
V.Mov,
V.MovID,
V.FechaEmision,
V.UEN,
V.Moneda,
CONVERT(FLOAT, V.TipoCambio) TipoCambioMov,
V.Cliente,
C.Nombre,
C.RFC,
C.Direccion,
C.DireccionNumero,
C.DireccionNumeroInt,
C.EntreCalles,
C.Observaciones,
C.Delegacion,
C.Colonia,
C.CodigoPostal,
C.Estado,
C.Pais,
C.Telefonos,
C.TelefonosLada,
C.Fax,
C.eMail1,
CA.Nombre AS CteSucNombre,
CA.Direccion AS CteSucDireccion,
CA.DireccionNumero AS CteSucDireccionNum,
CA.DireccionNumeroInt AS CteSucDirNumInt,
CA.EntreCalles AS CteSucEntreCalles,
CA.Observaciones AS CteSucObservaciones,
CA.Delegacion AS CteSucDelegacion,
CA.Colonia AS CteSucColonia,
CA.CodigoPostal AS CteSucCodigoPostal,
CA.Estado AS CteSucEstado,
CA.Pais AS CteSucPais,
CA.Telefonos As CteSucTelefonos,
CA.Fax AS CteSucFax,
CA.eMail1 AS CteSuceMail1,
V.Renglon,
CONVERT(INT, V.RenglonID) AS RENGLONID,
V.Articulo,
V.Cantidad,
A.Descripcion1 + ' ' + ISNULL(NULLIF(V.DescripcionExtra, ''), '') AS DESCRIPCIONART,
DATALENGTH(A.Descripcion1 + ' ' + ISNULL(NULLIF(V.DescripcionExtra, ''), '')) AS LARGODESCART,
VD.Precio PrecioME,
VD.PrecioTipoCambio,
VD.Precio * VD.PrecioTipoCambio PrecioMN,
VD.Precio * VD.Cantidad AS IMPORTETOTALME,
VD.Precio * VD.Cantidad * VD.PrecioTipoCambio AS ImporteTotalMN,
VD.DescuentoLinea,
VD.PrecioMoneda,
V.SUBTOTAL SubTotalMov,
V.Impuestos ImpuestosMov,
V.DescuentosTotales DescTotalesMov,
V.TotalNeto TotalNetoMov,
'DESCRIPCION' AS RENGLONREPTIPO,
1.0 AS ORDENREP,
V.Empresa,
E.Nombre AS EmpresaNombre,
AC.Direccion AS LOGORUTA,
V.Agente,
AG.Nombre AS AGENTENOMBRE,
VE.EnviarA,
E.RFC EmpresaRFC,
E.Direccion EmpresaDir,
E.DireccionNumero EmpresaDirNum,
E.DireccionNumeroInt EmpresaDirNumInt,
E.Colonia EmpresaColonia,
E.CodigoPostal EmpresaCP,
E.Poblacion EmpresaPoblacion,
E.Delegacion EmpresaDelegacion,
E.Estado EmpresaEDO,
E.Pais EmpresaPais,
E.Telefonos EmpresaTel,
E.Fax EmpresaFax,
V.Sucursal VentaSucursal,
S.Nombre SucursalNombre,
S.Direccion SucursalDir,
S.DireccionNumero SucursalDirNum,
S.DireccionNumeroInt SucursalDirNumInt,
S.Colonia SucursalColonia,
S.CodigoPostal SucursalCP,
S.Delegacion SucursalDelegacion,
S.Estado SucursalEDO,
S.Poblacion SucursalPoblacion,
S.Pais SucursalPais,
S.Telefonos SucursalTel,
S.Fax SucursalFax,
i.Fecha FechaCFD,
i.FechaTimbrado,
i.noCertificado,
i.noCertificadoSAT,
CONVERT(VARCHAR(100), i.UUID) UUID,
i.Sello,
i.SelloSAT,
i.TFDCadenaOriginal,
CONVERT(VARCHAR(50), NULL) AS SERIELOTE,
CONVERT(VARCHAR(100), NULL) AS ADUANA,
CONVERT(DATE, NULL) AS FECHAADUANA,
CONVERT(VARCHAR(50), NULL) AS PEDIMENTO,
(SELECT Direccion FROM AnexoCta WHERE RAMA = 'EMP' AND CUENTA = V.Empresa AND TIPO = 'Imagen' AND Nombre = 'LOGO') AS CODIGO,
(SELECT NOMBRE FROM FISCALREGIMEN WHERE FiscalRegimen = E.FiscalRegimen) AS REGIMENFISCAL,
ISNULL(VC.FormaCobro1, (SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)) AS FormaCobro1,
VC.FormaCobro2,
VC.FormaCobro3,
VC.FormaCobro4,
VC.FormaCobro5,
ISNULL(VC.Referencia1, (SELECT CuentaPago FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)) AS Referencia1,
VC.Referencia2,
VC.Referencia3,
VC.Referencia4,
VC.Referencia5,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.Referencia1, ''), (SELECT CUENTAPAGO FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.Referencia2, '') IS NOT NULL OR NULLIF(VC.Referencia3, '') IS NOT NULL OR NULLIF(VC.Referencia4, '') IS NOT NULL OR NULLIF(VC.Referencia5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSREFCOBRO,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.FormaCobro1, ''), (SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.FormaCobro2, '') IS NOT NULL OR NULLIF(VC.FormaCobro3, '') IS NOT NULL OR NULLIF(VC.FormaCobro4, '') IS NOT NULL OR NULLIF(VC.FormaCobro5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSFORMAPAGO,
V.Unidad UNIDADVTA,
CAD.Nombre AS CteEnviarNombre,
CAD.Direccion AS CteEnviarDireccion,
CAD.DireccionNumero AS CteEnviarDireccionNum,
CAD.DireccionNumeroInt AS CteEnviarDirNumInt,
CAD.EntreCalles AS CteEnviarEntreCalles,
CAD.Observaciones AS CteEnviarObservaciones,
CAD.Delegacion AS CteEnviarDelegacion,
CAD.Colonia AS CteEnviarColonia,
CAD.CodigoPostal AS CteEnviarCodigoPostal,
CAD.Estado AS CteEnviarEstado,
CAD.Pais AS CteEnviarPais,
CAD.Telefonos As CteEnviarTelefonos,
CAD.Fax AS CteEnviarFax,
CAD.eMail1 AS CteEnviareMail1,
NULLIF(VE.EnviarA, '') CteEnviarA
INTO #REPPRESUPUESTO
FROM VENTATCALC V
JOIN VENTA VE ON V.ID = VE.ID
JOIN Cte C ON V.CLIENTE = C.Cliente
LEFT OUTER JOIN CteEnviarA CA ON V.Cliente = CA.Cliente AND VE.EnviarA = CA.ID
JOIN ART A ON V.ARTICULO = A.ARTICULO
JOIN VENTAD VD ON V.ID = VD.ID AND V.Renglon = VD.Renglon AND V.RenglonID = VD.RenglonID
JOIN EMPRESA E ON V.Empresa = E.Empresa
LEFT OUTER JOIN AnexoCta AC ON V.Empresa = AC.Cuenta AND CONVERT(VARCHAR(10), V.ContUso) + 'F' = AC.Nombre AND AC.Rama = 'EMP' AND AC.Tipo = 'Imagen'
LEFT OUTER JOIN Agente AG ON V.Agente = AG.Agente
JOIN Sucursal S ON V.Sucursal = S.Sucursal
LEFT OUTER JOIN CFD i ON V.ID = i.ModuloID AND i.Modulo = 'VTAS'
LEFT OUTER JOIN VentaCobro VC ON V.ID = VC.ID
LEFT OUTER JOIN CteEnviarA CAD ON CAD.Cliente = V.Cliente AND VD.EnviarA = CAD.ID
WHERE V.ID = @ID AND VD.RENGLONTIPO IN ('N','J','L','S')
INSERT INTO #REPPRESUPUESTO
SELECT	V.ID,
V.Mov,
V.MovID,
V.FechaEmision,
V.UEN,
V.Moneda,
V.TipoCambio,
V.Cliente,
C.Nombre,
C.RFC,
C.Direccion,
C.DireccionNumero,
C.DireccionNumeroInt,
C.EntreCalles,
C.Observaciones,
C.Delegacion,
C.Colonia,
C.CodigoPostal,
C.Estado,
C.Pais,
C.Telefonos,
C.TelefonosLada,
C.Fax,
C.eMail1,
CA.Nombre AS CteSucNombre,
CA.Direccion AS CteSucDireccion,
CA.DireccionNumero AS CteSucDireccionNum,
CA.DireccionNumeroInt AS CteSucDirNumInt,
CA.EntreCalles AS CteSucEntreCalles,
CA.Observaciones AS CteSucObservaciones,
CA.Delegacion AS CteSucDelegacion,
CA.Colonia AS CteSucColonia,
CA.CodigoPostal AS CteSucCodigoPostal,
CA.Estado AS CteSucEstado,
CA.Pais AS CteSucPais,
CA.Telefonos As CteSucTelefonos,
CA.Fax AS CteSucFax,
CA.eMail1 AS CteSuceMail1,
V.Renglon,
V.RenglonID,
V.Articulo,
0 AS Cantidad,
A.Descripcion1 + ' ' + ISNULL(NULLIF(V.DescripcionExtra, ''), '') AS DESCRIPCIONART,
DATALENGTH(A.Descripcion1 + ' ' + ISNULL(NULLIF(V.DescripcionExtra, ''), '')) AS LARGODESCART,
0 AS PrecioME,
0 AS PrecioTipoCambio,
0 AS PrecioMN,
0 AS IMPORTETOTALME,
0 AS ImporteTotalMN,
0 AS DescuentoLinea,
VD.PrecioMoneda,
0 AS SubTotalMov,
0 AS ImpuestosMov,
0 AS DescTotalesMov,
0 AS TotalNetoMov,
'SERIELOTE' AS RENGLONREPTIPO,
2.0 AS ORDENREP,
V.Empresa,
E.Nombre AS EmpresaNombre,
AC.Direccion AS LOGORUTA,
V.Agente,
AG.Nombre AS AGENTENOMBRE,
VE.EnviarA,
E.RFC EmpresaRFC,
E.Direccion EmpresaDir,
E.DireccionNumero EmpresaDirNum,
E.DireccionNumeroInt EmpresaDirNumInt,
E.Colonia EmpresaColonia,
E.CodigoPostal EmpresaCP,
E.Poblacion EmpresaPoblacion,
E.Delegacion EmpresaDelegacion,
E.Estado EmpresaEDO,
E.Pais EmpresaPais,
E.Telefonos EmpresaTel,
E.Fax EmpresaFax,
V.Sucursal VentaSucursal,
S.Nombre SucursalNombre,
S.Direccion SucursalDir,
S.DireccionNumero SucursalDirNum,
S.DireccionNumeroInt SucursalDirNumInt,
S.Colonia SucursalColonia,
S.CodigoPostal SucursalCP,
S.Delegacion SucursalDelegacion,
S.Estado SucursalEDO,
S.Poblacion SucursalPoblacion,
S.Pais SucursalPais,
S.Telefonos SucursalTel,
S.Fax SucursalFax,
i.Fecha FechaCFD,
i.FechaTimbrado,
i.noCertificado,
i.noCertificadoSAT,
i.UUID,
i.Sello,
i.SelloSAT,
i.TFDCadenaOriginal,
SLM.SerieLote AS SERIELOTE,
SLP.Aduana AS ADUANA,
SLP.Fecha1 AS FECHAADUANA,
SLM.Propiedades AS PEDIMENTO,
(SELECT Direccion FROM AnexoCta WHERE RAMA = 'EMP' AND CUENTA = V.Empresa AND TIPO = 'Imagen' AND Nombre = 'LOGO') AS CODIGO,
(SELECT NOMBRE FROM FISCALREGIMEN WHERE FiscalRegimen = E.FiscalRegimen) AS REGIMENFISCAL,
ISNULL(VC.FormaCobro1, (SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)) AS FormaCobro1,
VC.FormaCobro2,
VC.FormaCobro3,
VC.FormaCobro4,
VC.FormaCobro5,
ISNULL(VC.Referencia1, (SELECT CuentaPago FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)) AS Referencia1,
VC.Referencia2,
VC.Referencia3,
VC.Referencia4,
VC.Referencia5,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.Referencia1, ''),(SELECT CUENTAPAGO FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.Referencia2, '') IS NOT NULL OR NULLIF(VC.Referencia3, '') IS NOT NULL OR NULLIF(VC.Referencia4, '') IS NOT NULL OR NULLIF(VC.Referencia5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSREFCOBRO,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.FormaCobro1, ''),(SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.FormaCobro2, '') IS NOT NULL OR NULLIF(VC.FormaCobro3, '') IS NOT NULL OR NULLIF(VC.FormaCobro4, '') IS NOT NULL OR NULLIF(VC.FormaCobro5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSFORMAPAGO,
V.Unidad UNIDADVTA,
CAD.Nombre AS CteEnviarNombre,
CAD.Direccion AS CteEnviarDireccion,
CAD.DireccionNumero AS CteEnviarDireccionNum,
CAD.DireccionNumeroInt AS CteEnviarDirNumInt,
CAD.EntreCalles AS CteEnviarEntreCalles,
CAD.Observaciones AS CteEnviarObservaciones,
CAD.Delegacion AS CteEnviarDelegacion,
CAD.Colonia AS CteEnviarColonia,
CAD.CodigoPostal AS CteEnviarCodigoPostal,
CAD.Estado AS CteEnviarEstado,
CAD.Pais AS CteEnviarPais,
CAD.Telefonos As CteEnviarTelefonos,
CAD.Fax AS CteEnviarFax,
CAD.eMail1 AS CteEnviareMail1,
NULLIF(VE.EnviarA, '') CteEnviarA
FROM VENTATCALC V
JOIN VENTA VE ON V.ID = VE.ID
JOIN Cte C ON V.CLIENTE = C.Cliente
LEFT OUTER JOIN CteEnviarA CA ON V.Cliente = CA.Cliente AND VE.EnviarA = CA.ID
JOIN ART A ON V.ARTICULO = A.ARTICULO
JOIN VENTAD VD ON V.ID = VD.ID AND V.Renglon = VD.Renglon AND V.RenglonID = VD.RenglonID
JOIN EMPRESA E ON V.Empresa = E.Empresa
LEFT OUTER JOIN AnexoCta AC ON V.Empresa = AC.Cuenta AND CONVERT(VARCHAR(10), V.ContUso) + 'F' = AC.Nombre AND AC.Rama = 'EMP' AND AC.Tipo = 'Imagen'
LEFT OUTER JOIN Agente AG ON V.Agente = AG.Agente
JOIN Sucursal S ON V.Sucursal = S.Sucursal
LEFT OUTER JOIN CFD i ON V.ID = i.ModuloID AND i.Modulo = 'VTAS'
JOIN SerieLoteMov SLM ON V.ID = SLM.ID AND SLM.Modulo = 'VTAS' AND V.Articulo = SLM.Articulo AND V.RenglonID = SLM.RenglonID
LEFT OUTER JOIN SerieLoteProp SLP ON SLM.Propiedades = SLP.Propiedades
LEFT OUTER JOIN VentaCobro VC ON V.ID = VC.ID
LEFT OUTER JOIN CteEnviarA CAD ON CAD.Cliente = V.Cliente AND VD.EnviarA = CAD.ID
WHERE V.ID=@ID
INSERT INTO #REPPRESUPUESTO
SELECT	V.ID,
V.Mov,
V.MovID,
V.FechaEmision,
V.UEN,
V.Moneda,
V.TipoCambio,
V.Cliente,
C.Nombre,
C.RFC,
C.Direccion,
C.DireccionNumero,
C.DireccionNumeroInt,
C.EntreCalles,
C.Observaciones,
C.Delegacion,
C.Colonia,
C.CodigoPostal,
C.Estado,
C.Pais,
C.Telefonos,
C.TelefonosLada,
C.Fax,
C.eMail1,
CA.Nombre AS CteSucNombre,
CA.Direccion AS CteSucDireccion,
CA.DireccionNumero AS CteSucDireccionNum,
CA.DireccionNumeroInt AS CteSucDirNumInt,
CA.EntreCalles AS CteSucEntreCalles,
CA.Observaciones AS CteSucObservaciones,
CA.Delegacion AS CteSucDelegacion,
CA.Colonia AS CteSucColonia,
CA.CodigoPostal AS CteSucCodigoPostal,
CA.Estado AS CteSucEstado,
CA.Pais AS CteSucPais,
CA.Telefonos As CteSucTelefonos,
CA.Fax AS CteSucFax,
CA.eMail1 AS CteSuceMail1,
(SELECT MAX(Renglon) + 1 FROM VENTAD WHERE ID = V.ID) AS Renglon,
(SELECT MAX(RenglonID) + 1 FROM VENTAD WHERE ID = V.ID) AS RenglonID,
'ANTICIPO' AS Articulo,
1 AS Cantidad,
'ANTICIPO FACTURADO' AS DESCRIPCIONART,
DATALENGTH('ANTICIPO FACTURADO') AS LARGODESCART,
0 AS PrecioME,
0 AS PrecioTipoCambio,
(V.ANTICIPOSFACTURADOS - V.ANTICIPOSIMPUESTOS) * -1 AS PrecioMN,
0 AS IMPORTETOTALME,
(V.ANTICIPOSFACTURADOS - V.ANTICIPOSIMPUESTOS) * -1 AS ImporteTotalMN,
NULL AS DescuentoLinea,
'' AS PRECIOMONEDA,
(V.ANTICIPOSFACTURADOS - V.ANTICIPOSIMPUESTOS) * -1 AS SubTotalMov,
V.ANTICIPOSIMPUESTOS * -1 AS ImpuestosMov,
0 AS DescTotalesMov,
V.ANTICIPOSFACTURADOS * -1 AS TotalNetoMov,
'ANTICIPOS' AS RENGLONREPTIPO,
1.0 AS ORDENREP,
V.Empresa,
E.Nombre AS EmpresaNombre,
AC.Direccion AS LOGORUTA,
V.Agente,
AG.Nombre AS AGENTENOMBRE,
V.EnviarA,
E.RFC EmpresaRFC,
E.Direccion EmpresaDir,
E.DireccionNumero EmpresaDirNum,
E.DireccionNumeroInt EmpresaDirNumInt,
E.Colonia EmpresaColonia,
E.CodigoPostal EmpresaCP,
E.Poblacion EmpresaPoblacion,
E.Delegacion EmpresaDelegacion,
E.Estado EmpresaEDO,
E.Pais EmpresaPais,
E.Telefonos EmpresaTel,
E.Fax EmpresaFax,
V.Sucursal VentaSucursal,
S.Nombre SucursalNombre,
S.Direccion SucursalDir,
S.DireccionNumero SucursalDirNum,
S.DireccionNumeroInt SucursalDirNumInt,
S.Colonia SucursalColonia,
S.CodigoPostal SucursalCP,
S.Delegacion SucursalDelegacion,
S.Estado SucursalEDO,
S.Poblacion SucursalPoblacion,
S.Pais SucursalPais,
S.Telefonos SucursalTel,
S.Fax SucursalFax,
i.Fecha FechaCFD,
i.FechaTimbrado,
i.noCertificado,
i.noCertificadoSAT,
i.UUID,
i.Sello,
i.SelloSAT,
i.TFDCadenaOriginal,
NULL AS SERIELOTE,
NULL AS ADUANA,
NULL AS FECHAADUANA,
NULL AS PEDIMENTO,
(SELECT Direccion FROM AnexoCta WHERE RAMA = 'EMP' AND CUENTA = V.Empresa AND TIPO = 'Imagen' AND Nombre = 'LOGO') AS CODIGO,
(SELECT NOMBRE FROM FISCALREGIMEN WHERE FiscalRegimen = E.FiscalRegimen) AS REGIMENFISCAL,
ISNULL(VC.FormaCobro1, (SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)) AS FormaCobro1,
VC.FormaCobro2,
VC.FormaCobro3,
VC.FormaCobro4,
VC.FormaCobro5,
ISNULL(VC.Referencia1, (SELECT CuentaPago FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)) AS Referencia1,
VC.Referencia2,
VC.Referencia3,
VC.Referencia4,
VC.Referencia5,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.Referencia1, ''),(SELECT CUENTAPAGO FROM CteCFDInfoPagoD P JOIN CteCFD CC ON P.Cliente = CC.Cliente AND CC.InfoPago = P.InfoPago AND P.FormaPago = CC.InfoFormaPago WHERE P.Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.Referencia2, '') IS NOT NULL OR NULLIF(VC.Referencia3, '') IS NOT NULL OR NULLIF(VC.Referencia4, '') IS NOT NULL OR NULLIF(VC.Referencia5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSREFCOBRO,
(CASE WHEN NULLIF(ISNULL(NULLIF(VC.FormaCobro1, ''),(SELECT InfoFormaPago FROM CteCFD WHERE Cliente = V.Cliente)), '')
IS NOT NULL OR NULLIF(VC.FormaCobro2, '') IS NOT NULL OR NULLIF(VC.FormaCobro3, '') IS NOT NULL OR NULLIF(VC.FormaCobro4, '') IS NOT NULL OR NULLIF(VC.FormaCobro5, '') IS NOT NULL
THEN 'SI' ELSE NULL END) AS CONDATOSFORMAPAGO,
'NO APLICA' UNIDADVTA,
'' AS CteEnviarNombre,
'' AS CteEnviarDireccion,
'' AS CteEnviarDireccionNum,
'' AS CteEnviarDirNumInt,
'' AS CteEnviarEntreCalles,
'' AS CteEnviarObservaciones,
'' AS CteEnviarDelegacion,
'' AS CteEnviarColonia,
'' AS CteEnviarCodigoPostal,
'' AS CteEnviarEstado,
'' AS CteEnviarPais,
'' As CteEnviarTelefonos,
'' AS CteEnviarFax,
'' AS CteEnviareMail1,
NULLIF(V.EnviarA, '') CteEnviarA
FROM Venta V
JOIN Cte C ON V.CLIENTE = C.Cliente
LEFT OUTER JOIN CteEnviarA CA ON V.Cliente = CA.Cliente AND V.EnviarA = CA.ID
JOIN EMPRESA E ON V.Empresa = E.Empresa
LEFT OUTER JOIN AnexoCta AC ON V.Empresa = AC.Cuenta AND CONVERT(VARCHAR(10), V.ContUso) + 'F' = AC.Nombre AND AC.Rama = 'EMP' AND AC.Tipo = 'Imagen'
LEFT OUTER JOIN Agente AG ON V.Agente = AG.Agente
JOIN Sucursal S ON V.Sucursal = S.Sucursal
LEFT OUTER JOIN CFD i ON V.ID = i.ModuloID AND i.Modulo = 'VTAS'
LEFT OUTER JOIN VentaCobro VC ON V.ID = VC.ID
WHERE V.ID = @ID AND NULLIF(V.AnticiposFacturados, '') IS NOT NULL
SELECT * FROM #REPPRESUPUESTO
ORDER BY ID, Renglon, RenglonID, ORDENREP
END

