SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spOmisionMensajeLayoutHSBC21

AS BEGIN
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00232', '(blank)(00232)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00233', '(blank)(00233)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00236', '(blank)(00236)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01016', '(blank)(01016)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04178', '(blank)(04178)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04180', '(blank)(04180)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05525', 'ABONO  POR ACLARACION EN CAJERO AUTOMATICO(05525)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02529', 'ABONO A CDA DESDE DDA POR APERTURA EN CP(02529)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02531', 'ABONO A CDA DESDE DDA POR REINVERSION CP(02531)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04115', 'ABONO A CTA. DE CHEQUES DE CAJA POR C/V(04115)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04535', 'ABONO A CUENTA DE CHEQUES CERTIFICADOS(04535)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01385', 'ABONO A FIDEICOMISOS O MANDATOS(01385)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01505', 'ABONO AJUSTE DE I.V.A POR SUSP PAGO(01505)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01503', 'ABONO AJUSTE DE I.V.A. CARGOS POR SERV(01503)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01511', 'ABONO AJUSTE DE I.V.A. POR CARGOS MISC(01511)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01507', 'ABONO AJUSTE DE I.V.A. POR CARGOS OD(01507)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01509', 'ABONO AJUSTE DE I.V.A. POR CHEQ DEV(01509)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05655', 'ABONO AL CLIENTE A LA PAR EN USD(05655)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01191', 'ABONO CANCELACION DE CTA C/SALDO NEG(01191)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01017', 'ABONO CARTA DE CREDITO(01017)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04547', 'ABONO CHQ. CERTIFICADO DEV. OTRAS CAUSAS(04547)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05687', 'ABONO COBRANZA ESP RECARGO(05687)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01659', 'ABONO COMISION POR NO LIBERACION DE PEDIMENTO(01659)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04159', 'ABONO CON DESCRIPCION VARIABLE(04159)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05823', 'ABONO CREDITO DOCUMENTARIO (HIE)(05823)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04603', 'ABONO CUENTAS PROPIAS PESOS CEI(04603)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05503', 'ABONO DE COBRANZAS ESPECIAL(05503)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05681', 'ABONO DESDE OTRAS EMPRESAS(05681)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05685', 'ABONO DESDE OTRAS EMPRESAS(05685)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01653', 'ABONO DEVOLUCION COBRANZA DOCUMENTARIA(01653)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05213', 'ABONO DEVOLUCION ORDEN DE PAGO SPEI(05213)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05063', 'ABONO DEVOLUCION ORDEN DE PAGO SPEUA(05063)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01403', 'ABONO ENGANCHE DE CREDITO DE CONSUMO(01403)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04623', 'ABONO FONDEO DE CUENTA CEI(04623)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04571', 'ABONO IMSS(04571)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01413', 'ABONO LIQUIDACION DE IMPORTE DEL CONSUMO(01413)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00216', 'ABONO MODULO DE CUENTAS  CONCILIABLES(00216)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04517', 'ABONO ORDEN DE PAGO RECIBIDA AUT C/V(04517)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04515', 'ABONO ORDEN DE PAGO RECIBIDA AUT PAR(04515)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00767', 'ABONO ORDEN DE PAGO RECIBIDA EN C/V AUTOMATICO(00767)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04519', 'ABONO ORDEN DE PAGO RECIBIDA MANUAL PAR(04519)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04521', 'ABONO ORDEN DE PAGO RECIBIDA MANUAL POR C/V(04521)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05603', 'ABONO ORDEN DE PAGO RECIBIDA OTROS BCOS.(05603)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05211', 'ABONO ORDEN DE PAGO SPEI(05211)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05061', 'ABONO ORDEN DE PAGO SPEUA(05061)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05173', 'ABONO P/DEV. ORD. PAGO DIVISA(05173)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05563', 'ABONO P/LIQ TIP (TRANSF.INMEDIATA DE PAGOS) CON AB(05563)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04627', 'ABONO PAGO DE IMPUESTOS CEI(04627)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05973', 'ABONO PAGO DE SERVICIOS EN LINEA BITAL(05973)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05848', 'ABONO PAGO INTERBANCARIO A OTROS BANCOS(05848)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05857', 'ABONO PAGO INTERBANCARIO A OTROS BANCOS(05857)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05861', 'ABONO PAGO INTERBANCARIO BITAL(05861)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01409', 'ABONO PAGO POR CREDITO DE CONSUMO(01409)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02051', 'ABONO PARA PAGO DE LINEA DE CREDITO(02051)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05677', 'ABONO POR ACLARACION CONEXION PERSONAL(05677)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04225', 'ABONO POR ACLARACION DE COBRANZA(04225)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01122', 'ABONO POR AJUSTE A INTS ACUM -SYS-(01122)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01533', 'ABONO POR AJUSTE DE I.S.R.(01533)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01119', 'ABONO POR AJUSTE DE INTERESES(01119)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03219', 'ABONO POR AJUSTE DE INTERESES DE INVERSIONES(03219)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01124', 'ABONO POR AJUSTE DE INTS. COBRADOS(01124)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04031', 'ABONO POR CANCELACION DE CHEQUE DE CAJA(04031)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04093', 'ABONO POR CANCELACION GIROS EN DOLARES(04093)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05148', 'ABONO POR CARGO INDEBIDO(05148)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05569', 'ABONO POR CARGO INDEBIDO TIP(05569)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05703', 'ABONO POR CARTERA  S/36(05703)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05203', 'ABONO POR CARTERA (SABI)(05203)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04165', 'ABONO POR CARTERA , AJ. DE PPAL. O AJ. DE INTS.(04165)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01683', 'ABONO POR CARTERA PEUGEOT(01683)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01687', 'ABONO POR CARTERA PEUGEOT(01687)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04541', 'ABONO POR CHEQUE CERTIFICADO(04541)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05048', 'ABONO POR CHEQUE DE CAJA DEV. OTRAS CAUSAS(05048)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05085', 'ABONO POR CHEQUE EMP. DEV. OTRAS CAUSAS(05085)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04191', 'ABONO POR COBRANZA LUZ Y FUERZA CANALES REMOTOS(04191)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04503', 'ABONO POR COBRO DE COMISION INDEBIDA(04503)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01731', 'ABONO POR COMISION DE CAJERO INDEBIDA(01731)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01177', 'ABONO POR COMPRA DE DIVISAS Y METALES(01177)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09813', 'ABONO POR COMPRA DE UDI''S(09813)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09811', 'ABONO POR COMPRA DE UDI''S (LINEA BITAL)(09811)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04003', 'ABONO POR COMPRA-VENTA(04003)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05557', 'ABONO POR CONTRATO INTERBANCARIO(05557)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03533', 'ABONO POR CORRECCION AL I.S.R. RETENIDO INVERSIONE(03533)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01405', 'ABONO POR CREDITO DE CONSUMO(01405)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00585', 'ABONO POR DEV. O.P. DE OT. BCOS.(00585)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05167', 'ABONO POR DEV. O.P. MXN(05167)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00594', 'ABONO POR DEV. ORD. PAGO EN US$(00594)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00596', 'ABONO POR DEV. ORD. PAGO EN US$(00596)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05171', 'ABONO POR DEV. ORD. PAGO EN US$(05171)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04233', 'ABONO POR DEVOLUCION DE NOMINA(04233)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05169', 'ABONO POR DEVOLUCION DE O.P.(05169)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05163', 'ABONO POR DEVOLUCION OP DIVISA(05163)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05645', 'ABONO POR DEVOLUCION POR O.P. ENVIADA HSBCNET EN U(05645)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04533', 'ABONO POR DISPERSION DE PAGO(04533)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04187', 'ABONO POR DISPOSICION CEI(04187)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05821', 'ABONO POR FINANCIAMIENTO (HIE)(05821)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05597', 'ABONO POR INTERES MORATORIO SIN IVA(05597)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05617', 'ABONO POR INTERES MORATORIO SIN IVA(05617)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05517', 'ABONO POR LIBERACION DE PEDIMENTO(05517)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05519', 'ABONO POR NO LIBERACION DE PEDIMENTO(05519)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05619', 'ABONO POR NO LIBERACION DE PEDIMENTO(05619)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01389', 'ABONO POR OPERACION FIDUCIARIA(01389)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05259', 'ABONO POR OPERACIONES DE SERVICIOS ESPECIALES(05259)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04083', 'ABONO POR ORDEN DE PAGO(04083)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04615', 'ABONO POR PAGO A TERCEROS DOLARES CEI(04615)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04611', 'ABONO POR PAGO A TERCEROS PESOS CEI(04611)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04231', 'ABONO POR PAGO DE NOMINA(04231)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04619', 'ABONO POR PAGO DE NOMINA CEI(04619)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05013', 'ABONO POR PAGO DE SORTEO(05013)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05073', 'ABONO POR PAGO DE TARJETA DE CREDITO EN(05073)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01421', 'ABONO POR SEGURO DE AUTO BITAL(01421)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05023', 'ABONO POR TARJETA DE DEBITO(05023)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01041', 'ABONO POR TERMINAL PUNTO DE VENTA(01041)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05223', 'ABONO POR TRANSF CAJERO AUTOMATICO(05223)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01045', 'ABONO POR TRANSF DE CAPITAL DE INV(01045)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01013', 'ABONO POR TRANSF DE CUENTAS CONEXAS (TB)(01013)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05123', 'ABONO POR TRANSF. BANCO EN SU EMPRESA.NOMINA(05123)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02511', 'ABONO POR TRANSF. CTAS. A LA VISTA (LB)(02511)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04147', 'ABONO POR TRANSF. DE ENLACE EMPRESARIAL(04147)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04141', 'ABONO POR TRANSF. DE TERCEROS DE OT. BCOS.(04141)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05901', 'ABONO POR TRANSF. PARA APERTURA CTA.(05901)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02523', 'ABONO POR TRANSFERENCIA(02523)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04237', 'ABONO POR TRANSFERENCIA(04237)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02001', 'ABONO POR TRANSFERENCIA A CDA EN LINEA BITAL(02001)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05813', 'ABONO POR TRANSFERENCIA BALANCE CERO(05813)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05817', 'ABONO POR TRANSFERENCIA BALANCE CERO(05817)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '02513', 'ABONO POR TRANSFERENCIA CTA. A LA VISTA(02513)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05829', 'ABONO POR TRANSFERENCIA DE CDA A DDA CP(05829)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05807', 'ABONO POR TRANSFERENCIA DE SEGUROS AP (ACC. PERSON(05807)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05803', 'ABONO POR TRANSFERENCIA DE VISTA A VISTA(05803)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05673', 'ABONO POR TRANSFERENCIA EN ATM(05673)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01011', 'ABONO POR TRANSFERENCIA EN LINEA BITAL(01011)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05911', 'ABONO POR TRANSFERENCIA EN LINEA BITAL(I(05911)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05003', 'ABONO POR TRANSFERENCIA POR C.D.A.(05003)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05011', 'ABONO POR TRANSFERENCIA POR CDA (LB)(05011)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05913', 'ABONO POR TRANSFERENCIAS A TERCEROS(05913)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09803', 'ABONO POR VENTA DE UDIS(09803)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09711', 'ABONO POR VENTA DE UDI''S (LINEA BITAL)(09711)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05539', 'ABONO POR VENTA GENERICA (ATM)(05539)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05547', 'ABONO POR VENTA GENERICA BD(05547)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04139', 'ABONO POR VENTA Y RENDIMIENTO DE PAPEL(04139)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01174', 'Abono Sin descripci�n(01174)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01425', 'ABONO SUMMIT-HOGAN(01425)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01219', 'ABONO TRANSF DE CUENTAS CONEXAS(01219)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01263', 'ABONO TRANSF. DE FONDOS PROGRAMADA(01263)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05423', 'ABONO TRANSFERENCIA BANCO EN SU EMPRESA(05423)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04179', 'ABONO TRANSFERENCIA C/V POR CONEXIONES(04179)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05635', 'ABONO TRANSFERENCIA HSBCNET C/V(05635)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05637', 'ABONO TRANSFERENCIA HSBCNET C/V(05637)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01441', 'ABONO TRANSFERENCIA MISMO BANCO(01441)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04183', 'ABONO TRANSFERENCIA POR CONEXIONES(04183)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05631', 'ABONO TRANSFERENCIA RECIBIDA POR HSBCNET(05631)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04573', 'ABONO VIVIENDA RCV (RETIRO CESANTIA Y VEJEZ)(04573)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05601', 'ABONO X COMISION CON IVA(05601)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '07023', 'ABONOS VARIOS POR CAJERO EN NUMERO DE OPS(07023)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05007', 'ACLARACIONES CARGOS CDMS(05007)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05005', 'ACLARACIONES DEPOSITOS CDMS(05005)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01117', 'ACUMULADO DE SALDOS CONTABLES -SYS-(01117)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05227', 'AJUSTE A LA PROVISION DE I.S.R.(05227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '33227', 'AJUSTE A LA PROVISION DE INTERESES(33227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '32227', 'AJUSTE DE INTERESES(32227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03227', 'AJUSTE DE INTS PROVISIONADOS EN TDA(03227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '32117', 'AJUSTE DE INTS PROVISIONADOS EN TDA(32117)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '11127', 'AJUSTE INTERESES ACUMULADOS CUENTAS ESPECIALES(11127)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '23227', 'AJUSTE PROV. INTS. CDA FUSION HSBC MN(23227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '13227', 'AJUSTE PROV. INTS. CDA FUSION HSBC US(13227)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '12509', 'APORT OBLIG PATRON -RTRO 101 / REV. TRASPASO SUBCUENTA SAR92 A AFORE C/(12509)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '14507', 'APORT OBLIG PATRON -VIV 101/REV. TRASPASO SUBCUENTA SAR92 A AFORE C/cve_sec_ec(14507)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '07001', 'APORTACION PATRONAL(07001)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '07003', 'APORTACION TRABAJADOR(07003)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01097', 'AUTO DEBIT TO PAY LOC MINIMUM PYMT DUE(01097)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03005', 'BALANCE CARRIED FORWARD TO GC ACCOUNT(03005)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05495', 'BICASH TO (NAME OF THE BENEFICIARY)(05495)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00482', 'BILLETES NAFIN PAGADOS(00482)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00456', 'BILLETES NAFINSA VENDIDOS(00456)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01641', 'BONIF AVALUOS SIN IVA / CARGO A CUENTA POR AVALUO /(01641)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00606', 'BONIF. AVALUOS CON IVA /PAGO DE AVALUO EN EFECTIVO(00606)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01489', 'BONIF. COMISION EXP O.P.(01489)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01491', 'BONIF.COMISION EXP.OP.DIVISA(01491)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00768', 'C/V MANUAL ORDEN PAGO RECIBIDA(00768)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00458', 'CAJA(00458)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00492', 'CAJA CONCENTRACION RECIBIDA(00492)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01371', 'CAMBIO DE SUBPRODUCTO(01371)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03371', 'CAMBIO DE SUBPRODUCTO EN CDA(03371)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01370', 'CAMBIO DE SUCURSAL/CENTRO DE COSTOS(01370)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03370', 'CAMBIO DE SUCURSAL/CENTRO DE COSTOS(03370)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00130', 'CANC OPMN CON COMPRAVENTA(00130)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00104', 'CANC.  DE GIRO CITIBANK DLS POR COMP-VTA(00104)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04107', 'CANC. DE CHEQUE DE CAJA OTROS CONCEPTOS(04107)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00576', 'CANC.GIRO/LIQ.-SUSP. TRANS. DLLS. EFECTI(00576)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01193', 'CANCELACION DE CTAS CON PAGO DE INTS(01193)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01195', 'CANCELACION DE CTAS SIN PAGO DE INTS(01195)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03248', 'CANCELACION DE INTERESES PAGADOS DE INVERSIONES(03248)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00114', 'CANCELACION DE O.P. EN MN. POR COMP-VTA.(00114)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01091', 'CANCELACION FORZADA CTA C/SALDO POS.(01091)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00770', 'CANCELACION ORDEN PAGO RECIBIDA(00770)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03057', 'CANCELLATION OF BALANCE IN NY AGENCY(03057)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03267', 'CAPITAL TRANSFERIDO DE INVERSIONES(03267)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05649', 'CARGO A COMPRAVENTA CONATONO A CUENTA EN PESOS(05649)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04043', 'CARGO A CUENTA DE CHEQUES POR C/V(04043)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05647', 'CARGO A CUENTA EN USD CON ABONO A COMPRA VENTA(05647)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05515', 'CARGO A CUENTA POR LIBERACION DE PEDIMENTO(05515)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01175', 'CARGO A CUENTA POR VENTA DE DIVISAS Y METALES(01175)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05755', 'CARGO A DDA POR APERTURA DE CDA EN CP(05755)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05757', 'CARGO A DDA POR REINVERSION DE CDA CP(05757)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01387', 'CARGO A FIDEICOMISOS O MANDATOS(01387)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01121', 'CARGO A INTERESES ACUMULADOS -SYS-(01121)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00061', 'CARGO A VISTA POR EXPEDICION CHEQUE DE CAJA(00061)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04581', 'CARGO ACLARACIONES VOUCHERS TDC/POS(04581)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01512', 'CARGO ADJUSTE DE I.V.A. POR CARGOS MISC(01512)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01508', 'CARGO AJUSTE DE I.V.A. POR CARGOS OD(01508)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01510', 'CARGO AJUSTE DE I.V.A. POR CHEQUE DEVUELTO(01510)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01506', 'CARGO AJUSTE DE I.V.A. POR SUSP PAGO(01506)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01504', 'CARGO AJUSTE IVA/CARGOS POR SERVICIO(01504)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04063', 'CARGO CANCEL. DE CHEQ. DE CAJA POR C/V(04063)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05583', 'CARGO CHQ HSBC PAGO SAR(05583)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05691', 'CARGO COBRANZA ESP CON CHEQUE(05691)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05689', 'CARGO COBRANZA ESP DESCUENTO(05689)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01651', 'CARGO COMISION COBRANZA DOCUMENTARIA(01651)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05827', 'CARGO COMISION COBRANZA DOCUMENTARIA (HIE)(05827)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01655', 'CARGO COMISION CREDITO DOCUMENTARIO ( HIE)(01655)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05271', 'CARGO COMPRA DE VALORES TREATS(05271)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04149', 'CARGO CON DESCRIPCION VARIABLE(04149)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01238', 'CARGO CONSUMO CON TARJETA DE DEBITO(01238)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05025', 'CARGO CONSUMO CON TARJETA DE DEBITO(05025)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05197', 'CARGO CORRECCION DE ABONO INDEBIDO(05197)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05825', 'CARGO CREDITO DOCUMENTARIO (HIE)(05825)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05581', 'CARGO CTA PAGO DE SAR(05581)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04601', 'CARGO CUENTAS PROPIAS PESOS CEI(04601)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05455', 'CARGO DE COBRANZAS ESPECIAL(05455)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01590', 'CARGO DE I.S.R POR PAGO DE SORTEO(01590)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01123', 'CARGO DE INTERESES POR SOBREGIRO(01123)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01593', 'CARGO DE ISR POR PAGO DE SORTEO / COMISION POR PRODUCTOS NO FINANCIEROS(01593)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05679', 'CARGO DESDE OTRAS EMPRESAS(05679)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05683', 'CARGO DESDE OTRAS EMPRESAS(05683)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04577', 'CARGO DEVOLUCION VOUCHERS TDC(04577)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05571', 'CARGO DOTACIONES DE EFECTIVO CON CARTA(05571)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01401', 'CARGO ENGANCHE DE CREDITO DE CONSUMO(01401)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04621', 'CARGO FONDEO DE CUENTA CEI(04621)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01617', 'CARGO I.V.A. DE LA COMISION (HIE)(01617)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01113', 'CARGO INTS MORATORIOS LINEA CREDITO(01113)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01115', 'CARGO INTS MORATORIOS LOC(01115)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05627', 'CARGO LIQUIDACION COBRANZA EXTRANJERA EN MN(05627)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01411', 'CARGO LIQUIDACION DE IMPORTE DEL CONSUMO(01411)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01197', 'CARGO MISCELANEO (BATCH CIERRE DIARIO) /RETIRO MISCELANEOS(01197)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '00218', 'CARGO MODULO DE CUENTAS CONCILIABLES(00218)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04523', 'CARGO ORDEN DE PAGO RECIBIDA CANCEL A LA PAR(04523)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05209', 'CARGO ORDEN DE PAGO SPEI(05209)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04061', 'CARGO ORDEN DE PAGO SPEUA(04061)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05561', 'CARGO P/LIQ TIP (TRANSF.INMEDIATA DE PAGOS)CON ABO(05561)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05565', 'CARGO P/LIQ TIP (TRANSF.INMEDIATA DE PAGOS)EN EFEC(05565)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04625', 'CARGO PAGO DE IMPUESTOS CEI(04625)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05153', 'CARGO PAGO DE NOMINA(05153)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05855', 'CARGO PAGO INTERBANCARIO A OTROS  BANCOS(05855)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05843', 'CARGO PAGO INTERBANCARIO BITAL(05843)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05859', 'CARGO PAGO INTERBANCARIO BITAL(05859)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05851', 'CARGO PAGO INTERBANCARIO G4(05851)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05971', 'CARGO PAGO SERVICIO TELEFONICO EN LINEA(05971)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05567', 'CARGO POR ABONO INDEBIDO TIP(05567)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04223', 'CARGO POR ACLARACION DE COBRANZA(04223)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05523', 'CARGO POR ACLARACION EN CAJERO AUTOMATICO(05523)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01127', 'CARGO POR AJUSTE A INTS ACUM -SYS-(01127)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01532', 'CARGO POR AJUSTE DE I.S.R.(01532)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03532', 'CARGO POR AJUSTE DE I.S.R. COBRADO(03532)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01161', 'CARGO POR AJUSTE DE INTERESES(01161)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '11161', 'CARGO POR AJUSTE DE INTERESES CUENTAS ESPECIALES(11161)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03261', 'CARGO POR AJUSTE DE INTERESES DE INVERISONES(03261)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01125', 'CARGO POR AJUSTE DE INTS. COBRADOS(01125)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05585', 'CARGO POR AJUSTE INT. SIN DESCRIPCION(05585)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05587', 'CARGO POR AJUSTE INT. SIN DESCRIPCION(05587)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05589', 'CARGO POR AJUSTE INT. SIN DESCRIPCION(05589)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04525', 'CARGO POR CANCEL ORDEN DE PAGO RECIBIDA POR C/V(04525)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04021', 'CARGO POR CANCELACION DE CHEQUE DE CAJA(04021)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01067', 'CARGO POR CARTA DE CREDITO(01067)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05065', 'CARGO POR CARTERA  S/36 / CARGO POR CARTERA HIPOTECARIA Y/O CCC(05065)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01065', 'CARGO POR CARTERA (SABI)(01065)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01069', 'CARGO POR CARTERA HIPOTECARIA(01069)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01681', 'CARGO POR CARTERA PEUGEOT(01681)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01685', 'CARGO POR CARTERA PEUGEOT(01685)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04545', 'CARGO POR CERTIFICACION DE CHEQUE(04545)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05053', 'CARGO POR CERTIFICACION DE CHEQUE(05053)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '08529', 'CARGO POR CERTIFICACION DE CHEQUE(08529)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04543', 'CARGO POR CHEQUE CERTIFICADO (CAMARA)(04543)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04539', 'CARGO POR CHEQUE CERTIFICADO (DEPOSITADO)(04539)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05353', 'CARGO POR CHEQUE DEPOSITADO(05353)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '08541', 'CARGO POR CHEQUE DEPOSITADO(08541)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01417', 'CARGO POR COBRANZA DE CREDITO DE CONSUMO(01417)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01423', 'CARGO POR COBRANZA TDC CON MOROSIDAD(01423)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05415', 'CARGO POR COBRANZAS ESPECIALES(05415)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09853', 'CARGO POR COMPRA DE UDIS(09853)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '09859', 'CARGO POR COMPRA DE UDI''S (LINEA BITAL)(09859)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05527', 'CARGO POR COMPRA EN CAJERO AUTOMATICO(05527)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '07523', 'CARGO POR COMPRA EN CAJERO FUERA LINEA(07523)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05535', 'CARGO POR COMPRA EN RED(05535)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '07573', 'CARGO POR COMPRA EN RED FUERA LINEA(07573)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '04053', 'CARGO POR COMPRA-VENTA(04053)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '05543', 'CARGO POR CONTRATO INTERBANCARIO(05543)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '01407', 'CARGO POR CREDITO DE CONSUMO(01407)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '03087', 'CARGO POR DEV DE CHEQ BITAL DEP EN INVERSIONES(03087)', 'Tesoreria', NULL, 0)
INSERT INTO MensajeLayout (Layout, Mensaje, Descripcion, TipoMovimiento, NaturalezaMovimiento, ConciliarMismaFecha) VALUES('HSBC2', '08545', 'CARGO POR DEV DE CHEQ C.I. DEP (FUERA DE LINEA)(08545)', 'Tesoreria', NULL, 0)
END

