SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spOportunidadSucursalLista

AS
BEGIN
DECLARE @ListaSucursal TABLE(Sucursal int, Nombre varchar(100))
INSERT INTO @ListaSucursal(Sucursal, Nombre) VALUES(-1, '(Todas)')
INSERT INTO @ListaSucursal SELECT Sucursal, Nombre FROM Sucursal WHERE Estatus='ALTA'
SELECT Sucursal, Nombre FROM @ListaSucursal
RETURN
END

