SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spPersonalDireccionFiscalActualizar

AS BEGIN
INSERT INTO PersonalDireccionFiscal(Personal, Icono, Mapeado)
SELECT p.Personal, 435, 0
FROM Personal p LEFT JOIN PersonalDireccionFiscal pd ON p.Personal = pd.Personal
WHERE pd.Personal IS NULL
RETURN
END

