SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSUsuarioInsertarMov
@Estacion     int,
@Usuario      varchar(10)

AS
BEGIN
INSERT POSUsuarioMov (Usuario, Mov, PuedeAutorizar)
SELECT				  Usuario, Mov, 1
FROM POSUsuarioMovTemp
WHERE Estacion = @Estacion
AND ID IN(SELECT ID FROM ListaID  WHERE Estacion = @Estacion)
END

