SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSHostDatosCaja
@Host 		varchar(20),
@Caja		varchar(10),
@Cajero		varchar(10)
 
AS
BEGIN
IF EXISTS(SELECT * FROM POSHost WHERE Host = @Host)
UPDATE POSHost
SET Caja = @Caja, Cajero = @Cajero
WHERE Host = @Host
ELSE
INSERT POSHost (
Host,  Caja,  Cajero)
VALUES (
@Host, @Caja, @Cajero)
END

