SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSCobroCreditoSaldoMayor
@ID	varchar(50)

AS
BEGIN
DECLARE
@Host			varchar(20),
@Caja	        varchar(20),
@Cluster		varchar(20)
EXEC spPOSHost @Host OUTPUT, @Cluster OUTPUT
SELECT @Caja = Caja
FROM POSL
WHERE ID = @ID
UPDATE POSLVenta SET Precio = 0.0
WHERE ID = @ID
UPDATE POSL SET Importe = 0.0
WHERE ID = @ID
INSERT POSLAccion (
Host,  Caja, Accion)
VALUES (
@Host, @Caja,'IMPORTE ANTICIPO' )
END

