SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSLDIADOResultado
@ID		varchar(36)

AS
BEGIN
SELECT NULLIF(Ok,0) Ok, OkRef, Mensaje, CadenaRespuesta, Cadena, IDLog
FROM POSLDIRespuestaTemp
WHERE ID = @ID
END

