SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSMovEliminarNoc
@Usuario		varchar(10) = NULL

AS
BEGIN
DECLARE
@ID varchar (36)
IF @Usuario IS NULL
BEGIN
DECLARE crSE1 CURSOR LOCAL FOR
SELECT ID
FROM POSL
WHERE Estatus IN ('PENDIENTE','SINAFECTAR', 'PORCOBRAR')
OPEN crSE1
FETCH NEXT FROM crSE1 INTO @ID
WHILE @@FETCH_STATUS <> -1
BEGIN
IF @@FETCH_STATUS <> -2
BEGIN
DELETE FROM POSL WHERE ID = @ID
DELETE FROM POSLVenta WHERE ID = @ID
DELETE FROM POSLCobro WHERE ID = @ID
DELETE FROM POSLSerieLote WHERE ID = @ID
END
FETCH NEXT FROM crSE1 INTO @ID
END
CLOSE crSE1
DEALLOCATE crSE1
END
ELSE
BEGIN
DECLARE crSE1 CURSOR LOCAL FOR
SELECT ID
FROM POSL
WHERE Estatus IN ('PENDIENTE','SINAFECTAR', 'PORCOBRAR')
AND Usuario = @Usuario
OPEN crSE1
FETCH NEXT FROM crSE1 INTO @ID
WHILE @@FETCH_STATUS <> -1
BEGIN
IF @@FETCH_STATUS <> -2
BEGIN
DELETE FROM POSL WHERE ID = @ID
DELETE FROM POSLVenta WHERE ID = @ID
DELETE FROM POSLCobro WHERE ID = @ID
DELETE FROM POSLSerieLote WHERE ID = @ID
END
FETCH NEXT FROM crSE1 INTO @ID
END
CLOSE crSE1
DEALLOCATE crSE1
END
END

