SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSHerrCteFrecuente
@Estacion   int

AS
BEGIN
INSERT POSHerrCteFrecuente(
Estacion, Cliente)
SELECT
@Estacion, Cliente
FROM Cte
WHERE Cliente IN (SELECT Clave FROM ListaST WHERE Estacion = @Estacion AND Clave NOT IN (SELECT Cliente FROM POSHerrCteFrecuente))
END

