SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC SpPropiedadInfonavit100
@Personal varchar (10)

AS BEGIN
SELECT Valor1 = CASE Valor WHEN ' ' THEN '0.00'
WHEN NULL THEN '0.00'
ELSE Valor end
FROM personalpropvalor
WHERE Rama = 'PER' AND Propiedad='% SDI Credito Infonavit' AND  Cuenta=@Personal 
END

