SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spProvDireccionFiscalActualizar

AS BEGIN
INSERT INTO ProvDireccionFiscal(Proveedor, Icono, Mapeado)
SELECT p.Proveedor, 435, 0
FROM Prov p LEFT JOIN ProvDireccionFiscal pd ON p.Proveedor = pd.Proveedor
WHERE pd.Proveedor IS NULL
RETURN
END

