SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spReconstruirSaldosIniciales

AS BEGIN
DECLARE
@Empresa	char(5),
@Ejercicio	int
DECLARE crSI CURSOR FOR
SELECT Empresa, Ejercicio
FROM Acum
GROUP BY Empresa, Ejercicio
ORDER BY Empresa, Ejercicio
OPEN crSI
FETCH NEXT FROM crSI INTO @Empresa, @Ejercicio
WHILE @@FETCH_STATUS <> -1
BEGIN
IF @@FETCH_STATUS <> -2
EXEC spTraspasarSaldos @Empresa, @Ejercicio
FETCH NEXT FROM crSI INTO @Empresa, @Ejercicio
END
CLOSE crSI
DEALLOCATE crSI
RETURN
END

