SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spRecEmpresaNombre
@Empresa      varchar(5)

AS BEGIN
SET NOCOUNT ON
IF EXISTS (SELECT TOP 1 Empresa FROM Empresa WHERE Empresa = @Empresa)
BEGIN
SELECT Nombre FROM Empresa WHERE Empresa = @Empresa
END
END

