SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spSucursalDireccionFiscalActualizar

AS BEGIN
INSERT INTO SucursalDireccionFiscal(Sucursal, Icono, Mapeado)
SELECT s.Sucursal, 435, 0
FROM Sucursal s LEFT JOIN SucursalDireccionFiscal sd ON s.Sucursal = sd.Sucursal
WHERE sd.Sucursal IS NULL
RETURN
END

