SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spTarjetaMonederoVerificar
@MonederoCB	varchar(20),
@Empresa	varchar(5)
AS BEGIN
DECLARE @Existe		bit
SET @Existe = 0
IF EXISTS (SELECT * FROM TarjetaMonedero WHERE Empresa = @Empresa AND Serie = @MonederoCB)
SET @Existe = 1
SELECT @Existe
END

