SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spTagLimpiar
(
@CampoXML varchar(MAX)
)

AS
BEGIN
DECLARE @TagLimpiar varchar(MAX)
SET @TagLimpiar = '<'+RTRIM(REPLACE(@CampoXML,'[',''))+'>'+'</'+RTRIM(REPLACE(@CampoXML,'[',''))+'>'
SET @TagLimpiar = RTRIM(REPLACE(@TagLimpiar,']',''))
SELECT @TagLimpiar
END

