SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spTMAArtListaSt
@EstacionTrabajo		int

AS
BEGIN
DELETE ListaSt WHERE Estacion = @EstacionTrabajo
INSERT INTO ListaSt(Estacion, Clave) SELECT DISTINCT @EstacionTrabajo, Articulo FROM WMSSurtidoProcesarD WHERE Estacion = @EstacionTrabajo AND Procesado = 0
END

