SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spValidaCantUbic
@ID		int,
@Existencia float

AS
DECLARE @cantidadA float
SELECT @cantidadA=SUM(Cantidad)  FROM InvArtUbicacionD WHERE  RID=@ID
IF @cantidadA>@Existencia
UPDATE  InvArtUbicacionD SET Cantidad=0 WHERE  RID=@ID
SELECT @cantidadA

