SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spVariableInit
@Estacion	int

AS BEGIN
UPDATE Variable
SET ValorChar = NULL,
ValorInt = NULL,
ValorFloat = NULL,
ValorDateTime = NULL,
ValorBit = NULL
WHERE Estacion = @Estacion
END

