SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spVentaImpuesto
@ID			AS INT,
@RID		AS INT

AS
BEGIN
SELECT a.Impuesto1
FROM Venta v
JOIN VentaD vd ON vd.ID=v.ID
JOIN Art a ON a.Articulo=vd.Articulo
WHERE v.ID=@ID AND VD.Renglon=@RID
END

