SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebCFDIsRecibosNomina
@Id			Int,
@Personal		Char(10)
AS BEGIN
SET NOCOUNT ON
SELECT DISTINCT a.Nombre
FROM AnexoMov a
JOIN NominaD b ON b.Id = a.Id
AND b.Personal = RTRIM(@Personal)
WHERE a.Rama = 'NOM'
AND a.id = @Id
AND Nombre like RTRIM(@Personal) + '%'
RETURN
END

