SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebArtEliminarImagenCombinacion
@IDCombinacion   int

AS BEGIN
UPDATE WebArtVariacionCombinacion SET Imagen =NULL, TipoArchivo = NULL, NombreImagen = NULL
WHERE ID = @IDCombinacion
END

