SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebArtBorrarWebCatArtTemp
@Estacion        int

AS BEGIN
DECLARE
@CategoriaID     int
DELETE WebCatArtTemp
WHERE Estacion = @Estacion
END

