SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebEnvolturaInsertarImagen
@IDEnvoltura	int,
@Nombre          varchar(255)

AS BEGIN
DECLARE
@Orden int
IF NULLIF(@IDEnvoltura,'') IS NULL OR NULLIF(@Nombre,'') IS NULL RETURN
UPDATE WebEnvolturaRegalo SET Imagen = @Nombre WHERE ID = @IDEnvoltura
END

