SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebEjercicioIngresoPers
@Personal Char(10)
AS BEGIN
SET NOCOUNT ON
SELECT EjercicioInicial = CONVERT(Integer, DATEPART(YYYY, ISNULL(FechaAntiguedad, GETDATE())))
FROM PERSONAL
WHERE Estatus = 'ALTA'
AND Personal = @Personal
SET NOCOUNT OFF
RETURN
END

