SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spWebUltRegAsisteD
@Personal  Char(10)
AS BEGIN
SELECT TOP 1 Registro, HoraRegistro
FROM Asisted
WHERE FechaD = CONVERT(Datetime, CONVERT(Varchar, GETDATE(), 102), 102)
AND FechaA = CONVERT(Datetime, CONVERT(Varchar, GETDATE(), 102), 102)
AND Personal = @Personal
ORDER BY HoraRegistro DESC
RETURN
END

