SET DATEFIRST 7
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
SET ANSI_WARNINGS ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE sxDeleteRouter
@from VARCHAR(10),
@to VARCHAR(10)
AS
BEGIN
DECLARE @router_id VARCHAR(25)
SELECT @router_id = 'rt_'+@from+'_'+@to
DELETE FROM sx_router WHERE router_id = @router_id
DELETE FROM sx_trigger_router WHERE router_id = @router_id
END

