SET DATEFIRST 7
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
SET ANSI_WARNINGS ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE sxDisableRouter
@from VARCHAR(10),
@to VARCHAR(10)
AS
BEGIN
DECLARE @router_id VARCHAR(25)
SELECT @router_id = 'rt_'+@from+'_'+@to
UPDATE sx_router SET sync_on_update = 0, sync_on_insert = 0, sync_on_delete = 0 WHERE router_id = @router_id
END

