SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpCxGenerarEnBorrador
@Modulo		char(5),
@ID			int,
@CxEstatus   varchar(15)		OUTPUT
AS BEGIN
RETURN
END

