SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpEnviarCorreo
@Empresa	varchar(5),
@Para		varchar(8000) OUTPUT,
@Asunto		varchar(8000)  OUTPUT,
@Mensaje	varchar(8000) = NULL  OUTPUT,
@Anexos		varchar(8000) = NULL  OUTPUT,
@SQL		varchar(8000) = NULL OUTPUT,
@SQLAncho	int 	      = 250 OUTPUT,
@CC			varchar(8000) = NULL OUTPUT,
@Perfil		varchar(50)	OUTPUT
AS BEGIN
RETURN
END

