SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpGenerarCFDEncabezado
@Estacion		int,
@Modulo			char(5),
@ID			int,
@Layout			varchar(50),
@Validar		bit		= 0,
@Empresa		char(5),
@Sucursal		int,
@Cliente		varchar(10),
@EnviarA		int,
@EmpresaGLN		varchar(50),
@Version		varchar(10),
@Mov			varchar(20),
@MovID			varchar(20),
@Estatus			varchar(15),
@ConsecutivoModulo	char(5),
@ConsecutivoMov		varchar(20),
@Fecha			datetime,
@Serie 			varchar(20),
@Folio			bigint,
@MovTipo		varchar(20),
@tipoDeComprobante	varchar(20),
@TipoAddenda 		varchar(50),
@AddendaVersion 	varchar(10),
@Moneda			char(10),
@TipoCambio		float,
@Liverpool		bit,
@Gigante		bit,
@ComercialMexicana	bit,
@Elektra		bit,
@EHB			bit,
@Origen			varchar(20),
@OrigenID		varchar(20),
@SucursalGLN		varchar(50) 	OUTPUT,
@ClienteGLN		varchar(50) 	OUTPUT,
@EnviarAGLN		varchar(50) 	OUTPUT,
@Referencia		varchar(50) 	OUTPUT,
@ReferenciaFecha	datetime 	OUTPUT,
@FormaEnvio		varchar(50) 	OUTPUT,
@Condicion		varchar(50) 	OUTPUT,
@Vencimiento		datetime 	OUTPUT,
@formaDePago		varchar(100) 	OUTPUT,
@metodoDePago		varchar(100) 	OUTPUT,
@EmisorID 		varchar(20) 	OUTPUT,
@ReceptorID 		varchar(20) 	OUTPUT,
@ProveedorID 		varchar(20) 	OUTPUT,
@OrdenCompra 		varchar(50) 	OUTPUT,
@FechaOrdenCompra	datetime 	OUTPUT,
@DepartamentoClave	varchar(20) 	OUTPUT,
@DepartamentoNombre	varchar(100) 	OUTPUT,
@DepartamentoContacto   varchar(100) 	OUTPUT,
@Observaciones		varchar(100) 	OUTPUT,
@EnviarAClave		varchar(20) 	OUTPUT,
@Embarque 		varchar(50) 	OUTPUT,
@EmbarqueFecha 		datetime 	OUTPUT,
@Recibo 		varchar(50) 	OUTPUT,
@ReciboFecha 		datetime 	OUTPUT,
@MonedaClave		char(3) 	OUTPUT,
@FechaRequerida		datetime 	OUTPUT,
@TipoCondicion		varchar(20) 	OUTPUT,
@DescuentoClave		varchar(20) 	OUTPUT,
@Antecedente		varchar(50) 	OUTPUT,
@AntecedenteFecha	datetime 	OUTPUT,
@ReferenciaEnvio	varchar(14) 	OUTPUT,
@Ok					int		= NULL OUTPUT,
@OkRef				varchar(255)	= NULL OUTPUT,
@AgruparDetalle		bit = 0 OUTPUT,
@ClienteDireccion	varchar(100)= NULL  OUTPUT,
@EnviarADireccion   varchar(100) =  NULL  OUTPUT,
@Descuento          varchar(50) =  NULL  OUTPUT,
@RegimenFiscal      varchar(100) =  NULL  OUTPUT,
@NumeroCuentaPago   varchar(255) =  NULL  OUTPUT,
@CuentaPredial      varchar(100) =  NULL  OUTPUT,
@LugarExpedicion    varchar(255) =  NULL  OUTPUT
AS BEGIN
RETURN
END

