SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpJuegoHeredarOpcion
@Juego		varchar(20),
@Componente	varchar(20),
@SubCuenta	varchar(50)
AS BEGIN
SELECT @Subcuenta
RETURN
END

