SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpOfertaAplicar
@ID			int,
@Aplica		bit OUTPUT
AS
BEGIN
/*	IF (SELECT ISNULL(DescuentoGlobal,0) FROM Venta WHERE ID = @ID)>0
SELECT @Aplica = 0*/
RETURN
END

