SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpOk_30180
@Empresa			char(5),
@Usuario			char(10),
@Accion			char(20),
@Modulo			char(5),
@ID				int,
@MovAplica		varchar(20),
@MovAplicaID		varchar(20),
@Ok              int 		OUTPUT,
@OkRef           varchar(255) 	OUTPUT
AS BEGIN
RETURN
END

