SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpOpcionD
@Empresa	char(5),
@Opcion		char(1),
@Articulo	varchar(20),
@SubCuenta	varchar(50)
AS BEGIN
SELECT Numero, Nombre
FROM OpcionD
WHERE Opcion = @Opcion
RETURN
END

