SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC xpOportunidadPlanPreliminarAgregar
@ID			int,
@Usuario	varchar(10),
@Sucursal	int,
@Plantilla	varchar(20),
@Ok			int			 = NULL OUTPUT,
@OkRef		varchar(255) = NULL OUTPUT
AS
BEGIN
RETURN
END

