SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE xpPOSVentaInsertaClienteVerificar
@Empresa		varchar(5),
@ID			varchar(50),
@Codigo		varchar(30),
@Cliente		varchar(10),
@CtaDinero		varchar(10),
@Ok			int	OUTPUT,
@OkRef			int	OUTPUT
AS
BEGIN
RETURN
END

