
[Forma]
Clave=DM0237AgenteFrm
Icono=0
Modulos=(Todos)
Nombre=Agentes

ListaCarpetas=lista
CarpetaPrincipal=lista
PosicionInicialIzquierda=263
PosicionInicialArriba=223
PosicionInicialAlturaCliente=273
PosicionInicialAncho=500
[lista]
Estilo=Hoja
Clave=lista
BusquedaRapidaControles=S
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=DM0237AgenteVis
Fuente={Tahoma, 8, Negro, []}
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Automática
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=agente
FiltroModificarEstatus=S
FiltroCambiarPeriodo=S
FiltroBuscarEn=S
FiltroFechasCambiar=S
FiltroFechasNormal=S
FiltroFechasNombre=&Fecha
BusquedaRapida=S
BusquedaInicializar=S
BusquedaRespetarControles=S
BusquedaAncho=20
BusquedaEnLinea=S
CarpetaVisible=S

[lista.agente]
Carpeta=lista
Clave=agente
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=10
ColorFondo=Blanco
ColorFuente=Negro

[lista.Columnas]
agente=64
