[Forma]
Clave=DM0278HistoricoCancelacionesSegurosVidaFRM
Icono=396
Modulos=(Todos)
ListaCarpetas=(Variables)<BR>Historico
CarpetaPrincipal=(Variables)
PosicionInicialAlturaCliente=949
PosicionInicialAncho=1298
PosicionInicialIzquierda=-9
PosicionInicialArriba=-9
PosicionSec1=78
BarraHerramientas=S
AccionesTamanoBoton=15x5
AccionesDerecha=S
ListaAcciones=Actualizar<BR>Imprimir<BR>Excel
VentanaTipoMarco=Sencillo
VentanaPosicionInicial=por Diseño
VentanaEstadoInicial=Normal
Nombre=CANCELACIONES DE SEGUROS DE VIDA CONCLUIDOS
ExpresionesAlMostrar=ASIGNA(Mavi.DM0278Ejercicio, Año(hoy))<BR>ASIGNA(Mavi.DM0278Periodo,Si<BR> (Dia(Hoy)<=15)<BR>Entonces<BR>  (Mes(Hoy)*2-1)<BR>Sino<BR>   (Mes(Hoy)*2)<BR>Fin)<BR>ASIGNA(Mavi.DM0278SucursalHis,nulo)<BR>ASIGNA(Mavi.DM0278FiltroClienteHis,nulo)<BR>ASIGNA(Mavi.DM0278FiltroNominaHis,nulo)
[(Variables)]
Estilo=Ficha
Clave=(Variables)
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=(Variables)
Fuente={Tahoma, 8, Negro, []}
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=Mavi.DM0278Ejercicio<BR>Mavi.DM0278Periodo<BR>Mavi.DM0278SucursalHis<BR>Mavi.DM0278FiltroClienteHis<BR>Mavi.DM0278FiltroNominaHis
CarpetaVisible=S
PermiteEditar=S
FichaEspacioEntreLineas=0
FichaEspacioNombres=0
FichaColorFondo=Plata
[(Variables).Mavi.DM0278Ejercicio]
Carpeta=(Variables)
Clave=Mavi.DM0278Ejercicio
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
[(Variables).Mavi.DM0278Periodo]
Carpeta=(Variables)
Clave=Mavi.DM0278Periodo
Editar=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
[Historico]
Estilo=Hoja
Clave=Historico
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=B1
Vista=DM0278HistoricoCancelacionesSegurosVidaVIS
Fuente={Tahoma, 8, Negro, []}
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Automática
CampoColorLetras=Negro
CampoColorFondo=Blanco
CarpetaVisible=S
ListaEnCaptura=SeguroVida<BR>Cliente<BR>NominaVendedor<BR>NombreVendedor<BR>SucursalOrigen<BR>NominaCancela<BR>Nombrecancela<BR>SucursalCancela<BR>Motivo<BR>FechaEmision<BR>FechaCancelacion<BR>DiasTranscurridos

[Historico.Cliente]
Carpeta=Historico
Clave=Cliente
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=15
ColorFondo=Blanco
[Historico.NominaVendedor]
Carpeta=Historico
Clave=NominaVendedor
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=15
ColorFondo=Blanco
[Historico.NombreVendedor]
Carpeta=Historico
Clave=NombreVendedor
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=50
ColorFondo=Blanco
[Historico.SucursalOrigen]
Carpeta=Historico
Clave=SucursalOrigen
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
[Historico.NominaCancela]
Carpeta=Historico
Clave=NominaCancela
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=15
ColorFondo=Blanco
[Historico.Nombrecancela]
Carpeta=Historico
Clave=Nombrecancela
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=50
ColorFondo=Blanco
[Historico.SucursalCancela]
Carpeta=Historico
Clave=SucursalCancela
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
[Historico.Motivo]
Carpeta=Historico
Clave=Motivo
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=50
ColorFondo=Blanco
[Historico.FechaEmision]
Carpeta=Historico
Clave=FechaEmision
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
[Historico.FechaCancelacion]
Carpeta=Historico
Clave=FechaCancelacion
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
[Historico.DiasTranscurridos]
Carpeta=Historico
Clave=DiasTranscurridos
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
[Historico.Columnas]
Factura=94
Cliente=94
NominaVendedor=94
NombreVendedor=304
SucursalOrigen=89
NominaCancela=94
Nombrecancela=304
SucursalCancela=96
Motivo=304
FechaEmision=94
FechaCancelacion=110
DiasTranscurridos=89
SeguroVida=109
NombreCancela=304
[Acciones.Actualizar]
Nombre=Actualizar
Boton=82
NombreDesplegar=Actualizar
EnBarraHerramientas=S
TipoAccion=Controles Captura
ClaveAccion=Actualizar Vista
Activo=S
Visible=S
NombreEnBoton=S
Multiple=S
ListaAccionesMultiples=Variables Asignar<BR>Actualizar Vista
[Acciones.Imprimir]
Nombre=Imprimir
Boton=4
NombreEnBoton=S
NombreDesplegar=&Imprimir
EnBarraHerramientas=S
TipoAccion=Reportes Impresora
Activo=S
Visible=S
ClaveAccion=DM0278HistoricoCancelacionesSegurosVidaREPIMP
[Acciones.Excel]
Nombre=Excel
Boton=115
NombreDesplegar=Enviar a &Excel
EnBarraHerramientas=S
TipoAccion=Reportes Excel
Activo=S
Visible=S
NombreEnBoton=S
ClaveAccion=DM0278HistoricoCancelacionesSegurosVidaREP
[Acciones.Actualizar.Variables Asignar]
Nombre=Variables Asignar
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.Actualizar.Actualizar Vista]
Nombre=Actualizar Vista
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Actualizar Vista
Activo=S
Visible=S

[Historico.SeguroVida]
Carpeta=Historico
Clave=SeguroVida
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=15
ColorFondo=Blanco

[(Variables).Mavi.DM0278SucursalHis]
Carpeta=(Variables)
Clave=Mavi.DM0278SucursalHis
Editar=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco

[(Variables).Mavi.DM0278FiltroClienteHis]
Carpeta=(Variables)
Clave=Mavi.DM0278FiltroClienteHis
Editar=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco

[(Variables).Mavi.DM0278FiltroNominaHis]
Carpeta=(Variables)
Clave=Mavi.DM0278FiltroNominaHis
Editar=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco


