[Forma]
Clave=MaviSegurosVidaFrm
Nombre=Tipo de Cobertura Seguro VIDA
Icono=0
Modulos=(Todos)
ListaCarpetas=(vista)
CarpetaPrincipal=(vista)
PosicionInicialIzquierda=364
PosicionInicialArriba=310
PosicionInicialAlturaCliente=113
PosicionInicialAncho=295
VentanaSiempreAlFrente=S
VentanaTipoMarco=Sencillo
VentanaPosicionInicial=Centrado
VentanaEstadoInicial=Normal
[(vista)]
Estilo=Hoja
Clave=(vista)
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=MaviSegurosVida
Fuente={Tahoma, 8, Negro, []}
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Automática
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=ARTICULO
CarpetaVisible=S
[(vista).ARTICULO]
Carpeta=(vista)
Clave=ARTICULO
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
ColorFuente=Negro
[(vista).Columnas]
ARTICULO=124

