[Forma]
Clave=RM0094ProvListaAgentFrm
Nombre=Proveedores - Agentes
Icono=0
Modulos=(Todos)
MovModulo=(Todos)
PosicionInicialAlturaCliente=452
PosicionInicialAncho=742
BarraHerramientas=S
EsConsultaExclusiva=S
AccionesTamanoBoton=15x5
AccionesDerecha=S
ListaCarpetas=Lista
CarpetaPrincipal=Lista
PosicionInicialIzquierda=364
PosicionInicialArriba=71
ListaAcciones=Seleccionar
[Lista]
Estilo=Iconos
PestanaOtroNombre=S
PestanaNombre=Proveedores - Agentes
Clave=Lista
BusquedaRapidaControles=S
MenuLocal=S
PermiteLocalizar=S
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=RM0094ProvAgentVis
Fuente={Tahoma, 8, Negro, []}
CampoColorLetras=Negro
CampoColorFondo=Blanco
FiltroModificarEstatus=S
FiltroCambiarPeriodo=S
FiltroBuscarEn=S
FiltroFechasCambiar=S
FiltroFechasNormal=S
FiltroFechasNombre=&Fecha
CarpetaVisible=S
ListaEnCaptura=Nombre<BR>Tipo
FiltroPredefinido1=
FiltroPredefinido2=
FiltroSituacionTodo=S
FiltroListaEstatus=ALTA<BR>APROBADO<BR>BLOQUEADO<BR>BAJA
FiltroEstatusDefault=ALTA
BusquedaRapida=S
BusquedaInicializar=S
BusquedaEnLinea=S
ListaAcciones=Actualizar<BR>Personalizar 
Filtros=S
IconosCampo=(sin Icono)
IconosEstilo=Detalles
IconosAlineacion=de Arriba hacia Abajo
IconosConSenales=S
ElementosPorPagina=200
FiltroPredefinido=S
FiltroGrupo1=Categoria
FiltroNullNombre=(sin clasificar)
FiltroEnOrden=S
FiltroTodoNombre=(Todo)
FiltroAncho=20
FiltroRespetar=S
FiltroTipo=Múltiple (por Grupos)
IconosSubTitulo=<T>Proveedor - Agente<T>
BusquedaRespetarControles=S
IconosNombre=RM0094ProvAgentVis:Proveedor
FiltroEstatus=S
FiltroSituacion=S
[Lista.Columnas]
0=-2
1=-2
2=-2
[Lista.Nombre]
Carpeta=Lista
Clave=Nombre
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=100
ColorFondo=Blanco
ColorFuente=Negro
[Acciones.Actualizar]
Nombre=Actualizar 
Boton=0
NombreDesplegar=&Actualizar
EnMenu=S
TipoAccion=Controles Captura
Activo=S
Visible=S
ClaveAccion=Actualizar Vista
[Acciones.Personalizar]
Nombre=Personalizar
Boton=0
NombreDesplegar=&Personalizar Campos
EnMenu=S
TipoAccion=Controles Captura
Activo=S
Visible=S
Carpeta=(Carpeta principal)
ClaveAccion=Mostrar Campos
[Acciones.Seleccionar]
Nombre=Seleccionar
Boton=23
NombreEnBoton=S
NombreDesplegar=&Seleccionar
EnBarraHerramientas=S
TipoAccion=Ventana
ClaveAccion=Seleccionar
Activo=S
Visible=S
[Lista.Tipo]
Carpeta=Lista
Clave=Tipo
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=15
ColorFondo=Blanco
ColorFuente=Negro
