[Forma]
Clave=RM0952BRubroagentegasFrm
Nombre=Gastos por Agente
Icono=0
Modulos=(Todos)
ListaCarpetas=Lista<BR>RAMA
CarpetaPrincipal=Lista
AccionesTamanoBoton=15x5
AccionesDerecha=S
PosicionInicialIzquierda=401
PosicionInicialArriba=246
PosicionInicialAlturaCliente=512
PosicionInicialAncho=695
PosicionSec1=55
BarraAcciones=S
BarraHerramientas=S
ListaAcciones=Generar<BR>Preeliminar<BR>Imprimir<BR>Excel<BR>Cerrar
[Lista]
Estilo=Ficha
Clave=Lista
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=(Variables)
Fuente={Tahoma, 8, Negro, []}
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=Mavi.RM0952BRubroAgenteVar<BR>Info.MesDSTMavi<BR>Info.Ano
CarpetaVisible=S
PermiteEditar=S
FichaEspacioEntreLineas=0
FichaEspacioNombres=0
FichaColorFondo=Plata
[Lista.Info.MesDSTMavi]
Carpeta=Lista
Clave=Info.MesDSTMavi
Editar=S
LineaNueva=N
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
ColorFuente=Negro
[Lista.Info.Ano]
Carpeta=Lista
Clave=Info.Ano
Editar=S
LineaNueva=N
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.Columnas]
NOMINA=64
NOMBRE=224
COMBUSTIBLE=87
HOTEL=64
INTERNET=64
MANTTO=64
MENSAJERIA=67
OTROS=64
PEAJE=92
MES=64
ANIO=64
[Acciones.acepto.MES]
Nombre=MES
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.acepto.Actualiza]
Nombre=Actualiza
Boton=0
TipoAccion=Expresion
Activo=S
Visible=S
Expresion=Forma.ActualizarVista
[Acciones.acepto.Anio]
Nombre=Anio
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
o=S
Visible=S
aveAccion=Variables Asignar
Activo=S
Visible=S
o=S
Visible=S
[Acciones.acepto.MESES]
Nombre=MESES
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.acepto.ANO]
Nombre=ANO
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.Cerrar]
Nombre=Cerrar
Boton=23
NombreDesplegar=&Cerrar
TipoAccion=Ventana
ClaveAccion=Cerrar
Activo=S
Visible=S
NombreEnBoton=S
EnBarraHerramientas=S
[Acciones.Preeliminar]
Nombre=Preeliminar
Boton=6
NombreDesplegar=&Preeliminar
EnBarraHerramientas=S
Activo=S
Visible=S
NombreEnBoton=S
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Multiple=S
ListaAccionesMultiples=preeliminar<BR>cerrar
[Acciones.acepto.actualizar]
Nombre=actualizar
Boton=0
TipoAccion=Expresion
Expresion=forma.actualizarVista
[Acciones.Preeliminar.preeliminar]
Nombre=preeliminar
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.Preeliminar.cerrar]
Nombre=cerrar
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar / Ventana Aceptar
Activo=S
Visible=S
[Acciones.Generar.Mes]
Nombre=Mes
Boton=0
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
Activo=S
Visible=S
[Acciones.Generar]
Nombre=Generar
Boton=92
NombreEnBoton=S
NombreDesplegar=&Generar
Multiple=S
EnBarraHerramientas=S
TipoAccion=Controles Captura
ClaveAccion=Variables Asignar
ListaAccionesMultiples=Mes<BR>Act
Activo=S
Visible=S
[Acciones.Generar.Act]
Nombre=Act
Boton=0
TipoAccion=Expresion
Expresion=Forma.ActualizarVista
Activo=S
Visible=S
[RAMA.NOMINA]
Carpeta=RAMA
Clave=NOMINA
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.NOMBRE]
Carpeta=RAMA
Clave=NOMBRE
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=100
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.COMBUSTIBLE]
Carpeta=RAMA
Clave=COMBUSTIBLE
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.HOTEL]
Carpeta=RAMA
Clave=HOTEL
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.INTERNET]
Carpeta=RAMA
Clave=INTERNET
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.MANTTO]
Carpeta=RAMA
Clave=MANTTO
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.MENSAJERIA]
Carpeta=RAMA
Clave=MENSAJERIA
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.OTROS]
Carpeta=RAMA
Clave=OTROS
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[RAMA.PEAJE]
Carpeta=RAMA
Clave=PEAJE
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
ColorFondo=Blanco
ColorFuente=Negro
[Acciones.Excel]
Nombre=Excel
Boton=115
NombreEnBoton=S
NombreDesplegar=&Excel
EnBarraHerramientas=S
TipoAccion=Reportes Excel
ClaveAccion=RM0952BRubroagenteRepXLS
Activo=S
Visible=S
[Acciones.Imprimir]
Nombre=Imprimir
Boton=4
NombreDesplegar=&Imprimir
EnBarraHerramientas=S
TipoAccion=Reportes Impresora
ClaveAccion=RM0952BRubroagenteRepImp
Activo=S
Visible=S
NombreEnBoton=S
[Lista.Mavi.RM0952BRubroAgenteVar]
Carpeta=Lista
Clave=Mavi.RM0952BRubroAgenteVar
Editar=S
LineaNueva=N
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
ColorFuente=Negro
[RAMA]
Estilo=Hoja
Clave=RAMA
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=B1
Vista=RM0952BRubroagenteSpVis
Fuente={Tahoma, 8, Negro, []}
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=NOMINA<BR>NOMBRE<BR>COMBUSTIBLE<BR>HOTEL<BR>INTERNET<BR>MANTTO<BR>MENSAJERIA<BR>OTROS<BR>PEAJE
CarpetaVisible=S
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Automática

