SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spActivoFijoSugerirCategorias
@EstacionTrabajo		int

AS BEGIN
DELETE ActivoFijoSugerir WHERE Estacion = @EstacionTrabajo
INSERT INTO ActivoFijoSugerir(Estacion, Categoria) SELECT @EstacionTrabajo, Categoria FROM ActivoFCat WITH(NOLOCK) ORDER BY Categoria
RETURN
END

