SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spAfectacionUsuario
@SPID			int,
@Usuario		varchar(10)

AS
BEGIN
DELETE AfectacionUsuario WHERE SPID = @SPID
INSERT INTO AfectacionUsuario(SPID, Usuario) VALUES(@SPID, @Usuario)
END

