SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE speDocInBorrarHerrTablaSt
@Estacion         int

AS BEGIN
DELETE eDocInHerrTablaST WHERE Estacion = @Estacion
DELETE eDocInHerrTablaSTD WHERE Estacion = @Estacion
END

