SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE speDocHabilitarProcedimientosOle

AS
BEGIN
EXEC sp_configure 'show advanced option', '1'
RECONFIGURE
EXEC sp_configure 'Ole Automation Procedures', '1'
RECONFIGURE
END

