SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spEmpresaCfgMovWMS
@Campo			varchar(50),
@Empresa		char(5)

AS BEGIN
DECLARE
@Resultado	varchar(50),
@SQL		nvarchar(max)
SELECT @Resultado = NULL
SELECT @sql = 'SELECT '+ @Campo + ' FROM EmpresaCfgMovWMS WITH (NOLOCK) WHERE Empresa ='''+@Empresa+''''
EXEC sp_executesql @sql
RETURN
END

