SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spExtraerMoney
@Texto 	  	varchar(8000)	OUTPUT,
@Money     	money		OUTPUT,
@Separador	varchar(10)

AS BEGIN
DECLARE
@MoneySt	varchar(255)
SELECT @Money = NULL
EXEC spExtraerDato @Texto OUTPUT, @MoneySt OUTPUT, @Separador
IF dbo.fnEsNumerico(@MoneySt) = 1
SELECT @Money = CONVERT(money, @MoneySt)
RETURN
END

