SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spGenerarCRAlmacen
@Empresa	varchar(5),
@Sucursal	int

AS BEGIN
SELECT '<?xml version="1.0" encoding="UTF-8" ?>'
SELECT '<crAlmacen>'
SELECT '</crAlmacen>'
RETURN
END

