SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spGenerarCRArtT

AS BEGIN
SELECT '<?xml version="1.0" encoding="UTF-8" ?>'
SELECT '<crArtT>'
SELECT '</crArtT>'
RETURN
END

