SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spInsertaEnArchivo2
(
@IDArchivo		int,
@Cadena		varchar(MAX),
@Ok				int = NULL OUTPUT,
@OkRef			varchar(255) = NULL OUTPUT
)

AS
BEGIN
DECLARE
@ResultadoOLE	int
EXECUTE @ResultadoOLE = sp_OAMethod @IDArchivo, 'Write', NULL, @Cadena
IF @ResultadoOLE <> 0 SET @Ok = 710520
END

