SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROC spMontacargaListST
@Estacion       int

AS BEGIN
DELETE ListaID WHERE Estacion=@Estacion
INSERT INTO ListaID (Estacion, ID)
SELECT @Estacion, IDLista
FROM dbo.fnWMSMontacargaTareaAgrupado (@Estacion)
WHERE Guia IN (SELECT Clave
FROM ListaSt (NOLOCK)
WHERE Estacion=@Estacion)
RETURN
END

