SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spModificarAcceso
@Empresa Varchar(5),
@Usuario  varchar(10)

AS BEGIN
DECLARE  @ID int
SELECT @ID = MAX(ID)
FROM Acceso WITH (NOLOCK)
WHERE Empresa = @Empresa
AND Usuario = @Usuario
UPDATE Acceso SET SPID = @@SPID
WHERE ID = @ID
END

