SET DATEFIRST 7    
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1  
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spMovInfo
@ID		int 		       OUTPUT,
@Modulo		char(5),
@Mov		char(20) 	= NULL OUTPUT,
@MovID		varchar(20) 	= NULL OUTPUT,
@Estatus	char(15) 	= NULL OUTPUT,
@Sucursal	int 		= NULL OUTPUT,
@UEN		int		= NULL OUTPUT,
@FechaEmision	datetime	= NULL	OUTPUT,
@Empresa	char(5)		= NULL 	OUTPUT,
@CtoTipo	varchar(20)  	= NULL	OUTPUT,
@Contacto	char(10)	= NULL 	OUTPUT,
@EnviarA	int		= NULL	OUTPUT,
@Situacion	varchar(50)	= NULL	OUTPUT,
@SituacionFecha	datetime	= NULL	OUTPUT,
@Proyecto	varchar(50)	= NULL	OUTPUT,
@Concepto	varchar(50)	= NULL	OUTPUT,
@Referencia	varchar(50)	= NULL	OUTPUT,
@Usuario	char(10)	= NULL	OUTPUT,
@MovTipo	varchar(20)	= NULL	OUTPUT,
@Ejercicio	int		= NULL	OUTPUT,
@Periodo	int		= NULL	OUTPUT,
@FechaCancelacion datetime	= NULL	OUTPUT,
@Clase		varchar(50)	= NULL	OUTPUT,
@SubClase	varchar(50)	= NULL	OUTPUT,
@Causa		varchar(50) 	= NULL	OUTPUT,
@FormaEnvio	varchar(50) 	= NULL	OUTPUT,
@Condicion	varchar(50) 	= NULL	OUTPUT,
@ZonaImpuesto	varchar(30)  	= NULL	OUTPUT,
@CtaDinero	varchar(10)	= NULL	OUTPUT,
@Cajero		varchar(10)	= NULL	OUTPUT,
@Moneda		varchar(10)	= NULL	OUTPUT,
@TipoCambio 	float 		= NULL	OUTPUT,
@SituacionUsuario varchar(10)	= NULL	OUTPUT,
@SituacionNota	  varchar(100)	= NULL	OUTPUT,
@Observaciones	varchar(100)	= NULL	OUTPUT,
@Importe	money		= NULL	OUTPUT,
@Impuestos	money		= NULL	OUTPUT,
@Retenciones	money		= NULL	OUTPUT,
@Total		money		= NULL	OUTPUT,
@UltimoCambio	datetime	= NULL	OUTPUT,
@OrigenTipo	varchar(10)	= NULL	OUTPUT,
@Origen		varchar(20)	= NULL	OUTPUT,
@OrigenID	varchar(20)	= NULL	OUTPUT,
@RamaID		int		= NULL	OUTPUT,
@Vencimiento	datetime = NULL OUTPUT, 
@FechaRegistro	datetime = NULL OUTPUT  

AS BEGIN
SELECT @FechaEmision = NULL, @Empresa = NULLIF(@Empresa,''), @Sucursal = NULL, @Estatus = NULL, @Situacion = NULL, @SituacionFecha = NULL, @SituacionUsuario = NULL, @SituacionNota = NULL,
@UEN = NULL, @CtoTipo = NULL, @Contacto = NULL, @EnviarA = NULL, @Proyecto = NULL, @Concepto = NULL, @Referencia = NULL, @Usuario = NULL,
@Ejercicio = NULL, @Periodo = NULL, @FechaCancelacion = NULL,
@Clase = NULL, @SubClase = NULL, @Causa = NULL, @FormaEnvio = NULL, @Condicion = NULL, @Condicion = NULL, @ZonaImpuesto = NULL,
@Moneda = NULL, @TipoCambio = NULL, @Cajero = NULL, @CtaDinero = NULL, @Observaciones = NULL, @Importe = NULL, @Impuestos = NULL, @Retenciones = NULL, @Total = NULL,
@UltimoCambio = NULL, @OrigenTipo = NULL, @Origen = NULL, @OrigenID = NULL, @RamaID = NULL, @Vencimiento = NULL, @FechaRegistro = NULL 
IF @ID IS NOT NULL
SELECT @Mov = NULL, @MovID = NULL
IF @Modulo = 'VTAS'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Cliente',    @Contacto = Cliente, @EnviarA = EnviarA, @Clase = Clase, @SubClase = SubClase, @Causa = Causa, @FormaEnvio = FormaEnvio, @Condicion = Condicion, @ZonaImpuesto = ZonaImpuesto, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Retenciones = Retencion, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Venta WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CXC'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Cliente',    @Contacto = Cliente, @EnviarA = ClienteEnviarA, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @Cajero = Cajero, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Retenciones = ISNULL(Retencion, 0.0) + ISNULL(Retencion2, 0.0) + ISNULL(Retencion3, 0.0), @RamaID = RamaID, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Cxc WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'ST'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Cliente',    @Contacto = Cliente, @EnviarA = EnviarA, @Clase = Clase, @SubClase = SubClase, @Importe = Importe, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Soporte WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'COMS'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Proveedor',  @Contacto = Proveedor, @Causa = Causa, @FormaEnvio = FormaEnvio, @Condicion = Condicion, @ZonaImpuesto = ZonaImpuesto, @Moneda = Moneda, @TipoCambio = TipoCambio, @Importe = Importe, @Impuestos = Impuestos, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Compra WITH(NOLOCK)  WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CXP'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Proveedor',  @Contacto = Proveedor, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @Cajero = Cajero, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Retenciones = ISNULL(Retencion, 0.0) + ISNULL(Retencion2, 0.0) + ISNULL(Retencion3, 0.0), @RamaID = RamaID, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Cxp WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'AGENT' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Agente',     @Contacto = Agente, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Retenciones = Retencion, @FechaRegistro = FechaRegistro FROM Agent WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'GAS'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = NULL,     @Referencia = NULL,       @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Proveedor',  @Contacto = Acreedor, @Clase = Clase, @SubClase = SubClase, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Retenciones = Retencion, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Gasto WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'DIN'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = ContactoTipo, @Contacto = Contacto, @Moneda = Moneda, @TipoCambio = TipoCambio, @Cajero = Cajero, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Dinero WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'AF'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Proveedor',  @Contacto = Proveedor, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM ActivoFijo WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'VALE'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Cliente',    @Contacto = Cliente, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Vale WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CR'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Agente',     @Contacto = Cajero, @Moneda = Moneda, @TipoCambio = TipoCambio, @Cajero = Cajero, @FechaRegistro = FechaRegistro FROM CR WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CAM'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = 'Cliente',    @Contacto = Cliente, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Cambio WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PACTO' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @CtoTipo = ContactoTipo,    @Contacto = (CASE ContactoTipo WHEN 'Cliente' THEN Cliente WHEN 'Prospecto' THEN Prospecto WHEN 'Proveedor' THEN Proveedor WHEN 'Personal' THEN Personal WHEN 'Agente' THEN Agente ELSE NULL END), @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Contrato WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CAP'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Capital WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'INC'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Incidencia WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CONC'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Conciliacion WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PPTO'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Presup WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CREDI' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Credito WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'TMA'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro FROM TMA WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'RSS'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro FROM RSS WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CMP'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro FROM Campana WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'FIS'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro  FROM Fiscal WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CONTP' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro  FROM ContParalela WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'OPORT' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro, @Importe = ImporteOportunidad FROM Oportunidad WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CORTE' SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Vencimiento = NULL, @FechaRegistro = FechaRegistro  FROM Corte WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'FRM'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro FROM FormaExtra WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CAPT'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro FROM Captura WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'GES'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @RamaID = RamaID, @FechaRegistro = FechaRegistro FROM Gestion WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CP'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro  FROM CP WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PCP'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro  FROM PCP WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PROY'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Proyecto WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'ORG'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Organiza WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'RE'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Recluta WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'ISL'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM ISL WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'CONT'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Importe = Importe, @FechaRegistro = FechaRegistro FROM Cont WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PROD'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @Importe = Importe, @FechaRegistro = FechaRegistro FROM Prod WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'INV'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FormaEnvio = FormaEnvio, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @Importe = Importe, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Inv WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'PC'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM PC WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'OFER'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Oferta WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'NOM'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = NULL,       @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Nomina WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'RH'    SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM RH WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'ASIS'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = NULL,     @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Moneda = Moneda, @TipoCambio = TipoCambio, @FechaRegistro = FechaRegistro FROM Asiste WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO')) ELSE
IF @Modulo = 'EMB'   SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @Condicion = Condicion, @Moneda = Moneda, @TipoCambio = TipoCambio, @CtaDinero = CtaDinero, @Importe = Importe, @Impuestos = Impuestos, @Vencimiento = Vencimiento, @FechaRegistro = FechaRegistro FROM Embarque WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO'))
IF @Modulo = 'SAUX'  SELECT @ID = ID, @OrigenTipo = OrigenTipo, @Origen = Origen, @OrigenID = OrigenID, @FechaEmision = FechaEmision, @FechaCancelacion = FechaCancelacion, @Ejercicio = Ejercicio, @Periodo = Periodo, @Empresa = Empresa, @Usuario = Usuario, @Proyecto = Proyecto, @Concepto = Concepto, @Referencia = Referencia, @Sucursal = Sucursal, @Mov = Mov, @MovID = MovID, @Estatus = Estatus, @Situacion = Situacion, @SituacionFecha = SituacionFecha, @SituacionUsuario = SituacionUsuario, @SituacionNota = SituacionNota, @UEN = UEN, @Observaciones = Observaciones, @UltimoCambio = UltimoCambio, @FechaRegistro = FechaRegistro  FROM SAUX WITH(NOLOCK) WHERE ID = @ID OR (Empresa = ISNULL(@Empresa, Empresa) AND Mov = @Mov AND MovID = @MovID AND Estatus NOT IN ('SINAFECTAR', 'BORRADOR', 'EMAIL', 'CONFIRMAR', 'CANCELADO'))
SELECT @Total = ISNULL(@Importe, 0.0) + ISNULL(@Impuestos, 0.0) - ISNULL(@Retenciones, 0.0)
SELECT @MovTipo = Clave FROM MovTipo WITH(NOLOCK) WHERE Modulo = @Modulo AND Mov = @Mov
RETURN
END

