SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSInsertarVentaRefacturarTemp
@Estacion   int

AS
BEGIN
INSERT VentaRefacturarTemp(
Estacion,  ID, Empresa, Mov, MovID)
SELECT
@Estacion, ID, Empresa, Mov, MovID
FROM VentaRefacturar WITH (NOLOCK)
WHERE ID IN(SELECT ID FROM ListaID WITH (NOLOCK) WHERE Estacion = @Estacion)
AND ID NOT IN(SELECT ID FROM VentaRefacturarTemp WITH (NOLOCK) WHERE Estacion = @Estacion)
END

