SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSBorrarMovimientos

AS
BEGIN
DELETE FROM POSL
DELETE FROM POSLCobro
DELETE FROM POSLVenta
DELETE FROM POSVentaCobro
DELETE FROM POSLSerieLote
DELETE FROM POSLValidarDevolucion
DELETE FROM POSLAuxiliar
DELETE FROM POSLArtSeleccionado
DELETE FROM POSLAccion
DELETE FROM POSEstatusCaja
DELETE FROM POSLPorCobrar
DELETE FROM POSLPorCobrarD
DELETE FROM POSOfertaFormaPago
DELETE FROM POSLDenominacion
DELETE FROM POSFechaCierre
DELETE FROM POSEstatusCajasCierre
DELETE FROM POSHistMoratorios
DELETE FROM POSValeSerie
DELETE FROM POSLDILog
DELETE FROM POSLDIMonedero
DELETE FROM POSLDIMonederoSaldoFavor
DELETE FROM POSJobErrores
DELETE FROM POSReporteTicket
UPDATE POSC SET Consecutivo = 0
END

