SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSVFAFormaPago
@Codigo		varchar(50),
@ID			varchar(36)

AS
BEGIN
DECLARE
@FormaPago	varchar(50),
@Forma		varchar(50),
@Caja	    varchar(10),
@Ok			int
SELECT @Caja = CtaDinero
FROM POSL WITH (NOLOCK)
WHERE ID = @ID
IF ISNULL((SELECT Abierto FROM POSEstatusCaja WITH (NOLOCK) WHERE Caja = @Caja),0) <> 1
SELECT @Ok = 30440
SELECT @FormaPago = FormaPago
FROM CB WITH (NOLOCK)
WHERE CB.Codigo = @Codigo
IF @Ok IS NULL AND NULLIF(@FormaPago,'') IS NOT NULL AND EXISTS(SELECT * FROM POSVFAFormaPago WITH (NOLOCK) WHERE FormaPago = @FormaPago)
SELECT @Forma   = @FormaPago
SELECT @Forma
END

