SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSTotales
@Filtro			varchar(255),
@Posicion		float

AS
BEGIN
DECLARE
@TAB				char(2),
@SUBTOTALText		varchar(50),
@DESCUENTOText		varchar(50),
@IMPUESTOSTex		varchar(50)
SET @TAB = '<BR>'
SET @SUBTOTALText = 'SUBTOTAL'
SET @DESCUENTOText = 'DESCUENTO'
SET @IMPUESTOSTex = 'IMPUESTOS'
EXEC spExtraerDato  @Filtro OUTPUT, @SUBTOTALText OUTPUT, @TAB
EXEC spExtraerDato  @Filtro OUTPUT, @DESCUENTOText OUTPUT, @TAB
EXEC spExtraerDato  @Filtro OUTPUT, @IMPUESTOSTex OUTPUT, @TAB
IF @Posicion = 1
SELECT SubTotal = '$ '+SUBSTRING(@SUBTOTALText,PATINDEX('%$%',@SUBTOTALText)+1,50)
IF @Posicion = 2
SELECT Descuento = '$ '+SUBSTRING(@DESCUENTOText,PATINDEX('%$%',@DESCUENTOText)+1,50)
IF @Posicion = 3
SELECT Impuestos = '$ '+SUBSTRING(@IMPUESTOSTex,PATINDEX('%$%',@IMPUESTOSTex)+1,50)
END

