SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSEliminarMov
@IDPOS		varchar(36)

AS
BEGIN
DECLARE
@Host       varchar(20),
@Caja		varchar(10)
SELECT @Host = p.Host , @Caja = p.Caja
FROM POSL p WITH (NOLOCK)
WHERE p.ID = @IDPOS
DELETE FROM POSLAccion WHERE Host = @Host AND Caja = @Caja
END

