SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSUsuarioAutoriza
@ID			varchar(36),
@Usuario	varchar(10)

AS
BEGIN
UPDATE POSL
SET UsuarioAutoriza = @Usuario
WHERE ID = @ID
END

