SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSUsuarioInsertarAccion
@Estacion     int,
@Usuario      varchar(10)

AS
BEGIN
INSERT POSUsuarioAccion (
Usuario, Accion)
SELECT
Usuario, Accion
FROM POSUsuarioAccionTemp WITH (NOLOCK)
WHERE Estacion = @Estacion
AND ID IN(SELECT ID FROM ListaID WITH (NOLOCK)  WHERE Estacion = @Estacion)
END

