SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER PROCEDURE spPOSCerrarPOS
@ID		varchar(36)

AS
BEGIN
EXEC spPOSMovEliminar NULL, NULL, NULL, NULL, @ID, NULL, NULL, NULL, NULL, NULL, 0
END

