SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER PROCEDURE [dbo].[xpConfigSQL]
AS
BEGIN
	SET DATEFIRST 7
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET LOCK_TIMEOUT - 1
	SET NOCOUNT ON
	SET IMPLICIT_TRANSACTIONS OFF
	RETURN
END
GO