SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ArtExistenciaNeta

AS
SELECT
Empresa Empresa,
Cuenta Articulo,
Grupo Almacen,
Moneda,
Sum(s.SaldoU*r.Factor) Existencia
FROM SaldoU s
JOIN Rama r  ON s.Rama = r.Rama AND s.Rama IN ('INV', 'VMOS')
GROUP BY
Empresa, Cuenta, Grupo, Moneda

