SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ArtIntelisisService
AS
SELECT ArtCosto.Sucursal, ArtCosto.Empresa,  ArtCosto.UltimoCosto, ArtCosto.CostoPromedio, ArtCosto.UltimoCostoSinGastos, Art.*
FROM Art Art LEFT OUTER JOIN ArtCosto ArtCosto
ON Art.Articulo = ArtCosto.Articulo

