SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW ArtVtasMostrador

AS
SELECT
s.Empresa Empresa,
s.Cuenta Articulo,
s.Grupo Almacen,
sum(s.SaldoU) PorProcesar
FROM SaldoU s
JOIN Rama r ON s.Rama=r.Rama
WHERE
r.Rama='VMOS'
GROUP BY
s.Empresa, s.Cuenta, s.Grupo

