SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW CFDVentaD AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,VentaD.ID))))) + RTRIM(LTRIM(CONVERT(varchar,VentaD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,VentaD.Renglon))))) + RTRIM(LTRIM(CONVERT(varchar,VentaD.Renglon))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,VentaD.RenglonSub))))) + RTRIM(LTRIM(CONVERT(varchar,VentaD.RenglonSub))) +
REPLICATE(' ',50)
OrdenExportacion,
Venta.Cliente VentaCliente,
VentaD.ID,
VentaD.Cantidad - ISNULL(VentaD.CantidadObsequio,0.0) VentaDCantidad,
VentaD.CantidadInventario VentaDCantidadInventario,
VentaD.Unidad VentaDUnidad,
Unidad.Clave UnidadClave,
VentaD.Articulo VentaDArticulo,
dbo.fnQueCodigo(EmpresaCFD.EAN13, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) EAN13,
dbo.fnQueCodigo(EmpresaCFD.SKU, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) SKUCliente,
dbo.fnQueCodigo(EmpresaCFD.SKUEmpresa, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) SKUEmpresa,
dbo.fnQueCodigo(EmpresaCFD.DUN14, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) DUN14,
Art.Descripcion1 VentaDDescripcion,
Art.Descripcion2 VentaDDescripcion2,
Art.TipoEmpaque ArtTipoEmpaque,
CASE WHEN  Ecfg.VentaPrecioMoneda =1 then
CASE WHEN Vtc.Precio IS NULL THEN 0.0 ELSE(( (Vtc.Precio*dbo.fneDocVentaFactorPrecio(VentaD.ID, VentaD.Renglon, VentaD.RenglonSub))* ISNULL(VentaD.PrecioTipoCambio,1.0))/Venta.TipoCambio)* dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) END
ELSE
CASE WHEN Vtc.Precio IS NULL THEN 0.0 ELSE( (Vtc.Precio*dbo.fneDocVentaFactorPrecio(VentaD.ID, VentaD.Renglon, VentaD.RenglonSub)))* dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) END
END  VentaDPrecio ,
CASE WHEN  Ecfg.VentaPrecioMoneda =1 then
CASE WHEN Vtc.PrecioTotal IS NULL THEN 0.0 ELSE (((Vtc.PrecioTotal*dbo.fneDocVentaFactorPrecio(VentaD.ID, VentaD.Renglon, VentaD.RenglonSub))*ISNULL(VentaD.PrecioTipoCambio,1.0))/Venta.TipoCambio)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) END
ELSE
CASE WHEN Vtc.PrecioTotal IS NULL THEN 0.0 ELSE ((Vtc.PrecioTotal*dbo.fneDocVentaFactorPrecio(VentaD.ID, VentaD.Renglon, VentaD.RenglonSub)))*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) END
END  VentaDPrecioTotal,
Vtc.DescuentoLinea*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDDescuentoLinea,
VentaD.DescuentoImporte*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDDescuentoImporte,
vtc.Impuesto1 ventaDImpuesto1,
vtc.Impuesto2 ventaDImpuesto2,
vtc.Importe*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImporte,
(Vtc.Importe/Vtc.Cantidad)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImporteUnitario,
vtc.DescuentoLineal*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDDescLineal,
vtc.DescuentosTotales*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDDescuentosTotales,
vtc.ImporteSobrePrecio*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImporteSobrePrecio,
vtc.SubTotal*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDSubTotal,
(vtc.SubTotal/Vtc.Cantidad)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDSubTotalUnitario,
vtc.Impuesto1Total*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImpuesto1Total,
vtc.Impuesto2Total*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImpuesto2Total,
vtc.Impuestos*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImpuestos,
vtc.ImporteTotal*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDImporteTotal,
vtc.TotalNeto*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) VentaDTotalNeto,
TipoEmpaque.Clave TipoEmpaqueClave,
TipoEmpaque.Tipo TipoEmpaqueTipo,
VentaD.Renglon VentaDRenglon,
VentaD.RenglonSub VentaDRenglonSub,
VentaD.RenglonID VentaDRenglonID,
VentaD.RenglonTipo VentaDRenglonTipo,
VentaD.Almacen VentaDAlmacen,
VentaD.EnviarA VentaDEnviarA,
VentaD.Codigo VentaDCodigo,
VentaD.SubCuenta VentaDSubCuenta,
VentaD.PrecioSugerido VentaDPrecioSugerido,
VentaD.DescuentoTipo VentaDDescuentoTipo,
VentaD.Impuesto3 VentaDImpuesto3,
VentaD.DescripcionExtra VentaDDescripcionExtra,
VentaD.Costo VentaDCosto,
VentaD.CostoActividad VentaDCostoActividad,
VentaD.Paquete VentaDPaquete,
VentaD.ContUso VentaDContUso,
VentaD.Comision VentaDComision,
VentaD.Aplica VentaDAplica,
VentaD.AplicaID VentaDAplicaID,
VentaD.CantidadPendiente VentaDCantidadPendiente,
VentaD.CantidadReservada VentaDCantidadReservada,
VentaD.CantidadCancelada VentaDCantidadCancelada,
VentaD.CantidadOrdenada VentaDCantidadOrdenada,
VentaD.CantidadEmbarcada VentaDCantidadEmbarcada,
VentaD.CantidadA VentaDCantidadA,
VentaD.Factor VentaDFactor,
VentaD.SustitutoArticulo VentaDSustitutoArticulo,
VentaD.SustitutoSubCuenta VentaDSustitutoSubCuenta,
VentaD.FechaRequerida VentaDFechaRequerida,
VentaD.HoraRequerida VentaDHoraRequerida,
VentaD.Instruccion VentaDInstruccion,
VentaD.Agente VentaDAgente,
VentaD.Departamento VentaDDepartamento,
VentaD.UltimoReservadoCantidad VentaDUltimoReservadoCantidad,
VentaD.UltimoReservadoFecha VentaDUltimoReservadoFecha,
VentaD.Sucursal VentaDSucursal,
VentaD.PoliticaPrecios VentaDPoliticaPrecios,
VentaD.SucursalOrigen VentaDSucursalOrigen,
VentaD.AutoLocalidad VentaDAutoLocalidad,
VentaD.UEN VentaDUEN,
VentaD.Espacio VentaDEspacio,
VentaD.CantidadAlterna VentaDCantidadAlterna,
VentaD.PrecioMoneda VentaDPrecioMoneda,
VentaD.PrecioTipoCambio VentaDPrecioTipoCambio,
VentaD.Estado VentaDEstado,
VentaD.ServicioNumero VentaDServicioNumero,
VentaD.AgentesAsignados VentaDAgentesAsignados,
VentaD.AFArticulo VentaDAFArticulo,
VentaD.ExcluirPlaneacion VentaDExcluirPlaneacion,
VentaD.Anexo VentaDAnexo,
VentaD.AjusteCosteo VentaDAjusteCosteo,
VentaD.CostoUEPS VentaDCostoUEPS,
VentaD.CostoPEPS VentaDCostoPEPS,
VentaD.UltimoCosto VentaDUltimoCosto,
VentaD.PrecioLista VentaDPrecioLista,
VentaD.DepartamentoDetallista VentaDDepartamentoDetallista,
VentaD.PresupuestoEsp VentaDPresupuestoEsp,
VentaD.Posicion VentaDPosicion,
VentaD.Puntos VentaDPuntos,
VentaD.CantidadObsequio VentaDCantidadObsequio,
VentaD.OfertaID VentaDOfertaID,
VentaD.ProveedorRef VentaDProveedorRef,
VentaD.TransferirA VentaDTransferirA,
VentaD.ArtEstatus VentaDArtEstatus,
VentaD.ArtSituacion VentaDArtSituacion,
VentaD.Tarima VentaDTarima,
VentaD.ExcluirISAN VentaDExcluirISAN,
VentaD.ContUso2 VentaDContUso2,
VentaD.ContUso3 VentaDContUso3,
VentaD.CostoEstandar VentaDCostoEstandar,
VentaD.ABC VentaDABC,
VentaD.OrdenCompra VentaDOrdenCompra,
VentaD.TipoImpuesto1 VentaDTipoImpuesto1,
VentaD.TipoImpuesto2 VentaDTipoImpuesto2,
VentaD.TipoImpuesto3 VentaDTipoImpuesto3,
VentaD.CostoPromedio VentaDCostoPromedio,
VentaD.CostoReposicion VentaDCostoReposicion,
VentaD.TipoComprobante VentaDTipoComprobante,
VentaD.SustentoComprobante VentaDSustentoComprobante,
VentaD.TipoIdentificacion VentaDTipoIdentificacion,
VentaD.DerechoDevolucion VentaDDerechoDevolucion,
VentaD.Establecimiento VentaDEstablecimiento,
VentaD.PuntoEmision VentaDPuntoEmision,
VentaD.SecuencialSRI VentaDSecuencialSRI,
VentaD.AutorizacionSRI VentaDAutorizacionSRI,
VentaD.VigenteA VentaDVigenteA,
VentaD.SecuenciaRetencion VentaDSecuenciaRetencion,
VentaD.Comprobante VentaDComprobante,
VentaD.FechaContableMov VentaDFechaContableMov,
VentaD.TipoRetencion1 VentaDTipoRetencion1,
VentaD.TipoRetencion2 VentaDTipoRetencion2,
VentaD.TipoRetencion3 VentaDTipoRetencion3,
VentaD.Retencion1 VentaDRetencion1,
VentaD.Retencion2 VentaDRetencion2,
VentaD.Retencion3 VentaDRetencion3,
vtc.ImporteDescuentoGlobal VentaDDescuentoGlobal
FROM VentaD JOIN Art
ON VentaD.Articulo = Art.Articulo JOIN VentaTCalc vtc
ON vtc.ID = VentaD.ID AND vtc.Renglon = VentaD.Renglon AND vtc.RenglonSub = VentaD.RenglonSub LEFT OUTER JOIN Unidad
ON Unidad.Unidad = VentaD.Unidad LEFT OUTER JOIN ArtProv
ON ArtProv.Proveedor = Art.Proveedor AND ArtProv.Articulo = Art.Articulo AND ISNULL(ArtProv.SubCuenta,'') = ISNULL(VentaD.SubCuenta,'') JOIN Venta 
ON Venta.ID = VentaD.ID LEFT OUTER JOIN EmpresaCFD
ON EmpresaCFD.Empresa = Venta.Empresa LEFT OUTER JOIN TipoEmpaque
ON Art.tipoEmpaque=TipoEmpaque.TipoEmpaque JOIN MovTipo mt
ON mt.Modulo = 'VTAS' AND mt.Mov = Venta.Mov LEFT OUTER JOIN EmpresaCfg Ecfg
ON Ecfg.Empresa = Venta.Empresa
UNION
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,Venta.ID))))) + RTRIM(LTRIM(CONVERT(varchar,Venta.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,'999999999999'))))) + RTRIM(LTRIM(CONVERT(varchar,'999999999999'))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,'0'))))) + RTRIM(LTRIM(CONVERT(varchar,'0'))) +
REPLICATE(' ',50)
OrdenExportacion,
Venta.Cliente VentaCliente,
Venta.ID,
'1' VentaDCantidad,
NULL AS VentaDCantidadInventario,
'No Aplica' AS VentaDUnidad,
NULL AS UnidadClave,
'ANTICIPO' AS VentaDArticulo,
NULL AS EAN13,
NULL AS SKUCliente,
NULL AS SKUEmpresa,
NULL AS DUN14,
'Anticipo Facturado' AS VentaDDescripcion,
NULL AS VentaDDescripcion2,
NULL AS ArtTipoEmpaque,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDPrecio,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDPrecioTotal,
NULL AS VentaDDescuentoLinea,
NULL AS VentaDDescuentoImporte,
((AnticiposImpuestos*100/(AnticiposFacturados-AnticiposImpuestos))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS ventaDImpuesto1,
NULL AS ventaDImpuesto2,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImporte,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImporteUnitario,
NULL AS VentaDDescLineal,
NULL AS VentaDDescuentosTotales,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImporteSobrePrecio,
((AnticiposFacturados-ISNULL(AnticiposImpuestos,0.0))*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDSubTotal,
NULL AS VentaDSubTotalUnitario,
((AnticiposImpuestos)*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImpuesto1Total,
NULL AS VentaDImpuesto2Total,
((AnticiposImpuestos)*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImpuestos,
((AnticiposFacturados)*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDImporteTotal,
((AnticiposFacturados)*-1)*dbo.fnCFDTipoCambioMN(Venta.TipoCambio, ISNULL(mt.SAT_MN, EmpresaCFD.SAT_MN)) AS VentaDTotalNeto,
NULL AS TipoEmpaqueClave,
NULL AS TipoEmpaqueTipo,
NULL AS VentaDRenglon,
NULL AS VentaDRenglonSub,
NULL AS VentaDRenglonID,
NULL AS VentaDRenglonTipo,
NULL AS VentaDAlmacen,
NULL AS VentaDEnviarA,
NULL AS VentaDCodigo,
NULL AS VentaDSubCuenta,
NULL AS VentaDPrecioSugerido,
NULL AS VentaDDescuentoTipo,
NULL AS VentaDImpuesto3,
NULL AS VentaDDescripcionExtra,
NULL AS VentaDCosto,
NULL AS VentaDCostoActividad,
NULL AS VentaDPaquete,
NULL AS VentaDContUso,
NULL AS VentaDComision,
NULL AS VentaDAplica,
NULL AS VentaDAplicaID,
NULL AS VentaDCantidadPendiente,
NULL AS VentaDCantidadReservada,
NULL AS VentaDCantidadCancelada,
NULL AS VentaDCantidadOrdenada,
NULL AS VentaDCantidadEmbarcada,
NULL AS VentaDCantidadA,
NULL AS VentaDFactor,
NULL AS VentaDSustitutoArticulo,
NULL AS VentaDSustitutoSubCuenta,
NULL AS VentaDFechaRequerida,
NULL AS VentaDHoraRequerida,
NULL AS VentaDInstruccion,
NULL AS VentaDAgente,
NULL AS VentaDDepartamento,
NULL AS VentaDUltimoReservadoCantidad,
NULL AS VentaDUltimoReservadoFecha,
NULL AS VentaDSucursal,
NULL AS VentaDPoliticaPrecios,
NULL AS VentaDSucursalOrigen,
NULL AS VentaDAutoLocalidad,
NULL AS VentaDUEN,
NULL AS VentaDEspacio,
NULL AS VentaDCantidadAlterna,
NULL AS VentaDPrecioMoneda,
NULL AS VentaDPrecioTipoCambio,
NULL AS VentaDEstado,
NULL AS VentaDServicioNumero,
NULL AS VentaDAgentesAsignados,
NULL AS VentaDAFArticulo,
NULL AS VentaDExcluirPlaneacion,
NULL AS VentaDAnexo,
NULL AS VentaDAjusteCosteo,
NULL AS VentaDCostoUEPS,
NULL AS VentaDCostoPEPS,
NULL AS VentaDUltimoCosto,
NULL AS VentaDPrecioLista,
NULL AS VentaDDepartamentoDetallista,
NULL AS VentaDPresupuestoEsp,
NULL AS VentaDPosicion,
NULL AS VentaDPuntos,
NULL AS VentaDCantidadObsequio,
NULL AS VentaDOfertaID,
NULL AS VentaDProveedorRef,
NULL AS VentaDTransferirA,
NULL AS VentaDArtEstatus,
NULL AS VentaDArtSituacion,
NULL AS VentaDTarima,
NULL AS VentaDExcluirISAN,
NULL AS VentaDContUso2,
NULL AS VentaDContUso3,
NULL AS VentaDCostoEstandar,
NULL AS VentaDABC,
NULL AS VentaDOrdenCompra,
NULL AS VentaDTipoImpuesto1,
NULL AS VentaDTipoImpuesto2,
NULL AS VentaDTipoImpuesto3,
NULL AS VentaDCostoPromedio,
NULL AS VentaDCostoReposicion,
NULL AS VentaDTipoComprobante,
NULL AS VentaDSustentoComprobante,
NULL AS VentaDTipoIdentificacion,
NULL AS VentaDDerechoDevolucion,
NULL AS VentaDEstablecimiento,
NULL AS VentaDPuntoEmision,
NULL AS VentaDSecuencialSRI,
NULL AS VentaDAutorizacionSRI,
NULL AS VentaDVigenteA,
NULL AS VentaDSecuenciaRetencion,
NULL AS VentaDComprobante,
NULL AS VentaDFechaContableMov,
NULL AS VentaDTipoRetencion1,
NULL AS VentaDTipoRetencion2,
NULL AS VentaDTipoRetencion3,
NULL AS VentaDRetencion1,
NULL AS VentaDRetencion2,
NULL AS VentaDRetencion3,
NULL AS VentaDDescuentoGlobal
FROM Venta
JOIN EmpresaCFD ON Venta.Empresa = EmpresaCFD.Empresa
JOIN MovTipo mt ON mt.Modulo = 'VTAS' AND mt.Mov = Venta.Mov
WHERE AnticiposFacturados IS NOT NULL
UNION
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,VentaD.ID))))) + RTRIM(LTRIM(CONVERT(varchar,VentaD.ID))) +
REPLICATE('0',12-LEN(RTRIM(LTRIM(CONVERT(varchar,Ventad.Renglon+'90000000'))))) + RTRIM(LTRIM(CONVERT(varchar,Ventad.Renglon+'90000000'))) +
REPLICATE('0',7-LEN(RTRIM(LTRIM(CONVERT(varchar,VentaD.RenglonSub))))) + RTRIM(LTRIM(CONVERT(varchar,VentaD.RenglonSub))) +
REPLICATE(' ',50)
OrdenExportacion,
Venta.Cliente VentaCliente,
VentaD.ID,
VentaD.CantidadObsequio VentaDCantidad,
VentaD.CantidadInventario VentaDCantidadInventario,
VentaD.Unidad VentaDUnidad,
Unidad.Clave UnidadClave,
VentaD.Articulo VentaDArticulo,
dbo.fnQueCodigo(EmpresaCFD.EAN13, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) EAN13,
dbo.fnQueCodigo(EmpresaCFD.SKU, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) SKUCliente,
dbo.fnQueCodigo(EmpresaCFD.SKUEmpresa, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) SKUEmpresa,
dbo.fnQueCodigo(EmpresaCFD.DUN14, VentaD.Articulo, VentaD.SubCuenta, VentaD.Codigo, Venta.Cliente) DUN14,
Art.Descripcion1 VentaDDescripcion,
Art.Descripcion2 VentaDDescripcion2,
Art.TipoEmpaque ArtTipoEmpaque,
0.0 VentaDPrecio ,
0.0 VentaDPrecioTotal,
0.0 VentaDDescuentoLinea,
0.0 VentaDDescuentoImporte,
vtc.Impuesto1 ventaDImpuesto1,
vtc.Impuesto2 ventaDImpuesto2,
0.0 VentaDImporte,
0.0 VentaDImporteUnitario,
0.0 VentaDDescLineal,
0.0 VentaDDescuentosTotales,
0.0 VentaDImporteSobrePrecio,
0.0 VentaDSubTotal,
0.0 VentaDSubTotalUnitario,
0.0 VentaDImpuesto1Total,
0.0 VentaDImpuesto2Total,
0.0 VentaDImpuestos,
0.0 VentaDImporteTotal,
0.0 VentaDTotalNeto,
TipoEmpaque.Clave TipoEmpaqueClave,
TipoEmpaque.Tipo TipoEmpaqueTipo,
VentaD.Renglon VentaDRenglon,
VentaD.RenglonSub VentaDRenglonSub,
VentaD.RenglonID VentaDRenglonID,
VentaD.RenglonTipo VentaDRenglonTipo,
VentaD.Almacen VentaDAlmacen,
VentaD.EnviarA VentaDEnviarA,
VentaD.Codigo VentaDCodigo,
VentaD.SubCuenta VentaDSubCuenta,
VentaD.PrecioSugerido VentaDPrecioSugerido,
VentaD.DescuentoTipo VentaDDescuentoTipo,
VentaD.Impuesto3 VentaDImpuesto3,
VentaD.DescripcionExtra VentaDDescripcionExtra,
VentaD.Costo VentaDCosto,
VentaD.CostoActividad VentaDCostoActividad,
VentaD.Paquete VentaDPaquete,
VentaD.ContUso VentaDContUso,
VentaD.Comision VentaDComision,
VentaD.Aplica VentaDAplica,
VentaD.AplicaID VentaDAplicaID,
VentaD.CantidadPendiente VentaDCantidadPendiente,
VentaD.CantidadReservada VentaDCantidadReservada,
VentaD.CantidadCancelada VentaDCantidadCancelada,
VentaD.CantidadOrdenada VentaDCantidadOrdenada,
VentaD.CantidadEmbarcada VentaDCantidadEmbarcada,
VentaD.CantidadA VentaDCantidadA,
VentaD.Factor VentaDFactor,
VentaD.SustitutoArticulo VentaDSustitutoArticulo,
VentaD.SustitutoSubCuenta VentaDSustitutoSubCuenta,
VentaD.FechaRequerida VentaDFechaRequerida,
VentaD.HoraRequerida VentaDHoraRequerida,
VentaD.Instruccion VentaDInstruccion,
VentaD.Agente VentaDAgente,
VentaD.Departamento VentaDDepartamento,
VentaD.UltimoReservadoCantidad VentaDUltimoReservadoCantidad,
VentaD.UltimoReservadoFecha VentaDUltimoReservadoFecha,
VentaD.Sucursal VentaDSucursal,
VentaD.PoliticaPrecios VentaDPoliticaPrecios,
VentaD.SucursalOrigen VentaDSucursalOrigen,
VentaD.AutoLocalidad VentaDAutoLocalidad,
VentaD.UEN VentaDUEN,
VentaD.Espacio VentaDEspacio,
VentaD.CantidadAlterna VentaDCantidadAlterna,
VentaD.PrecioMoneda VentaDPrecioMoneda,
VentaD.PrecioTipoCambio VentaDPrecioTipoCambio,
VentaD.Estado VentaDEstado,
VentaD.ServicioNumero VentaDServicioNumero,
VentaD.AgentesAsignados VentaDAgentesAsignados,
VentaD.AFArticulo VentaDAFArticulo,
VentaD.ExcluirPlaneacion VentaDExcluirPlaneacion,
VentaD.Anexo VentaDAnexo,
VentaD.AjusteCosteo VentaDAjusteCosteo,
VentaD.CostoUEPS VentaDCostoUEPS,
VentaD.CostoPEPS VentaDCostoPEPS,
VentaD.UltimoCosto VentaDUltimoCosto,
VentaD.PrecioLista VentaDPrecioLista,
VentaD.DepartamentoDetallista VentaDDepartamentoDetallista,
VentaD.PresupuestoEsp VentaDPresupuestoEsp,
VentaD.Posicion VentaDPosicion,
VentaD.Puntos VentaDPuntos,
VentaD.CantidadObsequio VentaDCantidadObsequio,
VentaD.OfertaID VentaDOfertaID,
VentaD.ProveedorRef VentaDProveedorRef,
VentaD.TransferirA VentaDTransferirA,
VentaD.ArtEstatus VentaDArtEstatus,
VentaD.ArtSituacion VentaDArtSituacion,
VentaD.Tarima VentaDTarima,
VentaD.ExcluirISAN VentaDExcluirISAN,
VentaD.ContUso2 VentaDContUso2,
VentaD.ContUso3 VentaDContUso3,
VentaD.CostoEstandar VentaDCostoEstandar,
VentaD.ABC VentaDABC,
VentaD.OrdenCompra VentaDOrdenCompra,
VentaD.TipoImpuesto1 VentaDTipoImpuesto1,
VentaD.TipoImpuesto2 VentaDTipoImpuesto2,
VentaD.TipoImpuesto3 VentaDTipoImpuesto3,
VentaD.CostoPromedio VentaDCostoPromedio,
VentaD.CostoReposicion VentaDCostoReposicion,
VentaD.TipoComprobante VentaDTipoComprobante,
VentaD.SustentoComprobante VentaDSustentoComprobante,
VentaD.TipoIdentificacion VentaDTipoIdentificacion,
VentaD.DerechoDevolucion VentaDDerechoDevolucion,
VentaD.Establecimiento VentaDEstablecimiento,
VentaD.PuntoEmision VentaDPuntoEmision,
VentaD.SecuencialSRI VentaDSecuencialSRI,
VentaD.AutorizacionSRI VentaDAutorizacionSRI,
VentaD.VigenteA VentaDVigenteA,
VentaD.SecuenciaRetencion VentaDSecuenciaRetencion,
VentaD.Comprobante VentaDComprobante,
VentaD.FechaContableMov VentaDFechaContableMov,
NULL AS VentaDTipoRetencion1,
NULL AS VentaDTipoRetencion2,
NULL AS VentaDTipoRetencion3,
NULL AS VentaDRetencion1,
NULL AS VentaDRetencion2,
NULL AS VentaDRetencion3,
vtc.ImporteDescuentoGlobal VentaDDescuentoGlobal
FROM VentaD JOIN Art
ON VentaD.Articulo = Art.Articulo JOIN VentaTCalc vtc
ON vtc.ID = VentaD.ID AND vtc.Renglon = VentaD.Renglon AND vtc.RenglonSub = VentaD.RenglonSub LEFT OUTER JOIN Unidad
ON Unidad.Unidad = VentaD.Unidad LEFT OUTER JOIN ArtProv
ON ArtProv.Proveedor = Art.Proveedor AND ArtProv.Articulo = Art.Articulo AND ISNULL(ArtProv.SubCuenta,'') = ISNULL(VentaD.SubCuenta,'') JOIN Venta 
ON Venta.ID = VentaD.ID LEFT OUTER JOIN EmpresaCFD
ON EmpresaCFD.Empresa = Venta.Empresa LEFT OUTER JOIN TipoEmpaque
ON Art.tipoEmpaque=TipoEmpaque.TipoEmpaque JOIN MovTipo mt
ON mt.Modulo = 'VTAS' AND mt.Mov = Venta.Mov LEFT OUTER JOIN EmpresaCfg Ecfg
ON Ecfg.Empresa = Venta.Empresa
WHERE VentaD.CantidadObsequio >= 1

