SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW CFDVentaDescuentofdgt AS
SELECT
REPLICATE('0',20-LEN(RTRIM(LTRIM(CONVERT(varchar,ID))))) + RTRIM(LTRIM(CONVERT(varchar,ID))) +
REPLICATE(' ',12) +
REPLICATE(' ',7) +
REPLICATE(' ',50)
OrdenExportacion,
ID,
SUM(ImporteSinDL) Base,
CONVERT(DECIMAL(10,2),(fdgtTasa)) Tasa,
SUM(ISNULL(DescuentoLinealSinDL,0.0)) Importe
FROM CFDVentaDfdgt
GROUP BY ID, CONVERT(DECIMAL(10,2),(fdgtTasa))

