SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW CompraAux

AS
SELECT Art.Articulo,
Prov.Proveedor,
a.*
FROM Art
JOIN AuxiliarRU a ON Art.Articulo = a.Cuenta AND a.Rama = 'COMS'
JOIN Prov ON a.Grupo = Prov.Proveedor

