SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFACategoriaEntidadOpcional AS
SELECT
Categoria    = '(todos)'
UNION
SELECT
Categoria
FROM CteCat
UNION
SELECT
Categoria
FROM ProvCat

