SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFACtaSaldoEjercicioComp AS
SELECT
A.Empresa,
A.Ejercicio,
A.Periodo,
A.Cuenta,
A.Moneda,
ISNULL(SUM(ISNULL(A.Cargos,0.0)),0.0) 'Cargos',
ISNULL(SUM(ISNULL(A.Abonos,0.0)),0.0) 'Abonos',
ISNULL(SUM(ISNULL(A.Cargos,0.0)-ISNULL(A.Abonos,0.0)),0.0) 'Saldo'
FROM MFAAcum A
WHERE A.Rama = 'CONT'
GROUP BY A.Empresa, A.Ejercicio, A.Periodo, A.Cuenta, A.Moneda

