SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFAContacto AS
SELECT
u.Usuario				'Clave',
ISNULL(u.Nombre, '')	'Nombres',
''						'Apellidos',
''						'Puesto',
ISNULL(u.Telefono, '')	'Telefono',
ISNULL(u.eMail, '')		'eMail'
FROM Usuario u
WHERE Estatus = 'ALTA'

