SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFAGastoCxcPendientePreCalc AS
SELECT
g.ID,
p.Empresa,
p.Origen,
p.OrigenID,
YEAR(g.FechaEmision) Ejercicio,
MONTH(g.FechaEmision) Periodo
FROM Cxc p
JOIN Gasto g ON g.MovID = p.OrigenID AND g.Mov = p.Origen
WHERE p.OrigenTipo = 'GAS'
AND g.Estatus IN ('PENDIENTE','CONCLUIDO')

