SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFAMovTipoOpcional AS
SELECT
Modulo       = CONVERT(varchar(10),'(todos)'),
Mov          = '(todos)'
UNION ALL
SELECT
Modulo = CONVERT(varchar(10),Modulo),
Mov
FROM MovTipo

