SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW MFAVentaPendientePreCalc AS
SELECT
v.ID,
c.Empresa,
c.Origen,
c.OrigenID,
YEAR(v.FechaEmision) Ejercicio,
MONTH(v.FechaEmision) Periodo
FROM Cxc c
JOIN Venta v ON v.MovID = c.OrigenID AND v.Mov = c.Origen
WHERE c.OrigenTipo = 'VTAS'
AND v.Estatus IN ('PENDIENTE','CONCLUIDO')

