SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW pNetAgente
AS
SELECT LTRIM(RTRIM(Agente)) Agente, LTRIM(RTRIM(Nombre)) Nombre
FROM Agente WHERE Estatus = 'ALTA'

