SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW pNetCampanaSituacion
AS
SELECT
c.ID, cs.CampanaTipo, cs.Situacion, cs.Orden
FROM CampanaTipoSituacion cs
JOIN Campana c ON cs.CampanaTipo = c.CampanaTipo

