SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW POSSerieLoteTemp1

AS
SELECT p.ID,  ISNULL(SUM(p.Cantidad),0.0) Cantidad,p.Articulo,p.SubCuenta,p.RenglonID
FROM POSLVenta p
JOIN Art a ON p.Articulo = a.Articulo
WHERE  a.Tipo IN('SERIE','LOTE')
GROUP BY p.ID, p.Articulo,p.SubCuenta,p.RenglonID

