SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW UENPrefijoLista

AS
SELECT "UEN" = CASE
WHEN NULLIF(RTRIM(Nombre), '') IS NULL THEN CONVERT(char, UEN)
WHEN UPPER(SUBSTRING(Nombre, 1, 9)) = 'UEN ' THEN RTRIM(CONVERT(char, UEN))+' - '+RTRIM(SUBSTRING(Nombre, 10, LEN(Nombre)))
ELSE RTRIM(CONVERT(char, UEN))+' - '+RTRIM(Nombre) END
FROM UEN
WHERE Estatus <> 'BAJA'

