SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW VentaTCalc

AS
SELECT
v.ID,
v.Empresa,
v.SucursalOrigen,
v.Sucursal,
v.SucursalVenta,
v.Mov,
v.MovID,
v.Moneda,
v.TipoCambio,
v.Concepto,
v.Referencia,
v.Proyecto,
v.FechaRegistro,
v.FechaEmision,
d.FechaRequerida,
v.HoraRequerida,
v.FechaOriginal,
v.Prioridad,
v.Estatus,
v.Situacion,
v.SituacionFecha,
v.SituacionUsuario,
v.SituacionNota,
v.Cliente,
d.EnviarA,
v.Agente,
v.FormaEnvio,
v.Condicion,
v.Vencimiento,
v.Usuario,
v.Paquetes,
v.Observaciones,
v.Causa,
v.AnticiposFacturados,
v.Retencion,
v.Ejercicio,
v.Periodo,
v.FechaConclusion,
v.FechaEntrega,
v.EmbarqueEstado,
v.Peso,
v.Volumen,
v.ListaPreciosEsp,
v.ZonaImpuesto,
v.Extra,
v.ServicioArticulo,
v.ServicioSerie,
v.Clase,
v.SubClase,
d.Aplica,
d.AplicaID,
d.Renglon,
d.RenglonSub,
d.RenglonID,
d.RenglonTipo,
d.Almacen,
d.Codigo,
d.Articulo,
d.SubCuenta,
d.Unidad,
d.Precio,
d.DescuentoTipo,
d.DescuentoLinea,
d.Impuesto1,
d.Impuesto2,
d.Impuesto3,
d.Cantidad,
d.CantidadInventario,
d.Factor,
d.CantidadNeta,
d.CantidadFactor,
d.ReservadaFactor,
d.OrdenadaFactor,
d.PendienteFactor,
d.ImpuestosPorcentaje,
d.PoliticaPrecios,
d.Comision,
d.CantidadPendiente,
d.CantidadReservada,
d.CantidadOrdenada,
d.CantidadEmbarcada,
d.Costo,
d.AjusteCosteo,
d.CostoUEPS,
d.CostoPEPS,
d.UltimoCosto,
d.CostoEstandar,
d.PrecioLista,
d.CostoTotal,
d.CostoActividad,
d.CostoActividadTotal,
d.PrecioTotal,
d.Importe,
d.ContUso,
d.ContUso2,
d.ContUso3,
d.Espacio,
d.UEN,
d.ExcluirISAN,
d.Posicion,
d.PresupuestoEsp,
d.DescuentoLineal,
d.TipoImpuesto1,
d.TipoImpuesto2,
d.TipoImpuesto3,
d.Retencion1,
d.Retencion2,
d.Retencion3,
d.CostoPromedio,
d.CostoReposicion,
d.Ordencompra,
d.DescripcionExtra,
d.AnticipoFacturado,  
d.AnticipoMoneda, 
d.AnticipoTipoCambio, 
d.AnticipoRetencion, 
d.ImpIncPrecio,
d.ImpIncPreImporte,
d.ImpIncImporte,
d.Tarima, 
"ImpIncDescuentoLineal" = ImpIncImporte*(d.DescuentoLinea/100.0),
d.PrecioSinDL,
d.PreImporteSinDL,
d.ImporteSinDL,
"DescuentoLinealSinDL" = ImporteSinDL*(d.DescuentoLinea/100.0),
"ImporteDescuentoGlobal" = convert(float, ROUND((d.Importe*(CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END)/100.0), ISNULL(vs.RedondeoMonetarios,0))),
"DescuentosTotales"      = convert(float, ROUND((d.Importe*(CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END)/100.0) + ISNULL(d.DescuentoLineal, 0.0), ISNULL(vs.RedondeoMonetarios,0))),
"ImpIncDescuentosTotales"= convert(float, ROUND(((d.ImpIncImporte*(1.0 - (d.DescuentoLinea/100.0)))*(CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END)/100.0) + (ISNULL(ImpIncImporte,0.0)*(ISNULL(d.DescuentoLinea,0.0)/100.0)), ISNULL(vs.RedondeoMonetarios,0))),
"DescuentosTotalesSinDL" = convert(float, ROUND((d.ImporteSinDL*ISNULL(v.DescuentoGlobal, 0.0)/100.0) + (ISNULL(ImporteSinDL,0.0)*(ISNULL(d.DescuentoLinea,0.0)/100.0)), ISNULL(vs.RedondeoMonetarios,0))),
"ImporteSobrePrecio"     = convert(float, ROUND((d.Importe*ISNULL(v.SobrePrecio, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))),
"SubTotal"               = Convert(float, ROUND(dbo.fnSubTotal(d.Importe, (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio), ISNULL(vs.RedondeoMonetarios,0))),
"SubTotalSinDL"  = Convert(float, ROUND(dbo.fnSubTotal(d.ImporteSinDL,  0.0, v.SobrePrecio), ISNULL(vs.RedondeoMonetarios,0))), 
"ImpIncSubTotal"         = Convert(float, ROUND(dbo.fnSubTotal(d.ImpIncImporte,  0.0, v.SobrePrecio), ISNULL(vs.RedondeoMonetarios,0))),
"Impuesto1Total"         = Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (1.0+(ISNULL(d.Impuesto2BaseImpuesto1, 0.0)/100.0))*(ISNULL(Impuesto1Base, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))),
"Impuesto2Total"         = Convert(float, ROUND(dbo.fnSubTotal(d.Importe, (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (ISNULL(Impuesto2Base, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))),
"Impuesto3Total"         = ISNULL(ImpuestosImporte, 0.0),
"Impuestos" 	           = ISNULL(ImpuestosImporte, 0.0) + Convert(float, ROUND(dbo.fnSubTotal(d.Importe, (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (ISNULL(ImpuestosPorcentaje, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))),
"Retencion1Total"        = Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) *(ISNULL(d.Retencion1, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))), 
"Retencion2Total"        = Convert(float, ROUND((CASE WHEN d.Retencion2BaseImpuesto1 = 0 THEN dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) ELSE Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (1.0+(ISNULL(d.Impuesto2BaseImpuesto1, 0.0)/100.0))*(ISNULL(Impuesto1Base, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))) END) *(ISNULL(d.Retencion2, 0.0)/100.0), ISNULL(vs.RedondeoMonetarios,0))), 
"Retencion3Total"        = Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) *(ISNULL(d.Retencion3, 0.0)/100.0), dbo.fnRedondeoMonetarios())),
"ImporteTotal"           = ISNULL(ImpuestosImporte, 0.0) + Convert(float, ROUND(dbo.fnSubTotal(d.Importe, (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (1.0+(ISNULL(ImpuestosPorcentaje, 0.0)/100.0)), ISNULL(vs.RedondeoMonetarios,0))),
"TotalNeto"              = (ISNULL(ImpuestosImporte, 0.0)
+ Convert(float, ROUND(dbo.fnSubTotal(d.Importe, (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (1.0+(ISNULL(ImpuestosPorcentaje, 0.0)/100.0)), dbo.fnRedondeoMonetarios())-
ISNULL(Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) *(ISNULL(d.Retencion1, 0.0)/100.0), dbo.fnRedondeoMonetarios())),0.0)
-ISNULL(Convert(float, ROUND((CASE WHEN d.Retencion2BaseImpuesto1 = 0 THEN dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) ELSE Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) * (1.0+(ISNULL(d.Impuesto2BaseImpuesto1, 0.0)/100.0))*(ISNULL(Impuesto1Base, 0.0)/100.0), dbo.fnRedondeoMonetarios())) END) *(ISNULL(d.Retencion2, 0.0)/100.0), dbo.fnRedondeoMonetarios())),0.0)))
-ISNULL(Convert(float, ROUND(dbo.fnSubTotal(ISNULL(d.Importe,0.0), (CASE WHEN ISNULL(d.AnticipoFacturado, 0) = 0 THEN ISNULL(v.DescuentoGlobal,0.0) ELSE 0 END), v.SobrePrecio) *(ISNULL(d.Retencion3, 0.0)/100.0), dbo.fnRedondeoMonetarios())),0.0)
/* "TotalNeto"              = ISNULL(ImpuestosImporte, 0.0) + Convert(float, ROUND(dbo.fnSubTotal(d.Importe, v.DescuentoGlobal, v.SobrePrecio) * (1.0+(ISNULL(ImpuestosPorcentaje, 0.0)/100.0))
- dbo.fnR3((SELECT SUM(b.importe) FROM VentaDCalc b WHERE b.ID = v.ID),100,d.Importe)*ISNULL(v.AnticiposFacturados, 0.0)
- CASE WHEN dbo.fnEsPitex(v.Cliente) = 1
THEN Convert(float, dbo.fnSubTotal(d.Importe, v.DescuentoGlobal, v.SobrePrecio) * (1.0+(ISNULL(d.Impuesto2BaseImpuesto1, 0.0)/100.0))*(ISNULL(Impuesto1Base, 0.0)/100.0))
ELSE CASE WHEN d.Articulo ='FLETE'
THEN Convert(float, dbo.fnSubTotal(d.Importe, v.DescuentoGlobal, v.SobrePrecio) * (1.0+(ISNULL(d.Impuesto2BaseImpuesto1, 0.0)/100.0))*(ISNULL(Impuesto1Base, 0.0)/100.0))
ELSE 0 END
END, ISNULL(vs.RedondeoMonetarios,0)))*/
FROM Venta v
JOIN VentaDCalc d ON v.ID = d.ID
JOIN Version vs ON 1 = 1

