SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW VerSincroISSolicitud

AS
SELECT CONVERT(varchar(36), Solicitud) AS Solicitud,
Tipo,
SucursalOrigen,
SucursalDestino,
FechaEnvio,
FechaRecibo,
Estatus
FROM SincroISSolicitud

