SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW VerSincroISOk

AS
SELECT CONVERT(varchar(36), Conversacion) AS Conversacion,
Fecha,
TipoMensaje,
CONVERT(varchar(max), Datos) AS Datos,
DatosRef,
Ok,
OkRef
FROM SincroISOk

