SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW VistaServiciosG3
AS
SELECT n.ID, s.Servicio as Modulo, n.NombreCSV, n.Qry, Params, s.Estatus
FROM ServiciosG3 s
LEFT JOIN ServiciosG3Detalle sd ON sd.ID = s.ID
LEFT JOIN NominaG4CFG n on n.ID = sd.IdArchivosCSV
WHERE s.Estatus = 1 AND ISNULL(sd.Estatus, 1) = 1

