SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW dbo.vwAgenteCtePNET
AS
SELECT C.Nombre, A.Cliente, U.Usuario
FROM Cte C WITH(NOLOCK, INDEX(Nombre))
JOIN AgenteCte A ON A.Cliente = C.Cliente
JOIN Usuario U ON A.Agente = U.DefAgente

