SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW vwSWPersonal_ConsultaSol
AS
SELECT Mov,
MovID,
(RTrim(Mov) + ' ' + RTrim(MovID)) as Movimiento,
Titulo,
FechaEmision,
Estatus,
Prioridad,
Personal
FROM Soporte

