SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
SET NOCOUNT ON
SET IMPLICIT_TRANSACTIONS OFF
GO
ALTER VIEW dbo.WMSTarimaMovPendiente
AS
SELECT d.Tarima
FROM TMAD d
JOIN TMA a
ON a.ID = d.ID
JOIN MovTipo m
ON m.Mov = a.Mov
AND m.Modulo = 'TMA'
WHERE a.Estatus IN ('PENDIENTE', 'SINAFECTAR')
AND m.Clave IN ('TMA.OSUR', 'TMA.TSUR','TMA.OPCKTARIMA','TMA.PCKTARIMATRAN','TMA.OPCKTARIMA')
UNION
SELECT d.Tarima
FROM TMAD d
JOIN TMA a
ON a.ID = d.ID
JOIN MovTipo m
ON m.Mov = a.Mov
AND m.Modulo = 'TMA'
WHERE a.Estatus IN ('PENDIENTE', 'SINAFECTAR')
AND m.Clave IN ('TMA.SRADO', 'TMA.SADO', 'TMA.ORADO', 'TMA.OADO','TMA.PCKTARIMATRAN','TMA.OPCKTARIMA')
AND d.Procesado = 0

